- Source/ACE/Command/Handlers/AccountCommands.cs
This is my first pull request, please let me know if I'm doing this incorrectly.
Simple change I made to the accountcreate command to correct and prevent the issue I experienced when setting up ACE.
The client always sends accounts as lowercase regardless of what the user types in the command line. The server itself resolves the difference and connects as well. The issue surfaces when attempting to create a character. That packet is sent, but no response is ever recv'd.
> Client and Server expects account in ace_auth to be lowercase only.

- Source/ACE/Network/Handlers/AuthenticationHandler.cs
Please use this PR if rejecting PR #34. this contains the fix to the server crash when an account is not created and a client tried to connect to the server using the invalid account.
this fix is already in PR #34 so if that one is accepted, reject this one.
> Fix for server crash when account does not exist for connecting client

- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/ICharacterDatabase.cs
The PropertiesBools doesn't always get set on character upon login, this change should correct that issue.
> Fix for LoadCharacterProperties

- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/ICharacterDatabase.cs
- Source/ACE.Entity/Character.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/WorldManager.cs
- Source/ACE/Network/Enum/SingleCharacterOption.cs
- Source/ACE/Network/Fragments/FragmentOpcode.cs
- Source/ACE/Network/GameAction/Actions/GameActionRemoveAllFriends.cs
- Source/ACE/Network/GameAction/Actions/GameActionSetSingleCharacterOption.cs
- Source/ACE/Network/GameAction/GameActionOpcode.cs
- Source/ACE/Network/Handlers/FriendsOldHandler.cs
/friends old just sends a chat packet saying that the command isn't used in the emu.
I also had to fix a bug in two WorldManager methods that I added in an earlier PR.  There was a scenario where the Session.Player was null and it was causing the LINQ query to throw an exception.
Appear Offline is actually part of a GameAction that is used for setting many different options.  The Handle method for it now just has a switch in it (there are ~52 options) for now but we may want to go to something else in the future as we add new features.
Resolves #72
> Implemented "/friends remove -all", "/friends old" and Appear Offline.

- Source/ACE/Command/CommandManager.cs
This change allows any command to work with quotes to better delimit some parameters.
An example of this would be for commands that require the use of a character name which has spaces in it such as Maia the Lawyer. 
The change results in the following command working as expected:
set-characteraccess "maia the laywer" admin
Another example this change would fix would be the eventual problem with teleto which it gets wired-up.
Without the change, the command reads like teleto maia the laywer and would try to teleport to the character named maia instead of the full name. teleto "maia the lawyer" then corrects this issue and finds the right player.
> Changed ParseCommand to support the use of quotes

- Source/ACE.Common/ConfigManager.cs
- Source/ACE/Command/Handlers/AccountCommands.cs
- Source/ACE/Config.json.example
- Source/ACE/Entity/Player.cs
Improved best of both worlds scenario.
Server operators have the choice to emulate access permissions via more complicated system used on official worlds or they can choose to use simplified account based permissions which would become the default install option for ACEmulator.
> Support easy permissions in ACEmulator

- Source/ACE.Entity/Enum/ChatMessageType.cs
- Source/ACE.Entity/Enum/GroupChatType.cs
- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Network/GameAction/Actions/GameActionAddChannel.cs
- Source/ACE/Network/GameAction/Actions/GameActionChannelIndex.cs
- Source/ACE/Network/GameAction/Actions/GameActionChannelList.cs
- Source/ACE/Network/GameAction/Actions/GameActionChatChannel.cs
- Source/ACE/Network/GameAction/Actions/GameActionRemoveChannel.cs
- Source/ACE/Network/GameAction/Actions/GameActionTalk.cs
- Source/ACE/Network/GameAction/Actions/GameActionTell.cs
- Source/ACE/Network/GameAction/GameActionOpcode.cs
- Source/ACE/Network/GameEvent/Events/GameEventChannelBroadcast.cs
- Source/ACE/Network/GameEvent/Events/GameEventChannelIndex.cs
- Source/ACE/Network/GameEvent/Events/GameEventChannelList.cs
- Source/ACE/Network/GameEvent/GameEventType.cs
- Source/ACE/Network/GameMessages/Messages/GameMessagePrivateUpdateBool.cs
Resurrected the various Admin global channels used by the Advocates, Sentinels, Envoys, and Admins, stubbed the @on and @off commands and added support for @index and @clist commands.
Some TODOs have been put into the code for when we get a plan in place for for db loading/saving of channel subscriptions, as well as properly set subscriptions for that matter.
> Add in support for the old global Admin channels

- Source/ACE.Common/ConfigManager.cs
- Source/ACE/Config.json.example
- Source/ACE/Network/Handlers/CharacterHandler.cs
- Source/ACE/Network/Packets/PacketOutboundReferral.cs
Allows a server operator to configure their external IP for clients connecting from the internet as well as allowing clients connecting on the intranet to use the local network IP address of the server remaining on local network instead of going out to come back in.
The options are configurable via config.json and set to false by default.
> Option to send Internal IP as World Host to client

- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/ConnectionListener.cs
- Source/ACE/Network/Handlers/AuthenticationHandler.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- Source/ACE/Network/NetworkBundle.cs
- Source/ACE/Network/NetworkSession.cs
- Source/ACE/Network/Session.cs
Fixed fragmentation logic; we should not fragment messages that do not fill a full packet. Removed NetworkSession.Flush as this change fixed all cases where that seemed needed. Fixed NETWORKDEBUG section which was missed by network refactor
> Fixed message fragmentation

- Source/ACE.Common/Cryptography/Hash32.cs
Fixed error in shift logic of Hash32, preventing certain packets from calculating correct checksum
> Fixed Hash32, which corrects Attribute raise issue

- Source/ACE.Entity/Character.cs
- Source/ACE.Entity/Enum/Skill.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionTrainSkill.cs
- Source/ACE/Network/GameAction/GameActionType.cs
Within this request I've sent code that will allow the client to attempt too spend skill credits. If enough skill credits are available, the server will grant the skill to the the character. If the skill credits are not available or the skill has already been trained, then the server makes sure to send the correct game messages with Skill.None, to keep the client from locking up.
On the bottom of the Skill.cs, I've added an extension that allows for skills with proper names, example:
`Sneak Attack` instead of `SneakAttack`.
> Feature: Spend Skill Credits

- Source/ACE.Common/ConfigManager.cs
- Source/ACE.DatLoader/DatManager.cs
- Source/ACE.Database/ChartDatabase.cs
Added Mono Path compatibility (Linux support) to the following objects by removing the prefixed slashes in file paths:
- ConfigManager
- Charts
- Dat Loading
Note: This was tested and working correctly on `Ubuntu 16.04`. No bugs were observed when play testing.
Installation Hint: The server currently requires _at least_ installing `mono-complete` with the `apt-get` package manager.
> Added Path support for Mono applications (Linux)

- Source/ACE.DatLoader/DatManager.cs
- Source/ACE/Config.json.example
Update to Yesterday's Path support PR. The path support push broke the loading of dats without trailing slashes in the config. Here are the changes in this PR that address this issue:
- Updated example DatFileDirectory with a trailing slash at the end of the value
- Changed DatLoader to use Path.Combine, trailing slash is no longer needed.
`ServerTime initialized to Date: Wintersebb 22, 28 P.Y.  Time: Warmtide
2017-03-22 10:04:22,672 INFO : Successfully opened C:\ACE\client_cell_1.dat file, containing 1 records
2017-03-22 10:04:22,781 INFO : Successfully opened C:\ACE\client_portal.dat file, containing 1 records`
> Dat Path Updates

- Source/ACE.Database.Tests/ConstructedStatementTests.cs
- Source/ACE.Database/Database.cs
- Source/ACE.Database/WorldDatabase.cs
- Renamed a function to cut down on confusion. Fixes an assumed typo in name for new function `ConstructStatement`.
> Renamed the new db statement constructor label

- Source/ACE/Entity/Player.cs
- Update Player.cs `SaveCharacter()` function to store the `Player.Position` in the Character data object, right before the object is is stored in the database. This allows the server to save the character's position on logout or after the player save interval has ended.
- Added a summary comment for `SaveCharacter`.
- Updated Code Style per StyleCop.
> Save Character Position to Database

- Source/ACE.Database/Database.cs
- Updated the `wherelist` text to include the proper SQL syntax, for a WHERE clause.
> Update: SQL Where Syntax for ConstructStatement

- Source/ACE.Entity/CharacterAbility.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/LandblockManager.cs
- Source/ACE/Network/GameAction/Actions/GameActionQueryHealth.cs
- Source/ACE/Network/GameAction/GameActionType.cs
- Source/ACE/Network/GameEvent/Events/GameEventUpdateHealth.cs
- Source/ACE/Network/GameEvent/GameEventType.cs
This is limited for Players currently but should be adjustable once creatures are in.
> Implements GameAction/Event for Update Health

- Database/Updates/Character/2017_03_26_character_positions_positiontype.sql
- Database/Updates/Character/2017_03_27_character_positions_change.sql
- Database/Updates/Character/2017_03_29_character_vw_character_positions.sql
- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/Database.cs
- Source/ACE.Database/ICharacterDatabase.cs
- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/Character.cs
- Source/ACE.Entity/Enum/PositionType.cs
- Source/ACE.Entity/Position.cs
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/LandblockManager.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- changelog.md
This huge PR is related to Issue #166. The code has been changed to allow more then one position type. A class was added for Character position types that match the requirements listed in the issue. A secondary Position Type class was added to match the client, provided by @LtRipley36706.
To work with the ORM code introduced during the developer meeting, I've attempted to copy the pseudo 1:1 mapping into `CharacterPosition.cs`. In order to allow for more then one position, the `Character.Position` member was changed to dictionary containing a list of character positions by type. `Player.Position` was changed to `Player.PhysicalPosition` and when the server decides to save the positions to the database, the data is saved through the ORM object in `CharacterPosition.cs`. 
There were a few …
> Feature: ORM Driven Character Positions for Issue #166

- Database/Updates/Character/2017_03_26_character_positions_positiontype.sql
- Database/Updates/Character/2017_03_27_character_positions_change.sql
- Changed `2017_03_27_character_positions_change.sql` and `2017_03_26_character_positions_positiontype.sql` to use AFTER instead of BEFORE, when aligning the column.  The `positionType` column has been moved after the `id` column.
> Fix: Reverted SQL syntax to use AFTER, instead of BEFORE

- Source/ACE/Entity/Landblock.cs
- changelog.md
- After performing some empirical visual client testing with:
`
float squaredDistance = player.Location.SquaredDistanceTo(obj.Location);
player.Session.Network.EnqueueSend(new GameMessageSystemChat(squaredDistance.ToString(), ChatMessageType.Broadcast));
`, I found that a static use distance of at least `4.9f` worked _well_. I did not change this float, but I am noting it here.
- I also changed the `Lifestone Use` text to blue.
> Reveresed the logic for the distance check on lifestone usage

- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/PhysicsData.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Factories/LootGenerationFactory.cs
- Source/ACE/Network/GameEvent/GameEventType.cs
- Source/ACE/Network/GameMessages/GameMessageOpcode.cs
- Source/ACE/Network/GameMessages/Messages/GameMessagePickupEvent.cs
- Source/ACE/Network/GameMessages/Messages/GameMessagePutObjectInContainer.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageRemoveObject.cs
This is a minor extension of the work I was doing previously, but it did turn up a number of good to know items.   
1.  When you are dropping an item, you have to increment the portal sequence - the client treats items being added to 3D space like a teleport.   It is on overloaded flag.   God, do I hate that.
1. There was some optimization code in player that was checking "check for a short circuit.  if we don't need to update, don't!"   This has a bug in it that I could not quite fix.   I commented it out for now with a big TODO.   It never sends an update on object create or update after the initial object creation.   We are missing updating the LastUpdatedTicks somewhere.
1. In Landblock - I added a lambda expression to omit sending the stop tracking message if we are the one putting …
> Inventory Part 2 - Create, Drop and Pickup

- Source/ACE.Entity/Position.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/BroadcastAction.cs
- Source/ACE/Entity/Events/BroadcastEventArgs.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionTeleToLifestone.cs
- Source/ACE/Network/GameAction/Actions/GameActionTeleToMarketplace.cs
- Source/ACE/Network/GameAction/GameActionType.cs
- Source/ACE/Network/GameAction/QueuedGameAction.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageUpdateMotion.cs
- changelog.md
Ideally this is merged after #226 if this acceptable for merging.
> MovementEvent Action Queue

- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/PhysicsData.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Factories/LootGenerationFactory.cs
- Source/ACE/Network/GameAction/Actions/GameActionDropItem.cs
- Source/ACE/Network/GameAction/Actions/GameActionPutItemInContainer.cs
- changelog.md
Can someone with more experience with Action Queue take a look at the file Landblock and the  case GameActionType.DropItem:       I don't want to refactor all of my stuff until someone can tell me if this looks correct.   It complies and works fine.   I would just like a sanity check.
> Update to use Action Queue - Requested Changes Made 4/14/2017

- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/ICharacterDatabase.cs
- Source/ACE.Entity/CharacterPositionExtensions.cs
- Source/ACE.Entity/Position.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- changelog.md
This code was created to address issue #242.
-Fixed bugs in `LandblockId` in position and server now resets the  position if missing.
-Added checks to prevent a missing location from crashing the server.
-Removed unnecessary `lastportal` recall position save, this is set on demand, this also prevents invalid data from entering the database.
Please give this a test by deleting a previously created character's position location (position type 1) and then try logging in, you should be at the current starting dungeon.
> Fix: Position missing update and LandblockId db object fix

- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Network/Extensions.cs
- changelog.md
This continues to address issue #246 
More things will need to be converted to PackedDWORD to fully squash the createobject errors.
> Bring WritePackedDWORD to ACE

- Source/ACE/Command/Handlers/DebugCommands.cs
- changelog.md
The `@reset-pos` command was removed in pr #243, but was re-added back in with Ripley's command text update commit 679b0814. If this is needed, please close this request; but I would like to remove this command too prevent invalid positions from being set as the `Location` position in the database.
> Removed @reset-pos again

- Source/ACE/Entity/Creature.cs
This was always true, due to a changes I made last night to the Creature Kill command. The changes made the Creatures also work like a player, but after I made this change, the types can now differentiate; allowing `@smite` and `@smite all` began to work correctly again.
> Fix IsDerivedPlayer logic to allow smite to work

- Database/Updates/World/009_2017_04_24_add_currentmotionstate.sql
- Source/ACE.DatLoader/Entity/ClothingBaseEffect.cs
- Source/ACE.DatLoader/FileTypes/ClothingTable.cs
- Source/ACE.Entity/BaseAceObject.cs
- Source/ACE.Entity/Position.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/DebugObject.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Factories/GenericObjectFactory.cs
- Source/ACE/Network/Motion/GeneralMotion.cs
- Source/AppVeyor/MySqlInstall.bat
- changelog.md
* Added currentMotionState to base_ace_object in ace_world database.
* Changed location in base_ace_object to an INT(10) in ace_world database.
* Changed vw_ace_creature_object and vw_ace_object to include currentMotionState.
* Added CurrentMotionState to BaseAceObject and linked it to currentMotionState.
* Added a method to GeneralMotion to convert from a byte array to GeneralMotion object.
* Added DebugObject to assist with building and testing out real objects for world.
* Changed GenericObjectFactory to spawn DebugObjects as a default if running server in DEBUG.
* Fixed Code Style issues within ClothingTable.cs and ClothingBaseEffect.cs in ACE.DatLoader.
* Changed Position to set Z to 0 to fix @tele command.
* Removed PlayScript.Create from landblock respawn section. Players should …
> Added currentMotionState and support within ACE

- Source/ACE.DatLoader/FileTypes/SetupModel.cs
- Source/ACE/Entity/Lifestone.cs
- changelog.md
Added a functional example of its usage to Lifestone.OnUse to properly take the model's radius and the object's use-radius into account when determining if a player is "close enough".
> Changed SetupModel.ReadFromDat function to be more user-friendly. 

- Source/ACE.Database/IWorldDatabase.cs
- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/BaseAceObject.cs
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Entity/CollidableObject.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/DebugObject.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Factories/LootGenerationFactory.cs
- changelog.md
Fixed
I fixed a lot of the issue with these two create object calls.    I modify some of the flags because the base ace object was made from a pcap - I think the logic is sound and it is how I had it working before.   I also put in some code to exclude the extra information from baseAceObject for portals, creatures and life stones.   We can expand that exclusion list if and when it is found necessary.
I added a new admin function cirand <typeId> that will allow you to easily test and exercise the ci function to insure it works for various itemTypes
> Fix for ci & create complete and tested.   Ready for merge if approved.  

- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/Character.cs
- Source/ACE.Entity/CreatureAbility.cs
- Source/ACE.Entity/CreatureVital.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Network/GameMessages/Messages/GameMessagePrivateUpdateVital.cs
Trying to take a small piece for my first commit -- hopefully this is reasonable.
Goal is to add basic functionality required for time based updates of creature's vitals (health, mana, stamina).  This is a subset of the challenge for issue #254 .  Current update rates do not reflect original game's update algorithm.
Summary of changes:
- Added setvital debug function -- sets a vital (hp mp stam) to a specified or relative value
- Added per-creature update function to landblock main loop
- Added vital update code per creature
- Added UI notification messages to player, so UI updates when vitals are changed.
I'm new to working on distributed teams via github, please let me know if there is anything I need to correct.
> Time-based updates to creature vitals

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/AceCharacter.cs
- Source/ACE.Entity/AceObject.cs
- Source/ACE.Entity/CreatureAbility.cs
- Source/ACE.Entity/CreatureSkill.cs
- Source/ACE/Entity/CollidableObject.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/DebugObject.cs
- Source/ACE/Entity/Door.cs
- Source/ACE/Entity/Lifestone.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/Portal.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Network/GameEvent/Events/GameEventPlayerDescription.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- changelog.md
Clean-up of backing state in game.  Primary focuses:
- Make persistent state of in-game objects to be backed by the AceObject
- Remove unneeded database fields from active state
- Stop in-game objects from redundantly writing to their AceObject.
Also fixes:
- Attribute2nd (vitals -- health/stam/mana) initializing incorrectly.
Still needs to be done:
- ORM interface cleanup.
> Cleanup backing AceObject

- Source/ACE.Common/ConfigManager.cs
- Source/ACE/Config.json.example
- Source/ACE/Managers/WorldManager.cs
- changelog.md
* Added a Config Setting and Max Allowed Sessions code, to allow configuration of the total concurrent connections.
This code was lost during the object-overhaul change: PR #345 -
* Changed the configuration sections to allow for the "MaxSessions" setting.
* There is a default value of 128.
* Check the Config.json.example for help.
> Re-Added Configuration for Maximum Allowed Sessions

- Source/ACE/Command/Handlers/DebugCommands.cs
- changelog.md
This code was lost during the object-overhaul switchover, from the PR #346 and was altered slightly to allow use from within the server console.
* Added a Helpful debug command for testing who is connected too your server.
* Can now be used from the console.
> Re-Added a debug command to list all players connected to the server.

- Source/ACE.Entity/AceObject.cs
- Source/ACE/Entity/DebugObject.cs
- Source/ACE/Entity/PhysicsData.cs
- Source/ACE/Entity/UsableObject.cs
- changelog.md
This code change corrects issues with AceObject, PhysicsData, DebugObject and UsableObject to make wielded items in database appear in world and attach mostly correct to their wielders. I say mostly correct as visually they look good, but all of the NPCs are static at this point and we're not setting the children flag on NPCs as well so there could be issues laying in wait for us when we get to movement for them which will require us to get that part working.
This works with data found in the last two ACE-World releases, no new export was required, although the latest release would be suggested as it fixes issues with landblock loading.
> Make NPCs in database wield items also in database

- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/DbManager.cs
- Source/ACE/Network/GameAction/Actions/GameActionSetCharacterOptions.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- Source/ACE/Network/Session.cs
- changelog.md
There is a bug in one of our latest patches, in which asynchronous saving races with loading, causing the game to sometimes (frequently) crash on player creation.  This patch causes that function (run in session network handler, so can block) to wait for the initial character creation DB save to complete before attempting login/load.
Also fixes issue in prior code in which the asynchronous saving loop would not stop when server shutdown was requested.
> Fix to asynchronous saving bug on character creation.

- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/WorldManager.cs
- Source/ACE/Network/GameAction/Actions/GameActionSetCharacterOptions.cs
- Source/ACE/Network/Session.cs
- changelog.md
My branch was causing a racy bug on logoff because I had not synchronized those operations with the server.  Those operations are now synchronized, as well as properly adding broadcasting for the logoff animation, and a timeout before the player is removed from world (while the logoff animation plays).
And uncommented learnspell (which now broadcasts the animation, so all can see you learn a spell).
> Fixed logoff crashing bug

- Source/ACE.Common/ConfigManager.cs
- Source/ACE/ACE.cs
- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Config.json.example
- Source/ACE/Managers/ServerManager.cs
- Source/ACE/Managers/WorldManager.cs
- Source/ACE/Network/Session.cs
- changelog.md
With these changes, there is now a way to stop the server after an interval has passed.
Stop the server after the interval set in the Config has Passed:
`@shutdown <shutdown text>`
Stop the Server immediately:
`@stop-now`
Cancel an in progress shutdown:
`@cancel-shutdown`
Change the seconds to wait until shutdown:
`@set-shutdown-interval <0-99999>`
There is also now a config change that adds an additional variable called `ShutdownInterval`. The goal of the variable is to tell the server how many seconds it will need to wait until shutdown. The maximum seconds allowed is 99999 and the default is 60.
This request has been worked on and tested since April, please let me know if you spot any issues. Previous iteration can be found here with additional concepts/scenarios: …
> Shutdown Controls

- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Managers/LandblockManager.cs
- Source/ACE/Managers/WorldManager.cs
- changelog.md
Bugs fixed:
- Player sticks when coming out of teleport (wasn't clearing requested positions properly from physics)
- Game sometimes crashes when transferring landblocks (Wasn't clearing player from old landblock properly)
- "glitch" in motion shortly after teleporting (was setting position after teleporting improperly).
> Fixed several movement related bugs

- Source/ACE.Entity/AceObject.cs
- changelog.md
* Changed from uint to ulong, to match the bigint/int64 data types.
This fix allows characters to once again level up correctly, along with allowing other properties to work.
> Fix: Incorrect data type when changing a bigint property that has previously been set

- Source/ACE/Factories/SpecialPortalObjectFactory.cs
- changelog.md
Someone other than me should check this PR in practice to see if it really is working, and that it isn't just a fluke that it works for me, before it is merged.  Should be able to summon multiple portals and they all should individually disappear in 15 seconds.
> Fix race in SpawnPortal when using ActionQueue and assign unique Id's to each Portal object

- Source/ACE.Database/CachingWorldDatabase.cs
- Source/ACE/Entity/Portal.cs
- changelog.md
The code works during my functional test, but I don't know if it was the correct way to fix it. Also, there seems to be a slight delay when using a another portal, after having failed a different portal's activation requirements. Example, with a character that is lower than 80, try to use the Eastwatch portal in the TN Annex. Player gets denied because of being too low a level. Next use the Danby's Output portal next to the Eastwatch one. There is a slight delay before teleport. Subsequent portals that don't block do not have a delay, until the next time the player doesn't pass the requirements of another portal.
> Review and possible merge: Fix portal requirements

- Source/ACE.Common/ConfigManager.cs
- Source/ACE.Database/CachingWorldDatabase.cs
- Source/ACE/Config.json.example
- Source/ACE/Managers/WorldManager.cs
- Source/ACE/Network/Enum/SessionState.cs
- Source/ACE/Network/Handlers/AuthenticationHandler.cs
- Source/ACE/Network/NetworkSession.cs
- Source/ACE/Network/Session.cs
- changelog.md
This is mostly for review, since @Zegeger has mentioned he created code to work with timeouts in issue #336, but I want to keep my server from crashing when 127 clients have connected, so I've implemented simple timeout testing code that is based on `ticks`.
In this code, sessions will timeout after 60 seconds of inactivity and be disconnected by the `WorldManager`.
> For Review Only: Added simple network session timeouts

- README.md
- changelog.md
We have had some contributors as well as people trying to install have issues.   Our computed columns require a newer version of mysql or mariadb.   Updated to reflect that.
> Update readme with minimum required database versions

- Source/ACE/Entity/MovementData.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionMoveToState.cs
- changelog.md
Basic support for animation broadcasts.  
- A client may now observe running/sidestepping/other animations/motion for another player
- FIXME: All animation speed data is just made-up.  Some of it appears correct, but I need to dig the formulas out of the client.
- FIXME/TODO: Some animations are broadcast multiple times (e.g. waving).  This is because we're receiving multiple requests form the client (possibly a networking error).  I should dedupe this, but I don't have animation timing information to do this.
> Basic support for Animation Broadcasts

- Source/ACE.Entity/AbilityFormulaAttribute.cs
- Source/ACE.Entity/CreatureVital.cs
- Source/ACE.Entity/Enum/Ability.cs
- Source/ACE.Entity/Enum/Properties/PropertyAttribute.cs
- Source/ACE.Entity/ICreatureXpSpendableStat.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionRaiseAbility.cs
- Source/ACE/Network/GameMessages/Messages/GameMessagePrivateUpdateAbility.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- changelog.md
Primary and secondary attributes can be raised correctly with xp again. Existing characters will have coord and quick exchanged as the enums for those abilities in the server are now aligned with the client.
Vital ticking wasn't touched yet, so it only starts during Player.Load
> Fixes to raising attributes

- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- changelog.md
`// TODO: Why does the client send a QueryItemMana action with a queryid of 0`
Looks like the client did this all the time, no reason seems apparent in retail pcaps, so killing this out for now
> Minor tweak to QueryItemMana

- Source/ACE/Network/Handlers/AuthenticationHandler.cs
- Source/ACE/Network/NetworkSession.cs
- Source/ACE/Network/Session.cs
- changelog.md
Set Ack delay initially to be 2 seconds.  Having the acks sent too early seems to impact connection reliability.
> Network fixes with inital Ack delay

- Source/ACE.Entity/Enum/Ability.cs
- Source/ACE/Network/ClientPacket.cs
- Source/ACE/Network/NetworkSession.cs
- Source/ACE/Network/Packet.cs
- Source/ACE/Network/PacketFragment.cs
- Source/ACE/Network/ServerPacket.cs
- changelog.md
* Rewrote packetizer code to fix incorrect multi-fragment messages (basically we shouldn't send optional headers when a single fragment fills the full packet)  
* In general this made the packetizer much cleaner and more organized  
* In the process I added support for preemptive tail sending.  Essentially for multifragment packets, the last fragment will likely be much smaller then the full packet size, so it could fit in an earlier message among other fragments.  We see this can occur in production network traces (eg the last index arrives as the first fragment of the message). Previously we did not do this, but now we can.
> Fix multifragment packetization logic

- Source/ACE/Factories/GeneratorFactory.cs
- changelog.md
This fixes a crash bug associated with picking up objects generated by generators. GUID change wasn't propagating to properties.
> Quick fix for proper GUID assignment on objects from Generators

- Source/ACE/Entity/Door.cs
- changelog.md
Added a minimum UseRadius to Doors. This prevents the radius being so small as to require you to be inside the door to open/close it.
> Added minimum UseRadius for Doors

- Database/Updates/World/10-03-2017-updateintprop46.sql
- Source/ACE.Entity/Enum/Properties/PropertyBool.cs
- Source/ACE.Entity/Enum/Properties/PropertyDataId.cs
- Source/ACE.Entity/Enum/Properties/PropertyDouble.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt64.cs
- Source/ACE.Entity/Enum/Properties/PropertyString.cs
- changelog.md
"These engines are the fastest in any tanks in the European Theater of Operations, forwards or backwards. You see, man, we like to feel we can get out of trouble, quicker than we got into it."   Oddball - Kelly's Heroes.
[Og II]
* Added update script to modify defaultCombatStance ace_object_properties_int to match change with @OptimShi changes of 10/02
* Rolled back [ServerOnly] attribute on enums.   I left the mechanism in place and tagged all over 9000 as such.   Our method for determining which of these are server only  this is not correct.   We can add these back when we fully understand which are truly not needed by the client.
> Retreat!   Fix for peace mode from unarmed

- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/Portal.cs
- changelog.md
Moved handling of Portals into the HandleOnCollide method and implemented MoveTo for OnUse for Portals.  Currently, OnUse also queues up portaling via a direct call to Portal.HandleOnCollide, which can be removed when collision is implemented.
> Portals update

- Source/ACE/Network/GameMessages/Messages/GameMessageDDDInterrogation.cs
Though the client doesn't seem to mind.
> DDDInterrogation uses 32 bit quantities, not 64 bit.

- Database/Updates/World/10-14-2017-fix-weenie-mmd-20630.sql
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionStackableMerge.cs
- Source/AppVeyor/MySqlInstall.bat
- changelog.md
* Added processing for merge items.
* Added script to update the burden, value and stack size of the weenie for MMD notes I used in testing.   20630 - value 250,000 burden 5 and stack size 1
* Cleaned up code, fixed a bug with drop item.
* This is work in progress, I have more to do, I am putting this up now so we StackOverflow or Ripley can take a look at the issue with vendor
Test steps:
- run update script on your WORLD database to set the values correctly, they are wrong.
- "@ci 20630" do this twice.   You will now have 2 MMD notes in your main pack that are not stacked.
- You can inspect each, you will see bu of 5, value of 250,000
- Stack them - check bu and value
- Split them - check bu and value
- You can log in or out, drop the notes and all saves as it should.
I have not tested …
> Mergers and Inquisitions: Added stack-able merge REVIEW ONLY Work in progress

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/Player.cs
- changelog.md
* Add the initial set of CoinValue in Container.cs to the value of contained Coins
* Modified item move, drop, and pickup methods to account for Pyreal changes, using StackOverflow's UpdateCurrencyClientCalculations();
> Fix coin value and pickup of stack-able items from landblock

- Source/ACE.Api.Host/Startup.cs
- Source/ACE.AuthApi.Host/Program.cs
- changelog.md
* Fix a typeo in ACE.AuthApi.Host, as it was attempting to start the API host in place of the AuthAPI host;
should be "var server = WebApp.Start<Startup>(url: ConfigManager.Config.AuthServer.Url);", not "var server = WebApp.Start<ACE.Api.Startup>(url: ConfigManager.Config.AuthServer.Url);"
Credit to Slushnas
> Fix TypeO in AuthApi.Host/Program.cs

- Source/ACE.Api.Common/JwtManager.cs
- Source/ACE.Api/Controllers/ServerController.cs
- Source/ACE.AuthApi.Host/Program.cs
- Source/ACE.Common/AuthServerConfiguration.cs
- Source/ACE/Config.json.example
- changelog.md
* @Slushnas found WebApp.Start error in ACE.AuthApi.Host: Changed ACE.Api.Startup to ACE.AuthApi.Startup to fix domain error.
* AuthServer Changes:
- AuthServer needs a publicly accessible address to point connecting clients if you're trying to use the server outside of a localhost/internal lan only environment.
- The current defaults basically point everything to `http://+:8001` which fails to resolve. So the following changes have been made..
- Changed AuthServer.Url to AuthServer.ListenUrl
- Added AuthServer.PublicUrl
- Typically, you'll leave the AuthServer.ListenUrl to the default, but you'll want to change AuthServer.PublicUrl to either of the following: 
* The externally accessible address of the AuthServer so that clients from the internet can authenticate.
OR
* localhost or the …
> Fix for AuthServer external access

- Source/ACE.Entity/Enum/EquipMask.cs
- changelog.md
Fixed bug with EquipMask enum that was causing Greaves/Lower Leg Armor not to appear on character
> EquipMask Enum Fix

- Source/ACE.Database/WorldDatabase.cs
- changelog.md
Forgot to recall the instance current location data and put it in AceObject.Location so that objects appear where they are supposed to.
> Fix Weenie Instance Position data load into AceObject

- Source/ACE.Entity/Enum/CombatMode.cs
- Source/ACE/Entity/Book.cs
- Source/ACE/Entity/Cow.cs
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/Door.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Lifestone.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/Portal.cs
- Source/ACE/Entity/Vendor.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Managers/WorldManager.cs
- changelog.md
Landblocks no longer act in parallel.  Any game-content updates done from a landblock need not worry about synchronizing with other landblocks, this should simplify the coding of the core game logic.
NOTE: The network packet parsing still happens in its own thread, so ActionChains are still required to move work from the network thread onto the landblock.
ActionChains are also still included for their uses delaying work (e.g. when waiting for an animation, or to reach a destination).
> Reducing threading in core & simplifying coding model

- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Player.cs
- changelog.md
Changed EquipTest debug command to utilize the index of a clothing table item and added an optional shade parameter
> EquipTest Updates

- Source/ACE/Network/PacketHeader.cs
Not important, just a little thing I noticed a while back,
Considering how C# handles constants, I don't think this could become an issue (even in the case system endian was reversed). Just a style issue, at most.
> Fix non-critical typo in hex constant.

- Source/ACE.DatLoader/FileTypes/Wave.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Entity/Line2.cs
- Source/ACE.Server/Entity/Mesh.cs
- Source/ACE.Server/Entity/Triangle.cs
This pull request is for the 2 Trello tasks:
https://trello.com/c/4ErxP7lc/90-implement-celllandblock-geometry-cache
https://trello.com/c/TxnqEnBH/85-celllandblockgetz-needs-rework
I'm still learning my way around the ACE project, so it's possible this code is not integrated in the correct location yet...
A LoadMesh() method has been added to Landblock.cs, which uses the Region file to determine the correct heights for the vertices. It loads the landblock grid as a triangle mesh, using a snippet of code from AC2D to ensure the cells are split between the correct vertices. I have verified in a few different locations that these splitters are being generated correctly, but I have no automated way of ensuring 100% accuracy across the entire map yet.
The GetZ() method has been implemented in …
> Implement CellLandblock geometry cache.

- Source/ACE.DatLoader/Entity/Frame.cs
- Source/ACE.DatLoader/Entity/SWVertex.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Entity/LandblockMesh.cs
- Source/ACE.Server/Entity/Mesh.cs
- Source/ACE.Server/Entity/ModelMesh.cs
- Source/ACE.Server/Entity/ModelPolygon.cs
- Source/ACE.Server/Entity/Polygon.cs
- Source/ACE.Server/Entity/StaticMesh.cs
- Source/ACE.Server/Entity/StaticMeshCache.cs
This PR is for loading the landblock objects / obstacles, buildings, and landblock weenies stored in the database
A lot of the code from the last PR in Landblock.cs and Mesh.cs has been moved to a new LandblockMesh.cs class. Mesh.cs is now a base class for both the triangle-based landblock meshes, and the new ModelMesh.cs. Model meshes are polygonal based, and have most of their data stored in a StaticMesh object, which points to a global cache for efficiency.
https://www.youtube.com/watch?v=X4c7VHJ6DHE
> Have Landblocks load all terrain, building, and generic obstacle data during start up and store it for use in the physics engine.

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Entity/LandblockMesh.cs
- Source/ACE.Server/Entity/ModelMesh.cs
- Source/ACE.Server/Entity/Polygon.cs
- Source/ACE.Server/Entity/Scenery.cs
- Source/ACE.Server/Physics/BoundingBox.cs
Here is the first attempt at the landscape scenery generation. It's performing the same calculations that the original client does to build the scenery objects, although it's still not matched up perfectly yet.
The scenery is defined on a per-cell basis, which gets mapped through the region file to the actual scenery data. Instead of placing individual shrubs and trees on each cell though, the game uses something akin to perlin noise generation to move scenery objects around the grid in a non-uniform way.
https://imgur.com/a/wyQRt
Todo:
- It appears there is more scenery generated than the original game, even though the functions should be matched up exactly with the client. I will need to investigate more to find out what could be causing any differences.
- Scenery items should not spawn …
> Have Landblocks load all scenery during start up and store it for use in the physics engine.

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Network/Session.cs
- changelog.md
* Adding /morph command for admins.
- The command was used to facilitate live ops by developers to play out story elements such as Martine wreaking havoc upon the lands.
- For some samples, you can try `martinelo`, `baelzharon`, `asheronlo`, `ayanbaqurdrunkenscholar`, `rabbitwhite`, `monougapaul`, or even `golemmegamagma`.
- Protip: If you do morph into a golem, press the b key ;)
The command usage is: `/morph [wcid or weenieClassName here]`
If successful, you will be logged out and when you enter the game again you'll be that creature
> 1000th Commit to ACE! Morph command for Admins/Liveops

- Source/ACE.Server/WorldObjects/Portal.cs
Changes the variables used for Portal level enforcement to those that are set in the database and retrieves and sets their values on Portal creation.
> Enable MinMax Portal level enforcement

- Source/ACE.Entity/Enum/WeenieError.cs
- Source/ACE.Entity/Enum/WeenieErrorWithString.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/Key.cs
The error message enums should be complete and correct now. I also made a few changes to the Door and Key objects to fix sounds and use the correct error messages that were in retail pcaps.
We may want to add more states to doors like motionStateOpening and motionStateClosing. The animation appears to be close to 1.5 seconds long for opening/closing. If we had opening/closing states we could prevent the player from spamming use on the door while it is performing an animation.
> Error message fix ups etc.

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Turning to target, range checking, switched busyCasting state bool to a more generic busyState status, and spell damage for two Life Magic spells
> Magic Level 3

- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
All of the Boost type Life spells and the Transfer spells damage portion implemented using the data from the StatMod World DB entries; applying the Transfer spell's drain amount to caster and vital transfer spells still to be implemented.
> Implemented StatMod World DB usage

- Source/ACE.Server/WorldObjects/Portal.cs
- Use the Player.Teleporting flag to prevent Portal.HandleActionOnCollide() from doing any actions multiple times because of repeated collisions
> Limit Portal Spam from multiple collisions

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- If target is player, check for similar PK status before allowing casting of harmful spells
- Implement target's Magic Defense vs caster's Magic Skill level
> Magic :: Lesson 12 : Check PK status and implement Magic Defense

- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Player.cs
Removed the value property from the corpse before it is added to the landblock. I don't know if this is an issue that most can see, but with loot, it is very noticeable.
> Corpses had no value.

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Target validation : checks for hackery, even if the client disallows certain targets for specific spells
- Workaround for spell projectiles in dungeons
- Remove extra UseDone message in Enchantment code path
> Magic :: Lesson 12.5 : Target validation and a few fixes

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
As caught by Derrick, a null check was missing vs the Attuned property itself.  However, the fist null check should remain, as there is a possibility that GetInventoryItem() might return a null, which would need to be handled in a manner to avoid a null pointer exception.
> Fix IsAttuned method

- Source/ACE.Entity/Enum/MovementParams.cs
- Source/ACE.Entity/LandblockId.cs
- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Network/Motion/UniversalMotion.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Monster.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
Thanks so much to @dgatewood, @Slushnas, and the entire ACE team for all the help with this PR
> Adding monster movement

- Source/ACE.Server/Command/Handlers/SentinelCommands.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventMagicDispelEnchantment.cs
- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Adds the ability for items with spells to cast them on players
- Fixes the player combat with no weapons equipped, which previously had the potential to create a null exception is two locations
- The refresh of spells in the Enchantment registry needs some work, as they currently don't work correctly, until the client is restarted.
> Magic :: Lesson 14 :: Items casting spells

- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Have HandleActionCastTargetedSpell method be more granular is deciding the target type to determine whether player rotation is needed
- Change an two if statements in IsInvalidTarget, so the result is correct to allow casting Item enchants on valid targets
> Fix a null exception and a couple of if statements

- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/Scripts/PhysicsScriptTable.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
Various bits of code have been added to make the existing spells line up with retail data and lay the groundwork for other spells. There is still more research to do but this is a step closer to retail based on the data I have gathered so far.
I am not sure if the code I added to WorldObjectFactory.cs is the best way to get the spell ID into the constructor (seems like one of the CreateWorldObject functions could be removed/integrated).
I had to add some code to be able to override some PhysicsDescription fields. I did a couple of searches through the pcaps and the fields that I set to false by default don't seem to have been used so I don't believe this will cause any problems.
> Bolt, Streak and Arc updates

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Added HandleReceive in WorldObjects
Checking within PlayerInventory if a HandleReceive is true.
Added new cases inside of ExecuteEmote.
Thiss allows all collectors and rng hand-ins, such as GamesMasters, to work.
> EmoteTable Stuff

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Creature.cs
This code works for all collectors and should work for many more things. The only problem is is that there are emote tables missing. Also, with quest NPCs, the first emote for onUse is to update the quest. Once the quest is updated, It will then give dialogue about the quest. We do not have quest tables in to update it, so you will not see any information regarding quests.
> On use emotes

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageDeleteObject.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Tracking.cs
- Source/ACE.Server/WorldObjects/Scroll.cs
- changelog.md
* Renamed GameMessageRemoveObject to GameMessageDeleteObject to avoid confusion with other messages.
* Renamed TryDestroyFromInventoryWithNetworking() to TryRemoveFromInventoryWithNetworking() as that function sends InventoryRemoveObject messages.
* Cleaned up some stack merging code and added support for merging missile ammo to currently equipped ammo.
* Added the ability to set the stacksize of spawned items created with the /ci command.
* Fix for observed players improperly playing last combat mode animation when moving.
* Fixed missile ammo appearing in players hands on login.
* Fixed arrows being fired after switching to peace mode.
* Added ammo usage to player missile attacks.
* Added damageSource parameter to damage functions to better support edge cases.
* Various other minor …
> Various missile combat fixes/additions

- Source/ACE.DatLoader/Entity/Texture.cs
no longer uses the stream length for parsing
more descriptive property name
moved DirectX texture formats enum to ACE.DatLoader.Entity namespace
> fixed bug causing DefaultPaletteId to always be set

- Source/ACE.Server/Network/GameEvent/Events/GameEventDefenderNotification.cs
I noticed this message wasn't parsing correctly. This should fix it.
> Fix Defender notification message length.

- Source/ACE.Server/Network/MessageFragment.cs
- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/PacketFragmentHeader.cs
- Source/ACE.Server/Network/PacketHeader.cs
- Source/ACE.Server/Network/PacketHeaderFlags.cs
- Source/ACE.Server/Network/PacketHeaderOptional.cs
- Source/ACE.Server/Network/Session.cs
WAN sessions are now at least reliable enough to test with
message fragments are now grouped by queue
refactor PacketFragmentHeader.Queue to match aclogview
refactor Packet.Header.Iteration to match aclogview
included some missing header flags from aclogview
include aclogview packet header flag names as comments
refactor typo in packet header flag names
> WAN reliability, message queues, refactoring

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Selected Wielded Objects as well as Inventory Objects. This fixes crash of gioving wielded objects to the town crier.
> Give Request fix

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Unwield and RemoveWithNetworking added/moved to the first thing done.
> Unequip and burden correction

- Source/ACE.Server/Command/Handlers/DebugCommands.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/Physics/Animation/Transition.cs
- Source/ACE.Server/Physics/Common/Position.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/Util/AdjustCell.cs
- Source/ACE.Server/WorldObjects/Creature_BodyPart.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/SkillFormula.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Fixed various bugs with monsters crossing between landblock and cell boundaries.
- Monsters should be able to chase the player through dungeons and indoor areas more consistently
- Added monster movement debug commands
- Fixed the missing portals in Hotel Swank
- Fixed a bug with some dungeons having black screens on portal entry
> Improved monster transitions between landblocks and cell boundaries

- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
-Remove the five unneeded start items from WeeniePropertiesCreateList that get generated for all characters.
> Remove the five unneeded start items

- Source/ACE.Server/Command/Handlers/SentinelCommands.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/Enum/WeaponMask.cs
- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Switch.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Redirect Aura spells cast by items to Player
-Fix Enchantment Registry timers
-Account for gems casting spells requiring a duration
-Initial pass at Enchantment layering
TODO: duplicate and overridden item enchants still show up on AppraisalInfo :: will fix in next PR
> Fix Enchant Registry for duration and layering and Redirect Aura spells

- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- changelog.md
This addresses Issue #779 
To test:
* /ci 8327 (Gold Pea)
* /ci 8283 (Splitting Tool)
* /ci 136 (Pack)
* Place these items in the Pack.
* Use the Splitting Tool on the Gold Pea in Pack.
Gold Pea should be removed and Gold Scarabs placed in main backpack.
> Fix for using recipe items located in Packs

- Source/ACE.Server/Network/Enum/ArmorMask.cs
- Source/ACE.Server/Network/Enum/WeaponMask.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/Network/Structure/ArmorProfile.cs
Rework AppraisalInfo to differentiate between intrinsic spells and applied spells
- "spellbook" data sent in AppraisalInfo packet uses highest bit of uint to indicated whether intrinsic spell of item or applied enchant
- WeenieType.Cothing enchants are applied to the item
- Account for debuffs applied to wielded weapons
- Enchants applied to armor affecting armor stats fixed to display correctly
> Rework AppraisalInfo for Enchants

- Source/ACE.Entity/Enum/AetheriaBitfield.cs
- Source/ACE.Entity/Enum/AttackType.cs
- Source/ACE.Entity/Enum/AttunedStatus.cs
- Source/ACE.Entity/Enum/BondedStatus.cs
- Source/ACE.Entity/Enum/CombatBodyPart.cs
- Source/ACE.Entity/Enum/HookTypeEnum.cs
- Source/ACE.Entity/Enum/HouseType.cs
- Source/ACE.Entity/Enum/ImbuedEffectType.cs
- Source/ACE.Entity/Enum/SubscriptionStatus.cs
- Source/ACE.Entity/Enum/SummoningMastery.cs
- Source/ACE.Entity/Enum/WeaponType.cs
- Source/ACE.Entity/Enum/WieldRequirement.cs
Note that HookType exists in both:
ACE.Entity.Enum
ACE.Server.Physics.Hooks
The one in Physics should probably be renamed to PhysicsHookType so that the more global one in ACE.Entity.Enum can maintain consistant naming with the client.
> More enums added from the client/ACLogView to ACE.Entity.Enum

- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
A 2 second delay was added to the casting of the recall spells in patch Thorns of the Hopeslayer
> Add 2 second delay to Recall spells

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Add checks before Magic Damage is calculated to ensure target isn't already dead
-Change EarnXP on creature kill to sharable
-Rearranged the flow of player spell casting, predominately moving the out-of-mana fizzle to after the spell windup animation and the speaking of the spell words
> Add check for target death before process Magic Damage

- Source/ACE.Entity/Enum/CharacterOption.cs
- Source/ACE.Entity/Enum/CharacterOptions1.cs
- Source/ACE.Entity/Enum/CharacterOptions2.cs
- Source/ACE.Entity/Enum/MaterialType.cs
- Source/ACE.Entity/Enum/MotionCommand.cs
- Source/ACE.Entity/Enum/MovementTypes.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Entity/Enum/SkillStatus.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
MaterialType is what the client uses, and follows the patter we've been using for other enum names as well.
> Enum comments added, Material renamed to MaterialType

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
-Add GameEventPopupString message function to EmoteType.PopUp, when no confirmation is requested, and finish the Confirmation functionality
-Adjust the Welcome message to match retail, with a twist
-Change two more Spell references to SpellBase, in EnchantmentManager.cs
-Add GameEventCommunicationTransientString to Chest.cs, when chests are in the locked condition
> Various tweaks

- Source/ACE.Database/Models/Auth/AuthDbContext.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/Models/World/WorldDbContext.cs
This simply updates the files to the latest formats generated by Pomelo.
This gets format changes out of the way so that future schema changes show only the fields changed, and not additional format changes.
> All 3 databases rescaffolded

- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Move PK checks to after start of spell cast and one spell projectile collision
-Move spell damage messages to be mutually exclusive with the death messages
-Implement SpellType.PortalLink (Primary Portal, Secondary Portal, and LIfestone Tie)
> Move PK checks and spell damage messages and implement SpellType.PortalLink

- Source/ACE.Entity/Enum/PhysicsState.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Physics/Animation/ObjectInfo.cs
- Source/ACE.Server/Physics/Animation/Transition.cs
- Source/ACE.Server/Physics/Common/LandCell.cs
- Source/ACE.Server/Physics/Common/ObjCell.cs
- Source/ACE.Server/Physics/Common/ObjectMaint.cs
- Source/ACE.Server/Physics/PhysicsEngine.cs
- Source/ACE.Server/Physics/PhysicsGlobals.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This patch synchronizes the physics state between WorldObject and PhysicsObj
PhysicsObj.State should be the backing store, with WorldObject having easily accessible bool properties, which also persist to PropertyBool for the appropriate fields
This patch also re-introduces Jyrus' change to move InitPhysicsObj() to LandblockManager.AddWorldObjectInternal(). This still needs additional testing, and it seems like we should be initting the PhysicsObjs before this method is called. It is a very convenient entrypoint at the moment though, as it ensures only PhysicsObjs are created for objects upon entry into the 3D world.
There could still be some possible issues though (multithreading?), for example the bug with players entering portals and re-appearing in their original location.
> physics state sync between WorldObject and PhysicsObj

- Source/ACE.Server/WorldObjects/Player_Magic.cs
-Rearrange spell casting busy state notifications to match PCAPs
-Change ChatMessageType for spell words, allowing VT decal plugin to cast spells without any duplicate casts
> Change spell casting busy and Spell words ChatMessageType

- Source/ACE.Database/DatabaseManager.cs
- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardConfigDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Managers/PropertyManager.cs
Previously, PropertyManager used SerializedShardDatabase to wrap it's database calls.
This didn't make much sense because SerializedShardDatabase was basically just a wrapper that serialized calls to ShardDatabase.
So, instead, we now have a ShardConfigDatabase class as well that is held by DatabaseManager. This holds the property/config specific funcitons for the shard.
In addition, there were a couple bugs fixed in PropertyManager where a function migt have been GetLong() when it should have been GetDouble(), etc...
> PropertyManager Database Cleanup

- Database/Base/ShardBase.sql
- Database/Updates/Shard/2018-08-10.txt
- Database/Updates/Shard/updates.txt
- Source/ACE.Database/Models/Shard/Biota.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
- changelog.md
The base Biota record now holds a flags property that indicates what collections are populated, and thus, what should be queried from the database.
GetPlayerBiotas and it's associated functions GetInventory and GetWieldedItems now use Parallel.ForEach loops which significantly improve performance.
> Major Shard Performance Improvements

- Source/ACE.Server/WorldObjects/Creature.cs
In the world data, some property strings don't have the exact case we have in the enums. Thus, a simple ignoreCase bool is needed.
> Creature GetNewFace fix for enum values

- Database/Base/ShardBase.sql
- changelog.md
I was unable to create a fresh Shard DB after @Mag-nus' previous PR seemingly due to a missing comma in ShardBase.sql. Thought I'd correct it for others.
> Added missing comma in updated ShardBase.sql

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Allow for non-Admin and non-Sentinel players, as the target, to correctly pass through IsInvalidTarget() method for beneficial spell casting
> Fix WorldObject_Magic IsInvalidTarget()

- Source/ACE.Entity/Enum/Properties/PropertyBool.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- changelog.md
Test: @create 28973
Portrait of Asheron Realaidain
Even though the item is a technically creature (Int.ItemType = 16), it should ID as a regular object.
Examine should continue to work for creatures, NPCs, other objects as expected.
> Added NpcLooksLikeObject usage in AppraiseInfo

- Source/ACE.Server/Command/Handlers/AdminShardCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
This is in preparation for some DeveloperDatabaseCommands I plan to add.
The reason for the rename is the command handlers we have are all organized based on AccessLevel. Thus, this just aligns the file/class names to the access level commands it contains.
> Rename CommandHandlers to be more appropriate

- Source/ACE.Server/Network/ConnectionListener.cs
This patch recovers from fatal network errors, such as 'FATAL: Network Socket has thrown: An existing connection was forcibly closed by the remote host' which seems to be thrown often from ThwargLauncher connections
The ConnectionListener.Listen() function starts receiving data from a socket, calling OnDataReceive. At the end of OnDataReceive, the Listen() function is called again to resume listening for the next request
If an exception is thrown in Listen(), the exception handler needs to call Listen() again to recover gracefully and to start listening for the next request.
> Network fatal exception recovery

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperDatabaseCommands.cs
- Source/ACE.Server/Command/Handlers/Processors/DatabasePerfTest.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/EmoteManagerExample.cs
- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureAttribute.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Client.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Database.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This is a major change on how Biotas are added/saved to shard.
The AddBiota function is no more. Now, to add or save a biota, the same function is used, SaveBiota.
SaveBiota will pull (in full) the existing biota (if it exists) from the database. It will do a full diff between the new biota to save and the existing biota. It will copy over any differences, add any new rows, and delete from the database any rows that have been removed.
In addition, a ReadWriterLockSlim is passed to the Save/Remove functions in the database. This is necessary to prevent collection modification from the server while Entity Framework is processing the object.
There are still some bugs I need to fix.
BiotaPropertiesEnchantmentRegistry needs to be accessed through this new model for thread safety.
Character …
> Shard Biota Save & Threading Model Rework

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
SetProperty now has an out bool biotaChanged argument that can help the caller know if an actual change was made.
In addition, setting the objects CreationTimestamp was in the wrong place
> Fix biotas being falsely detected as changed

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/Structure/EnchantmentRegistry.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
- Source/ACE.Server/WorldObjects/WorldObject_Database.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Thread safety added to EnchantmentManager
Thread safety added to EnchantmentRegistry
The locks are required only when we iterate/insert/remove from the collections. EF accesses these collections on a separate thread and they cannot be modified while being iterated over.
Player save removed from EnchantmentManager. Saving a player should be a function of the player, not the enchantment manager. If we want to save a player on death, we can do that from the player.
Some minor cosmetic code improvements here and there.
> EnchantmentRegistry improvements

- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
I believe this to be the proper way to use EF with our application.
If we are able to improve db performance, it will be very marginal past this. This is near a best case scenario, if not already best case.
This utilizes Entity Frameworks tracking abilities for the life of the biota.
This does not suffer from context bloat because a single context only manages a single biota.
This does not suffer from data pollution because ACE does not support manipulating a biota via the database while it is currently used by the server.
When a biota is no longer used by ACE, the ConditionalWeakTable will release the reference to its cached DbContext. The garbage collector will dispose that for us.
If we want to explicitly dispose of the DbContext, we can use the FreeBiotaAndDisposeContext functions. …
> ShardDbContext caching. 1 for every Biota via a ConditionalWeakTable

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
-Implement unsecure ability, ie. without Trade_ protocols, to give items to other players, given the status of their "Let Other Players Give You Items" CharacterOption
-Bug fix by gmriggs in EmoteManager.cs for EmoteType.Turn and EmoteType.TurnToTarget
> Player giving items to other players fix

- Source/ACE.Server/Managers/WorldManager.cs
Very simple functions should not be parallelized. It will actually be slower to do so.
In addition, it's unlikely there will be so many network sessions timed out in a single tick that would even require them to be parallelized.
> Threading improvement for WorldManager

- Source/ACE.Server/Entity/Actions/ActionChain.cs
- Source/ACE.Server/Managers/WorldManager.cs
WorldManager SecondsToTicks wasn't implemented correctly and simply returned the same value.
This was added long time ago. It likely had a purpose that doesn't exist anymore.
> ActionChain AddDelaySeconds cleanup

- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Network/ClientPacket.cs
- Source/ACE.Server/Network/ConnectionListener.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/MessageFragment.cs
- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
- Source/ACE.Server/log4net.config
Using the DEBUG log level was basically useless due to all the packet level spam.
Now, you can keep packets at the log level of INFO and the main log setting at DEBUG. This will allow you to see common debug messages but not the actual packet data.
> Packets log level to separate configurable value via log4net.config file.

- Source/ACE.Entity/Enum/SpellBitfield.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/starterGear.json
This PR includes:
1. Ring spell projectiles should now properly explode at their max range. Thanks to @gmriggs for the code.
2. Changed magic range check calculation to match the client code.
3. Added an unknown spell bitfield flag.
4. Fixed a typo with a Creature Magic starter spell.
5. Changed the out of range message for magic to match the retail message.
> Spell range check update, correct ring spell projectile destruction and a couple of small fixes.

- Source/ACE.Server/WorldObjects/Player.cs
If the Character.CharacterOptions are 0, this will try to pull the options from the Biota, or set them to default values.
This is a patch to fix the PR979 schema change.
> Copy CharacterOptions

- Source/ACE.Server/Network/GameAction/Actions/GameActionSetCharacterOptions.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/WorldObjects/Player_Character.cs
This has two fixes.
1) ACE logoff code runs before the final GameActionSetCharacterOption event from the client. Because of this order of operations, any changed options weren't being saved to the character on logoff.
2) Character was being modified while it was being saved by EF. This caused some change tracking mismatches.
I mentioned before, but there are still a few lingering places that need this type of locking. It's another thing on my todo list.
> Character gameplay_Options fix

- Source/ACE.Server/WorldObjects/AdvocateFane.cs
- Source/ACE.Server/WorldObjects/Book.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Cow.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Game.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Lifestone.cs
- Source/ACE.Server/WorldObjects/PKModifier.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/Scroll.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
This removes the unecessary ActionChains that were wrapping many of the HandleActionGameEvent functions.
ActionChains should only be used to enqueue work with delays, or, explicitly queue work for another WO that absolutely must be run on the landblock thread that owns the WO. (very rare, if any cases?)
We do not need to worry about out of order operations with HandleActionGameEvents. These handlers are enqueued when they are received on the network threads. They are then executed in a single thread in our UpdateWorld loop. This pattern is unlikely to change, and allows us to make the assumption that code executed from any HandleAction function (and not from an action chain) does not need to worry about thread safety, as it is the only thread modifying the world.
Parallelization will be …
> ActionChain Cleanup

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
The purpose of this queue was to make removing items from a landblock thread safe.
The assumption was that a worldObject and the landblock that owns it could be run on two separate threads.
Our initial implentation for multithreaded AC was that any Landblock or WO could be ticking on a completely separate thread.
We've since changed how we plan to multi-thread AC, with the assumption that a WO will be ticked/think on the same thread as it's parent Landblock, and furthermore that any adjacent landblock that has at least 1 player will also tick/think on the same thread.
This makes the design of ACE a lot more simple in the long run, and allows us to remove a lot of instances of excessive thread safety and action chain use.
> LandblockMotionQueue removed

- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
PlayerEnterWorld is a callback from a task created in the SerializedShardDatabase.
This callback can end up modifying the Landblock collections and data.
UpdateWorld also modifies Landblock collections and data.
We add UpdateWorldLandblockLock to make sure only a single thread accesses/modifies these collections.
> Fix Landblock multithreading

- Source/ACE.Server/Network/GameEvent/Events/GameEventAttackerNotification.cs
This fixes the serialization of the AttackerNotification message. Critical hit messages will now be displayed properly in the client.
> Fix serialization of the critical hit field.

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This patch adjusts the attack animation speed for Players and monsters to match the quickness / weapon speed / enchantments for melee weapons
- Fixed a bug with indoor scatter generators not getting the new cell
- Fixed an issue with invisible objects broadcasting to players
>  Adding weapon speed mod

- Source/ACE.Server/Network/GameAction/Actions/GameActionOpenTradeNegotiations.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventDeclineTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventTradeFailure.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Trade.cs
- changelog.md
This is an update to my previous PR where basic secure trade functionality was implemented.
This PR does the following:
- Verifies that trade partner is in range
- Honors ignore all trade requests character option
- Does not initiate when either party is in combat mode
- Adds a few messages based on what I saw in retail PCAPs
- Implemented GameEventDeclineTrade per PCAPs
- Implements turn to when approaching trade partner
Probably a few other minor tweaks. Again, sorry for all of the open and closing PR noise. Git and I are often not friends.
> Revised pass at secure trade

- Source/ACE.DatLoader/BinaryReaderExtensions.cs
- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/WorldObject_Database.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
WorldObject.Positions was misused. The code has been cleaned up so that Position access passes through the Get/Set/Remove functions.
Furthermore, on save, we make sure that the positions in the biota have the latest up to date values from the cache.
We must do this because we don't wrap Positions like we do attributes/skills/vitals.
Also added a very important note regarding use of SetPosition:
/// !!! VERY IMPORTANT NOTE REGARDING SetPosition !!!<para />
/// Position objects are reference types. Lets say you want to create a new object and give it the location of a player,
/// If you do LandscapeItem.SetPosition(PositionType.Location, Player.Location), you've now set the Location position
/// for both the player and the LandscapeItem to the same exact object. Modifying one will affect …
> WorldObject Position Updates

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- changelog.md
This PR should address both concerns raised by @OptimShi as noted in issue #866.
The messages returned when a user attempts to place pack being viewed by another user were what I remembered of retail. I couldn't find anything in PCAPs to support what I remembered. I'm open to suggestions if those messages should be something else. I'd be happy to update with the consensus.
> Fix the picking up of open and in use packs

- Source/ACE.Server/WorldObjects/Player_Trade.cs
Fixed a bug @gmriggs found where where an erroneous WeenieError.TradeCancelled was sent to client when a character entered combat mode, whether or not the character was trading.
> Fixed bug where excess WeenieError.TradeCancelled was sent

- Source/ACE.Server/Command/CommandManager.cs
- Source/ACE.Server/Command/Handlers/AccountCommands.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/AdminShardCommands.cs
- Source/ACE.Server/Command/Handlers/CharacterCommands.cs
- Source/ACE.Server/Command/Handlers/CommandHandlerHelper.cs
- Source/ACE.Server/Command/Handlers/ConsoleCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperDatabaseCommands.cs
- Source/ACE.Server/Command/Handlers/HelpCommands.cs
- Source/ACE.Server/Command/Handlers/Processors/DatabasePerfTest.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
There were a ton of commands that worked both on the console, and from a player session.
These commands had conditions like the following to determine if the output should be sent to the console or to the sesion:
if (session != null)
sendToSession()
else
SendToConsole()
CommandHandlerHelper cleans up this.
In addition, there were places in the code that were doing Console.WriteLine that should have been using the logger instead.
> CommandHandlerHelper (Yum!) Added

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Physics/Animation/MotionTable.cs
- Source/ACE.Server/Physics/Managers/MoveToManager.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Inventory.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Tick.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Tracking.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Tick.cs
- Added direct visibility / line-of-sight test
- Added ExecuteMotion, which plays the animation on both the client and server.
- EmoteManager - EmoteType.Motion now goes through ExecuteMotion, so animations like monsters going to sleep (skeletons/golems) will now be simulated properly on the server. This fixes the bug where monsters would start moving while they were still transitioning from sleep->wakeup
- Added more robust logic for animation timing while switching combat stances, for both players and creatures
- Added randomized stack size variances to mob projectiles, based on WieldedTreasure tables
- Improved timing for all monster animation transitions (combat stance, missile launches, spellcasting)
- Added randomized variance to monster melee attack delay (0.5-2s)
- Fixed a bug …
> Improved monster timing / server animation sync

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Properties are no longer spit out on ident in debug builds.
Now, you can use /propertydump to spit out all the properties of the last item you identified.
> PropertyDump added

- Source/ACE.Server/Entity/SpellProperties.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Change DamageType to DamageType2 for LifeMagic Boost spells
> Fix DamageType for Boost spells

- Source/ACE.Server/Network/GameEvent/Events/GameEventCombatCommenceAttack.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Creature_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- There are a bunch of Bandit weapons that can be used for testing. https://github.com/ACEmulator/ACE-World-16PY/search?q=TripleSlash will show a bunch of multistrike weapons. /ci 12053 for a Bandit Lightning Dagger
- The animation hit frames were synced up reasonably well, but I am still looking for something in the data that can tell us exactly which animation frames to strike on.
- Two-handed weapons are temporarily double-striking, while cleaving is still being added
- Fixed a bug with fist combat mode being broken
- Improved dual wielding combat so that the stats from the offhand weapon are used on the offhand attacks
- Added more comments to Player_Melee
- Fixed a bug where melee combat was not sending the 'AttackDone' network message when 'Auto-repeat' attacks option was disabled, …
> Adding multistrike weapons

- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
- Source/ACE.Server/WorldObjects/Player.cs
Fixes an issue where a new characters will not show as joining an allegiance until a server restart. If the new character is the patron the server will crash, also fixed. During testing of the latest server code found that character creation was broken. Added that fix here by setting up Character.IsPlussed to 'true' in ..ACE\Source\ACE.Server\WorldObjects\Player.cs. I am not sure if it should be 'true' or 'false'.
> Alleg Fixes plus fix for No Default SQL

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageSound.cs
- Source/ACE.Server/WorldObjects/ManaStone.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Added the 'ItemManaDepleted' sound effect
- Added a small delay between 'ItemManaDepleted' sound and 'SpellExpired' messages/sound effects. Not sure if retail just purged the item enchantments invisibly?
- Changed the low mana warning timer from 30s -> 2m
- Added commas to all numbers >= 1,000
- Added /givemana developer function
- Changed the wording of some messages to match retail:
- mana -> Mana for low/depleted messages
- added a missing . to the end of item lists
> Updating the 'item is low on mana / out of mana' system

- Source/ACE.Server/Network/GameMessages/Messages/GameMessagePlayerTeleport.cs
Furthermore, in retail, the sequence sent in GameMessagePlayerTeleport is always the PREVIOUS sequence value, and then the sequence get's incremented AFTER the message is actually secent (and thus, sent in the next UpdatePosition message).
For simplicity, ACE just increments the sequence BEFORE this message is sent. It doesn't seem to affect the client or decal and is cleaner this way.
> GameMessagePlayerTeleport was malformed

- Source/ACE.Server/WorldObjects/Creature_Tick.cs
- Source/ACE.Server/WorldObjects/Creature_Vitals.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
- Source/ACE.Server/WorldObjects/Player_Xp.cs
These changes are the result of profiling.
VitalHeartBeat (formerly VitalTick) had code that iterated over all enchantments several times. This reduces the number of times those collections are iterated over on each heartbeat.
> VitalHeartBeat performance optimizations

- Source/ACE.Server/WorldObjects/Monster_Missile.cs
Should this even be wrapped in an actionchain?
We shouldn't wrap things in action chains now unless we really need to.
> LaunchMissile check for null (fix exception)

- Source/ACE.Common/RateMonitor.cs
- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/Processors/DatabasePerfTest.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
There are 2 major changes in this PR.
1) NetworkSession GameMessageGroup based bundles have been switched from a concurrent dictionary to an array. An array will be many times more performant as there are only 12 elements and they're aligned to a 64bit boundary, thus making get/sets atomic. As such, we can simplify the way we lock access to each element.
2) Landblock ctor async code has been grouped up into a single thread. Furthermore, the database work being performed inside that thread will no longer spawn more threads by using parallel calls. This makes sure that landblock construction an obtaining assets doesn't eat up the applications idle threads from the pool. We want to save those threads for more important work that will help keep UpdateGameWorld running smoothly.
Renamed the …
> More profiling based improvements

- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- changelog.md
> Command verb "list" for developer command /telepoi 

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Physics/Animation/AnimSequenceNode.cs
- Source/ACE.Server/Physics/BSP/BSPNode.cs
- Source/ACE.Server/Physics/Common/CellStruct.cs
- Source/ACE.Server/Physics/Common/DBObj.cs
- Source/ACE.Server/Physics/Common/EnvCell.cs
- Source/ACE.Server/Physics/Common/GfxObj.cs
- Source/ACE.Server/Physics/Common/LScape.cs
- Source/ACE.Server/Physics/Common/Landblock.cs
- Source/ACE.Server/Physics/Common/LandblockStruct.cs
- Source/ACE.Server/Physics/Common/ObjCell.cs
- Source/ACE.Server/Physics/Entity/BSPCache.cs
- Source/ACE.Server/Physics/Entity/GfxObjCache.cs
- Source/ACE.Server/Physics/Entity/PolygonCache.cs
- Source/ACE.Server/Physics/Entity/VertexCache.cs
- Source/ACE.Server/Physics/PhysicsPart.cs
- Source/ACE.Server/Physics/Setup.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
* Vertex/Polygon/BSP cache disabled by default
* GfxObjCache is now thread safe
* DBObj boxing/unboxing improvements
With the above changes, landblock physics loading uses about 30% less CPU.
* Landblock now loads physics assets in the async worker created in the landblock ctor. 
There might still be some bugs from this, will need some testing.
> Landblock async physics loading + some physics profiling improvements *NEEDS TESTING*

- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Decay.cs
Fixed corpses not decaying at Corpse.EmptyDecayTime after they were looted.
Fixed items given to NPC's reappearing back in your inventory. Item.Destroy() was not being called on the object after it was processed. Destroy() will remove the item from the database, thus, breaking the link from the player.
> Give item fix

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/EmoteManagerExample.cs
- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Healer.cs
- Source/ACE.Server/WorldObjects/Lock.cs
- Source/ACE.Server/WorldObjects/ManaStone.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Scroll.cs
- Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
- Source/ACE.Server/WorldObjects/WorldObject_Decay.cs
Retain TimeToRot magic values of 0 and -1. They may have come from the weenie.
Destroy stacks that are consumed.
Destroy consumables when they're consumed.
> More item destruction fixes

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This, again, is a pretty significant change even though it seems very minor.
Previously, any time a biota property was get/set/removed, the action would iterate over the biota property collections to perform the action. As you can imagine, if the property was toward the back of the collection, the overhead was significant.
Now, we cache those records in dictionaries keyed by the property key.
This reduces the CPU needed for the actions by about 80%.
What's the catch?
The catch is that if a developer adds/removes to/from the biota property records directly, the dictionaries will get out of sync and exceptions will most likely be thrown.
This isn't a new requirement though. We already had a requirement that everything had to go through the GetProperty, SetProperty and RemoveProperty …
> Property Dictionaries

- Source/ACE.DatLoader/CellDatDatabase.cs
- Source/ACE.DatLoader/DatDatabase.cs
- Source/ACE.DatLoader/DatManager.cs
- Source/ACE.DatLoader/PortalDatDatabase.cs
- Source/ACE.Server/Program.cs
Default is off, which should act exactly as ACE did before.
The use of this feature is set in Program.cs via the following line:
DatManager.Initialize(ConfigManager.Config.Server.DatFilesDirectory, true);
I did not actually profile this, so, I don't know if reusing the filestream actually makes a difference. This is the reason for the **NEEDS TESTING** tag.
> keepOpen option added to DatDatabase FileStream

- Source/ACE.Server/Network/Sequence/SequenceManager.cs
- Source/ACE.Server/Network/Sequence/SequenceType.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Previously, WorldObject init every sequence.
Now, WorldObject only inits the base and public sequences used by (possibly and/or probably) all world objects.
Player, then further inits the sequences used by players.
This reduces the footprint of non-player WorldObjects, which are the overhwleming majority.
In addition, SequenceManager itself has received some very minor tweaks for efficiency and simplificaiton.
> SequenceManager simplification

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
Get's rid of old code. Removes item from player with networking, and saves item to database once it has been transfered to Vendor.
> Vendors work again, with nearly no change.

- Source/ACE.Database/SQLFormatters/SQLWriter.cs
- Source/ACE.Entity/Enum/Properties/PositionType.cs
- Source/ACE.Entity/Enum/Properties/PropertyDataId.cs
- Source/ACE.Entity/Enum/Properties/PropertyFloat.cs
- Source/ACE.Entity/Enum/Properties/PropertyInstanceId.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Entity/Enum/Properties/PropertyString.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/WorldObjects/Creature_Networking.cs
- changelog.md
* Added some properties so the writers could annotate them for readability
* Updated Creature.CalculateObjDesc to support reading in of PCAP'd ObjDesc data. This bootstraps weenie appearance without the need to divine clothing data (base and objects(palette + shade))
> Changes to support PCAP exported data being used in database

- Source/ACE.DatLoader/Entity/SkillCG.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Factories/PlayerFactory.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Previously, character creation wasn't taking into account skill credit overrides.
For example, every heritage group defines Arcane Lore as being 0 credits to train and 2 to spec, where as the main skill table in the dat defines Arcane Lore as 4 credits to train.
This will correctly take into account heritage group overrides.
WorldObject IsBusy and IsMovingTo have simply been changed to auto properties. IsDestroyed has been removed as it was never used.
> Fix char creation heritage group skill cost overrides

- Source/ACE.Server/Network/ClientPacket.cs
- Source/ACE.Server/Network/ConnectionListener.cs
- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/Packet.cs
- Source/ACE.Server/Network/ServerPacket.cs
Because of this bug, ACE has been sending packets with no size limit. While this works well on a local network, it could have had reliability issues over a WAN.
ServerPacket has a MaxPacketSize of 464. This stems from the original days of ACE.
I suspect this is the maximum size of AC related data we can stuff into a UDP packet (before overhead is added) to keep the UDP packet sent over the WAN in a single fragment.
If we increase this value, it could reduce some server load and byte overhead, but, if a single fragment of the UDP is lost, all fragments will be lost and have to be resent.
> This fixes ServerPackets that were built with too many fragments, and thus too large

- Source/ACE.Server/Entity/PositionExtensions.cs
Generators are using this function, and, occassionaly throw exceptions as a result of landcell being null.
> Handle null result from LScape.get_landcell() in GetCell()

- Source/ACE.Server/WorldObjects/Vendor.cs
Fixes issue where vendors gave you X times the value for an amount of items in a stack that you were selling.
> Update Vendor.cs, Resolves #1126 and Resolves #811

- Source/ACE.Server/Physics/Common/EnvCell.cs
This resolves the issue with Gan-Zo's Golden Chest not spawning in the Shoushi Casino, as well as other possible spawn issues
> Fixing object spawning in visible child cell

- Database/Updates/Shard/HousePermission.sql
- Source/ACE.Database/Models/Shard/Biota.cs
- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Database/Models/Shard/HousePermission.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Entity/PositionExtensions.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseAddAllStoragePermission.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseAddPermanentGuest.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseBootEveryone.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseBootSpecificGuest.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseChangeStoragePermission.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseListAvailable.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseRemoveAllPermanentGuests.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseRemoveAllStoragePermission.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseRemovePermanentGuest.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseRequestFullGuestList.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseSetHooksVisibility.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionHouseSetOpenStatus.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventHouseUpdateRestrictions.cs
- Source/ACE.Server/Network/Structure/RestrictionDB.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Hook.cs
- Source/ACE.Server/WorldObjects/House.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Storage.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
The following commands have been added for housing:
@house boot <name> - Removes a player from your house.
@house boot -all - Removes everyone from your house.
@house guest add <name> - Adds players to your house guest list.
@house guest remove <name> - Removes players from your house guest list.
@house guest remove_all - Removes all guests from your house guest list.
@house guest list - Shows the current guest list.
@house storage add <name> - Gives a player permission to use your house storage.
@house storage remove <name> - Removes permission to use your house storage from a player.
@house storage remove_all - Removes all storage permissions from guests.
@house open - Creates an open house.
@house close - Closes your house.
@house hooks on|off - Makes the hooks in your house visible or …
> Adding house guest and storage permissions, open/closed, hook visibility, and boot system

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player.cs
This resolves https://github.com/ACEmulator/ACE/issues/1189
> Updating consumables

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
This fixes a bug where vendor buy/sell prices for trade notes weren't matched up on the server
This resulted in the player thinking they were buying a trade node for a certain price, and then being charged a lot more for it
It also resulted in a player selling a trade note to a vendor, and receiving less than the actual trade note value
This also adds various small vendor details, such as the Buy/Sell emotes, and PickupEvent sound effects when a transaction has been made
> Fixing vendor trade notes

- Database/Updates/Shard/2018-12-31-00-Enchantment-Index.sql
- Source/ACE.Server/Entity/AddEnchantmentResult.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes some differences between the way ACE was handling Enchantment layers that differed from retail
Previously, for the 'surpassed' and 'surpassing' cases, ACE would not write enchantments if they were surpassed by an existing enchantment, or in the 'surpassing' case, it would modify the old enchantment, instead of adding a new layer.
The proper functionality here is to write the new enchantments in both cases, always increasing the layer id.
Also previously, ACE was sort of implicitly managing the most powerful enchantment as always being the top layer enchantment for that category (in GetEnchantments_TopLayer). Since it can no longer be assumed that the top layer id for category is the most powerful enchantment, this function has been modified so that it sorts by descending …
> Improved enchantment layering

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
We have to add certain "hacks" to the code because Player_Tracking->RemoveTrackedEquippedObject() is doing GameMessageDeleteObject, not GameMessagePickupEvent
> Fix giving items back and forth

- Source/ACE.Server/WorldObjects/Creature_Missile.cs
For players, we TryDequipObjectWithNetworking with ConsumeItem and that will also call the Destroy for us.
Monsters, we TryDequipObjectWithBroadcasting.
Players and Monsters treat this a little differently.
Key being that players use WithNetworking (since they have sessions and require more info), and creatures use WithBroadcasting (since they don't have sessions and don't have clients that need updates)
> Players need to DequipWithNetworking on final missile launch

- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
This fixes the elusive bug when killing some monsters, where the 'alive' version would appear again, as a frozen/duplicate copy
Thanks to everyone who helped track this one down (Keith, Jyrus)
> Fixing monster corpse spawn bug

- Source/ACE.Server/Network/GameAction/Actions/GameActionChangeCombatMode.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Issues that still exist:
Player_Inventory.HandleActionGetAndWieldItem() needs a way to prevent further actions when the player is currently in a busy state (animating from a previous action)
If you are in combat mode, with your arrow visible, and someone logs in next to you, they will not see your arrow. *FIXED*
> Missiles aren't childeren. Return to peace when dequipping ammo

- Source/ACE.Server/Program.cs
This will (should) catch any unhandled exception from any thread.
It will log it as an error, and the application will exit (unsafely).
The user will see the same exception twice on their console, but only one will be logged to the logger. This is expected behavior.
This was tested with the gem exception and works.
If you're wondering, there is no safe way to handle exceptions from UpdateWorld and keep going, nor is there any safe thing we can do if we're in that state to save players. We have no idea what state a player might be in when this is thrown. The could be between two very critical modifications. Furthermore, if we did try to save all players on exceptions, it could be used as an exploit to try to save players/items in a "bugged" state.
The safest thing to do is quit and trust …
> use AppDomain.CurrentDomain.UnhandledException

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Monster.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
Notes during playthrough:
http://asheron.wikia.com/wiki/Oswald%27s_Dirk_Quest
- On the very first step of the quest, when picking up the Empty Mug from the table, I noticed that I had to jump up onto the table to actually get within pickup range. I updated the Player_Use distance check function to use the same cylinder distance check from physics, but even this seemed to produce the exact same result.
- In the 2nd trial with the Rolling Balls of Death, the balls weren't spawning, and I checked Gaerlan's Citadel - they were also broken again there too. They were broken from the recent change to EmoteType.CastSpellInstant to call WorldObject_Magic.TryCastSpell, which was only handling targetted spells. Updated these code paths to also handle untargeted spells.
Note, when comparing to retail …
> Fixing Oswald's Dirk Quest

- Source/ACE.Entity/Enum/Properties/PropertyInt64.cs
- Source/ACE.Server/Entity/IPlayer.cs
- Source/ACE.Server/Entity/OfflinePlayer.cs
- Source/ACE.Server/Managers/AllegianceManager.cs
- Source/ACE.Server/Network/Structure/AllegianceData.cs
- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
Managing the conversions between int -> long for allegiance passup XP can be error-prone, so this patch adds Int64 properties for these values
Generated and received XP from the allegiance is now tracked, and these fields are also stored as Int64 (although the network protocol sends the 'cpTithed / generated' as uint, so the display for these will cap out at ~4 billion still...
> Improving allegiance XP passup

- Database/Updates/Shard/2019-01-17-00-Spellbook_Filters.sql
- Source/ACE.Database/Models/Shard/Character.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Entity/Enum/SpellBookFilterOptions.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionSpellbookFilter.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPlayerDescription.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
This fixes https://github.com/ACEmulator/ACE/issues/1283 for the unhandled GameAction message
This PR has a shard update SQL script to install:
Database/Updates/Shard/2019-01-17-00-Spellbook_Filters.sql
> Adding server persistence for spellbook filters

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/WorldObject_Tick.cs
This patch adds physics simulation during the death animations for corpses, which fixes issues such as corpses getting stuck in walls and unreachable places, and not spawning corpses
This resolves https://github.com/ACEmulator/ACE/issues/1305 and https://github.com/ACEmulator/ACE/issues/1309
> Adding physics simulation for corpses

- Source/ACE.Server/WorldObjects/Hook.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
This fixes https://github.com/ACEmulator/ACE/issues/1293 and https://github.com/ACEmulator/ACE/issues/1304
> Returning ObjDesc for items on housing hooks

- Source/ACE.Entity/Enum/Properties/PropertyInstanceId.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/Lock.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
When a chest is unlocked, LastUnlocker is set.
When a chest is opened, if this property has a value, the only the player that unlocked it can open it.
todo: When a container is reset/regen, LastUnlocker should be set to null.
> Use LastUnlocker for chests + Make sure player looting is player that has chest open.

- Source/ACE.Server/Entity/SpellFormula.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
This resolves https://github.com/ACEmulator/ACE/issues/1325
- Casting built-in spells no longer has a chance to fizzle
- The windup animation has been removed, only the cast motion is performed
- The player doesn't shout the spell words
> Improved caster built-in spells

- Source/ACE.Server/Managers/EmoteManager.cs
Fix for emote.stat being null, which is functionally equivalent as having a zero, from the TOD Lifestoned data conversion.  Weenies 13239 through 13241, the academy leather pieces, have been updated to post a pop-up on pickup; however, the conversion process didn't output a 0 for the stat field but a null.  This fix causes a null to default to zero, which is a plain popup with no confirmation feedback needed.
> Emote Manager Null Fix

- Source/ACE.Server/WorldObjects/Cow.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
- Completed moving UseTimestamp and ResetTimestamp to common locations, as they are used by multiple objects/Fixes new/hidden compiler warning
- Fixed null spell._spellBase issue of sending extra UseDone message and change this check to use another, less game intrusive message for notification of bad spellId being sent to the server
> Fix Null Spell Msg and Compiler Warnings

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/WorldObjects/Container_Tick.cs
- Source/ACE.Server/WorldObjects/Creature_Tick.cs
- Source/ACE.Server/WorldObjects/Player_Tick.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- Source/ACE.Server/WorldObjects/WorldObject_Tick.cs
There is no longer a DefaultHeartbeatInterval.
Heartbeats only happen if a HeartbeatInterval exists and is greater than 0.
Heartbeats are still staggered over heartbeatSpreadInterval (5s).
Generators will GeneratorHeartBeat() on the next tick after object construction.
However, if RegenerationInterval is 0, they will not beat again.
> GeneratorHeartbeat() is now ticked independantly from Heartbeat()

- Source/ACE.Server/Managers/LandblockManager.cs
This fixes some bugs with objects appearing invisible when first loading into some landblocks
> Adding synchronized ServerObject loading for non-adjacents

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- changelog.md
- Update LootGenerationFactory to support the updated TOD weapon weenies
> Change LootGenerationFactory to support TOD

- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Hook.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Hook are saved when an item is added to it. This is to prevent the possibilty of an item being lost in the event an item is added and the server crashes immediately after.
In addition, the OnAddItem and OnRemoveItem code has been cleaned up as well.
> Cleanup hook related code

- Source/ACE.Server/WorldObjects/Container.cs
GetFreeInventorySlots is something I need for the vendor pack space check that i'm still working on.....
MergeAllStackables is used for the slumlord as requested by gmriggs. note that i did not actually test this code. It looks good though.
> GetFreeInventorySlots() and MergeAllStackables()

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Physics/Common/Landblock.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/WorldObject_Links.cs
We must wait for Landblock.CreateWorldObjects() to complete before we can teleport in. For that we have a new bool CreateWorldObjectsCompleted
Players now check this bool in OnTeleportComplete() and delay materliazation until the landblock resources have finished loading. This will keep players in a pink bubble state until it's safe to spawn in.
> Load Landblock resources async again

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/GamePiece.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Create now sets TimeToRot to Double.MaxValue if whatever you're creating doesn't start with a default. This will leave the created object in the world forever, or until it's picked up and placed down again, or it's destroyed (possibly by killing it)
Monster deaths now call the Destroy() command
Few other places cleaned up that should have been calling Destroy()
Note added to Destroy() where the GUID recycling will be injected.
> Fix Create and Monster Death Destroy()

- Source/ACE.Server/WorldObjects/ManaStone.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
If ItemCurMana.Value < itemsNeedingMana.Count, an infinite loop would result.
Also, the code has been rewritten so that every WorldObject doesn't require a ManaGiven variable.
We also don't need to check Player.EquippedObjectsLoaded. Players are constructed with all of their inventory, and even if that changes, there should never be a case where a player can exist in the world and be interacted with but not yet have their inventory loaded.
> Fix inifinite loop when using mana stone

- Source/ACE.Server/WorldObjects/Coin.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
CoinValue should not be virtual.
Coin.cs no longer overrides CoinValue. Coins don't us CoinValue, only Players do.
This also fixes a bug where the players CoinValue wasn't set on initial login (likely the result of the previous reshuffling for the EncumbranceVal/Value PR)
> Fix CoinValue

- Source/ACE.Server/Managers/EmoteManager.cs
- changelog.md
- Update EmoteType.DirectBroadcast to support "&lt;questname&gt;@You must wait %CDtime to collect the &lt;quest item&gt; again."
> DirectBroadcast Update

- Source/ACE.Server/Entity/Generator.cs
This fixes a bug with picking up items spawned by scatter generators, and then later dropping them
> cleaning up scatter position after initial spawn

- Source/ACE.Server/WorldObjects/ManaStone.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Rework and simplify slightly Player.HandleActionUseWithTarget to allow healing to work, again, and add an allowed target check into ManaStone.HandleActionUseOnTarget()
> Fix healing

- Source/ACE.Server/Network/GameAction/Actions/GameActionNoLongerViewingContents.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
I noticed that in some cases, under load, corpses were remaining on the landblock (not decaying), because the IsOpen flag remained true. This was because either the closing ActOnUse message was being lost, or, VTank was not sending these when extra server load was present.
Now, when we ActOnUse on a new container, and our previous container is still IsOpen by us, we close it.
Also, LastUsedContainer has been changed to LastOpenedContainer which is more descriptive of its actual function.
> Make sure prior container is closed when using a new one

- Source/ACE.Server/Physics/PhysicsObj.cs
This bug occurs when players re-enter visibility to an unmoving player
> Fixing invisible player bug

- Source/ACE.Server/WorldObjects/Vendor.cs
- changelog.md
Items sold or bought by vendors that report Value of 0 are treated as if they were Value of 1.
This is seen with the vendor in training academy, Oil of Rendering is meant to cost 1p, while its value is 0.
In practice this is rare, and client tends to not allow player to sale to vendors items of 0 value items
Co-Authored-By: gmriggs <gmriggs@gmail.com>
> Fix for vendors selling and/or buying items with Value of 0

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
I don't understand the emote system, but it seems odd to me that
CloseMe does **targetObject**.Close()
and
OpenMe does **WorldObject**.Open()
Shouldn't they be performing the action on the same object?
> Fix the legacy Open/Close virtual functions in WorldObject base

- Source/ACE.Server/Managers/LandblockManager.cs
- changelog.md
If landblock is set to permaload and it also set to load its adajcents, those landblocks should also be marked as permaload
> Allow passthrough of permaload flag to landblocks loaded by adjacent load

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
This resolves https://github.com/ACEmulator/ACE/issues/1535
Some notes:
- The max size for a pyreal stack is 25k, so tested with 3x stacks of 10k pyreals each, instead of the 100k pyreal stacks in the original issue
- The exact message printed by this scenario was: You've lost 10,000 Pyreals, 5,000 Pyreals, your Leather Boots, your Pants, and your Jerkin!
So not exactly splitting each of the 3x 10k stacks in half, but this is the way the SpendCurrency() function works... it sorts all of the Pyreal stacks in order from smallest to largest, and then starts consuming the amount of coins
The death message has been consolidated, so the total amount of pyreals dropped is listed, instead of each of the individual stacks that were consumed from.
After much discussion about whether or not pyreals …
> consolidating pyreals in death message, adding corpse_destroy_pyreals option

- Source/ACE.Server/Entity/Landblock.cs
Check to see if AddPhysicsObj failed first, before we actually add the object to the landblock.
I did not actually play test this...
Edit: Play tested it. Seems normal to me.
> AddWorldObjectInternal Fix

- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/AdvocateItem.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
- Source/ACE.Server/WorldObjects/WorldObject_Tick.cs
- changelog.md
When Advocates equipped their Aegis (AdvocateItem) RadarBlipColor changed from White (Default) to Pink (Advocate) and the reverse occurred on unequip.
> Support AdvocateItem RadarBlipColor changes

- Source/ACE.DatLoader/Entity/SexCG.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Server/Factories/PlayerFactory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- changelog.md
This corrects the appearance of Gear Knights. (And should also apply to Olthoi characters, once enabled).
There is a work around for older Gear Knight players, as well, so they should look normal (but may not have accurate colors as chosen by player, and they never will due to missing data)
This addresses issue #1294
> Gear Knight display fixes

- Source/ACE.Server/Entity/Spell.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This adds support for vital multiplier enchantments, such as Asheron's Benediction
For adding and removing enchantments which affect MaxVitals, an UpdateVital packet is also now sent much quicker, instead of on the next VitalTick update
This resolves https://github.com/ACEmulator/ACE/issues/1607
> Adding support for Asheron's Benediction

- Source/ACE.Server/ACE.Server.csproj
This prevents all threads from being blocked while GC runs (Workstation mode).
Server allows the game threads to continue to operate while GC performs. This is also what is done in web applications and other server based applications.
> Use ServerGarbageCollection instead of Workstation GC

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Fix the merge exploit.
Remove some broadcast messages on errors that weren't needed
Fixed an issue when picking up and merging a partial stack using the R key.
> Inventory Fixes

- Source/ACE.Server/Network/GameAction/Actions/GameActionTalkDirect.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionTell.cs
- changelog.md
This resolves the missing tells issue players are seeing. Some were using the `@tell player, message` form which worked, some were using TalkDirect form that comes from client GUI, which did not work.
> Fix tells via client gui (TalkDirect) to players.

- Source/ACE.Common/Extensions/ExceptionExtensions.cs
- Source/ACE.Database/ShardDatabase.cs
On my load test server, occasionally I would see SaveBiota SSL exceptions. With this PR, it passes on the second attempt.
This may also work for many other db related exceptions.
> Retry failed shard db queries

- Source/ACE.Server/Managers/ServerPerformanceMonitor.cs
- Source/ACE.Server/Managers/WorldManager.cs
In addition, a Total Seconds (Tot) column has been added to /serverperformance.
This new column is a much easier way to see how much resources a particular system is consuming.
> ProcessPacket performance added to /serverperformance

- Source/ACE.Server/Network/Motion/MovementData.cs
- Source/ACE.Server/Network/PacketHeaderOptional.cs
- Source/ACE.Server/Network/ServerPacket.cs
ToArray does a copy where GetBuffer gets the underlying backing array.
Thanks Paradox for the tip.
> MemoryStream ToArray() -> GetBuffer()

- Source/ACE.Server/Factories/LootGenerationFactory.cs
The way these if statements were written, only two variances were actually being used for a given weapon type. The final if/else for each block.
> GetVariance fix maybe?

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Source/ACE.Server/Factories/LootTables.cs
Updated loot values to use material types and gem types when determining the value. This is getting closer to what it should, but it isn't perfect.
> Loot value updates

- Source/ACE.Server/Network/NetworkSession.cs
It was possible for packetQueue to get corrupt when clients request packet retransmits. At that point, multiple threads could be enqueing work.
This adds slight overhead by converting it to a ConcurrentQueue, but, should also (hopefully) fix the "corrupt sessions" issue people were seeing.
This should also fix the exception that was reported in NetowrkSession.FlushPackets()
> Network Stability Improvements

- Source/ACE.Database/ShardDatabase.cs
This is just a partial fix for dispoing contexts properly.
The contexts that are released from BiotaContexts as biotas go out of scope are never disposed. They are only finalized when the GC collects them. I plan to come up with a solution for that as well.
> Dispose ShardContext on RemoveBiota

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Entity/PositionExtensions.cs
- Source/ACE.Server/Physics/Common/LScape.cs
On my test of 1000 landblocks, x: 0x20-0x40, y: 0x20-0x40,
After all landblocks load usign "loadalllandblocks" and unload, there were still ~36 physics landblocks remaining.
This reduces it to ~15.
I've also commented out the landblock unload debug message.
> Reduce rogue physics landblocks loaded by portal desitnation parsing

- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Remove other Magic skill types from elemental casters; only Void and War Magic skill used for wield requirements
- Allow for non-elemental casters to have wield requirements
- Add wieldSkillType to loot melee weapons
- Add Level wield requirement for tier 7 & 8 jewelry
- Correctly apply the Level wield requirement for tier 7 & 8 on armor/clothing
> Add missing WieldSkillType to loot melee weapons

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootTables.cs
- Add shirts and pants to loot drop
- Change weapon damage to be based upon wield difficulty, instead of tier number
- Lower Essence drop rate to ~17%
- Convert a number of magic numbers to descriptive, enum based values
> LootGen Changes/fixes

- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Correct switch statement in Loot gen code, as Light daggers currently in ACE are multi-strike
> Change switch statement, as light daggers are multistrike

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Adjust wield requirement RNG roll from 0, 100 to 1, 100
- Remove extra, unneeded ThreadSafeRandom.Next(), as it only gets called once per run of GetWield()
- Tweak magic caster requirement chances per tier, especially to remove lesser wield requirement values from higher tier loot
> Adjust wield requirements and method used

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Factories/PlayerFactory.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Book.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/House.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
* `iou_trades` property must be enabled (true)
* Hand any IOU to a Town Crier and it will turn it into real item if that item is now in DB
* also fix corpse decay for empty corpses
> Add IOU trade in support

- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
* Changed loot to drop to ground if NoCorpse is true for creatures
* Broadcast CasterEffect if spell has one for all to see (if creature is visible)
* Change Generators enable/disable to staged: change occurs on 2nd heartbeat, 1st detects the change and arms.
> Changes related to Event Generators

- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This adds some protection against some extreme transition scenarios / feeding bad transitions to the physics engine
This can prevent some CPU lockups for ranged monsters taking aim at the player, and then the player portals away
> adding GetBlockDist

- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Source/ACE.Server/Factories/LootTables.cs
- Remove throwing spikes, daggers, axes, etc, that are stackable items from loot generator, as they were only obtainable by crafting, store bought, or as trophy drops
> Remove incorrectly added thrown weapons from loot gen

- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/Session.cs
This is a simple patch to help CE mem usage. The proper fix is to funnel NetworkSession work through Session, so that Session can manage it's state directly.
What is happening now, and can/will happen in the future, is that Player references are being held, and thus, their Session and NetworkSession objects aren't being released.
Even after a Session drops, work can still be enqueued onto NetworkSession through ActionChains and other means. This PR will now ignore that work. Currently, in master, that work is received and held indefinitely (until Player/Session are released)
This also fixes the case where NetworkSession work was being enqueued after a session dropped, but before the Player was fully logged out of the world. Now, that work will be ignored.
> Release NetworkSession resources when a session drops

- Source/ACE.Server/Entity/DamageEvent.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
This looks like it might fix the bug where some players were occasionally getting hit in rare instances for 400+ by Olthoi Rippers and Biakas
GetArmorLayers() is a very old function, and was originally written to use the current AttackTarget of the monster. I left a comment in DamageEvent when I realized this might be unsafe, but now we might see some possible ramifications of this
When the monster AI was updated much later for switching targets in functions like FindNextTarget(), the current execution of this target switching might need to be more tightly clamped to certain states. What I think is happening is, monsters are switching targets in the middle of an attack (ie. maybe they start swinging at a player, and then maybe they re-target a nearby summoned mob before their attack hits …
> possible fix for rare damage spikes

- Database/Updates/Shard/2019-05-03-00-Fix_Biota_Jewelry_WeenieType.sql
- changelog.md
* Add fix up SQL script (2019-05-03-00-Fix_Biota_Jewelry_WeenieType.sql) for existing servers to run to correct jewelry WeenieType on existing items.
- This script will only need to be run once and only fixes incorrect objects.
> Fix Existing Jewelry objects in Shard DB

- Source/ACE.Server/Factories/LootTables.cs
- Add missing new skill spells and cantrips to appropriate spell tables for armor item loot drops
> Add missing new skill spells and cantrips for loot drops

- Source/ACE.Server/Entity/Generator.cs
This is the second part of the Generator fix which allows Generators to be garbage collected as soon as the landblock unloads.
When a Generator receives a NotifyGenerator event, it waits "Delay" before that spawn is actually released.
Currently, that work is enqueued using DelayManager.
In this PR, that work is enqueued in a local Queue that is checked every ~5s HeartBeat.
- Without this fix, generators must wait until their delayed actions are run via DelayManager, and then can be collected.
- With this fix, generators can now be garbage collected as soon as the landblock is unloaded.
This also merges the Delay calculation code into a single property.
> Switch Generators from DelayManager to local queue using the existing 5s HeartBeat

- Source/ACE.Server/Entity/Tailoring.cs
This adds support for the Armor Lower Reduction Kit to reduce leggings to lower legs (greaves) only. It currently only works for Arms -> Lower Arms (bracers).
> Add support for lower armor reduction kit applied to leggings

- Source/ACE.Server/Factories/LootGenerationFactory.cs
If my math is correct and the code is doing what I expect it should be doing with the comparisons, this PR should match Epic drop rates to the rough estimates provided by Mag-nus in dev.  I somewhat matched the rarity of multi-majors to be similar to Epics. If further adjustments or refinements are needed, they can be performed in SpellDistribution(), GetNumMajorCantrips(), GetNumEpicCantrips, and GetNumLegendayCantrips().
Currently, there isn't any other kind of ordering for cantrip spell additions than minor, major, epic, and lastly legendary, nor is there any coding to preclude lesser or greater cantrip or adjusting their percentages based upon what was rolled beforehand, if that type of process was performed.
> Adjustment to loot percentages

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Add option for re-enabling the former skill formula for Assess Creature skill, when skill is untrained
> Optional assess creature mod

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
As requested in #1887, adds optional parameter to /listplayers, supporting either the name or value from `AccessLevel` 
i.e.
```
/listplayers
/listplayers 5
/listplayers admin
```
Attaching a screenshot with the tests I ran locally:
> Add optional AccessLevel parameter to /listplayers

- Source/ACE.Server/Entity/Generator.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
This fixes the issue were chests weren't calling their profiles generator.HeartBeat() because chest.ResetGenerator was false.
The fix is to process maintenance for generator profiles always, but only the spawn heartbeats conditionally.
This was tested using /crack and the pathwarden chest.
> Fix RegenOnClose

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Player.cs
moving the player.IsBusy check to the ActOnUse function prevents multiple food items in a stack from being used while the player is in a busy state
> move IsBusy check to action, not consume

- Source/ACE.Server/Network/GameAction/Actions/GameActionStackableMerge.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionStackableSplitTo3D.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionStackableSplitToContainer.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Switch back to int to avoid the type casting.
We now check to see if amount is <= 0 instead of just == 0 to avoid packet crafting exploits.
The additional messages remain.
A new logging message has been added for <= 0 events detected.
> Partial #1902 Revert

- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootTables.cs
adds percentage chance for jewelry drops based on slot, not type of jewelry
as of right now i set 35% rings, 35% bracelets, 30% necklaces.... this can easily be adjusted by altering the percentage variables
there are more types of necklaces and they were dropping at a higher percentage
also adds gorgets and the second type of ring to loot
> add percentages for jewelry slot drops, move jewelry items to LootTables.cs

- Source/ACE.DatLoader/FileTypes/PaletteSet.cs
- changelog.md
Made a small adjustment to the GetPaletteID function that was, in certain circumstances, returning the wrong palette.
> Fix GetPaletteID function

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Network/Motion/InterpretedMotionState.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
In the previous version, ThreadSafeRandom.Next was being called for each entry in the emoteSet list, increasing the chances of some of the rarer events from occurring
> fixing emote table rng

- Source/ACE.Server/Managers/RecipeManager.cs
This fixes bugs from leather/ivory salvage:
- If a player tried to apply leather/ivory salvage to an item that has already been tinkered 10 times, the server would crash when trying to index into TinkeringDifficulty
- The server would also crash with a null recipe exception after the item has been modified. It appears after the item has been modified, re-getting the recipe returns null, so the original recipe is passed in instead.
> Fixing leather salvage

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- changelog.md
* Add `requirecomps` command.
* Add SpellComponentsRequired property.
* Add HasComponentsForSpell.
* Add HasComponentsForSpell checks to Player.CreatePlayerSpell for targeted and untargeted spells.
> Add ComponentCheck to player spell casting

- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/Managers/NetworkManager.cs
- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/SessionConnectionData.cs
This should fix cachedPacket retention from clients with poor connections. Packet retention is now capped at 60s.
This also removes the SessionConnectionData wrapper:
public double ServerTime => Timers.PortalYearTicks;
> NetworkSession.cachedPackets pruning

- Source/ACE.Server/WorldObjects/WorldObject.cs
Fixes crashes, errors on Switches, Levers, random things with motion that aren't creatures
> Add CMS setting if MotionTableId is present

- Source/ACE.Server/WorldObjects/Creature_Networking.cs
- changelog.md
Added code to use the Setup of a piece of clothing to visually equip it if no ClothingBase exists. This specifically applies to Ursuin Guise, WCID 32155, but may apply to others items in the future.
> Added handler if no ClothingBase exists for an equipped item

- Source/ACE.Server/WorldObjects/House.cs
this fixes something that was working originally, but then was broken again when OnProperty and DungeonLandblockID were updated
this updates those properties so everything works as expected with shallow references to outdoor houses on unloaded landblocks
> updating outdoor house references for unloaded landblocks

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Healer.cs
- Source/ACE.Server/WorldObjects/Player_Vitals.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- removed duplicate BoostEnum/BoosterEnum properties in Food/Healer, moved to WorldObject_Properties using original name
- refactored Food."BoostEnum - 1" and Healer.GetVitalsByKitType() into common GetCreatureVital(PropertyAttribute2nd)
- left a note for Structure/MaxStructure ushort/int inconsistency for future refactoring
- Added TransientMessages for '&lt;target&gt; is already at full &lt;vital&gt;!' for stamina/mana (doesn't appear to be werrors for those)
- Added logic for UnlimitedUse kits
- Updated remainingMsg to match retail: removed double space, '1 use', 'Your &lt;kitName&gt; is used up.' also sent on failure, omitting message for UnlimitedUse
- Fixed a bug where Healer.DoSkillCheck() was using target.MissingHealth instead of target.MissingVital
- Ensure UnlimitedUse kits are …
> additional healing kit refactoring

- Source/ACE.Server/Factories/LootTables.cs
never should have changed the spell ID for the drop, 1949 was working... just rare
> fix nullify item scroll drop

- Source/ACE.Server/WorldObjects/CombatPet.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/PetDevice.cs
- changelog.md
* Fix issue of weenie cache corruption, setting the weenie's type instead of biota's weenietype
* Ensure subbed combatpets are always melee by depriving them of inventory
> Fix some issues with CombatPets

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/GeneratorProfile.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- changelog.md
* Generator system tweaks
- Carry over Delay from profile template correctly.
- Update RemoveQueue info in GeneratorDump.
- Adjust CurrentCreate to be calculated to prevent out-of-sync issues.
- Added GeneratedTreasureItem to GeneratorProfile to track when TreasureGenerator is used (random, mutated lootgen)
> Generator system tweaks

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
this pr resolves https://github.com/ACEmulator/ACE/issues/1922
the code in this pr got a little hairy, in particular the 'bool equipping' that EnchantmentManager seems to require, and the way it needs to be passed through many of the magic functions
i think that maybe these -1 duration spells from equipping items could all be the SpellType.Enchantment, but with the way spells are first passed to Creature/Item/Life Magic, and each one handling SpellType.Enchantment and further passing to CreateEnchantment, required passing this 'equip' bool through many of these functions unfortunately.
the logic in EnchantmentManager that determines if a duration should be -1 used to be a sticking point in the past, but it really seems to boil down to something simple: if i am equipping an item that casts …
> fixing item proc sources and messages

- Source/ACE.Server/Network/ConnectionListener.cs
- Source/ACE.Server/Network/Managers/NetworkManager.cs
- Source/ACE.Server/Network/Managers/SocketManager.cs
- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/Session.cs
This allows you to bind ACE to multiple interfaces via the Config.js.
For most configurations, on a single-homed machine, your Config.js would have:
"Host": "0.0.0.0",
However, in the event you have a server with multiple NIC's, or, a software based VPN, you may want to expose your server to the internet via both of those ip addresses, using the VPN for your public clients and your actual address for your personal clients.
You can now do something like this:
"Host": "10.1.2.3,192.1.2.3",
The PR seems like it's a lot of changes, but it's mainly just a few renamed. The difference now is we pass the ConnectionListener to the NetworkSession and use the ConnectionListener that was initially used to connect to transmit our return packets.
> Add multi-homed internet support

- Source/ACE.Server/Command/CommandManager.cs
Fixes for things like
/command "Param1" "Param 2"
> Fix CommandParser for Multiple Encapsulated Arguments

- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
This code takes a different route from the base, so our normal packet handlers don't catch these exceptions.
> Exception Catch

- Source/ACE.Server/Network/ConnectionListener.cs
- Source/ACE.Server/Network/Enum/SessionTerminationReason.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/Managers/NetworkManager.cs
Fix exceptions from account names that exceed the database column limit.
Fix another exception caused by fragments that are too large
> MoreNetworkFixes

- Source/ACE.Server/WorldObjects/Player_Move.cs
This fixes a bug that only appears while looting containers in magic combat mode:
- Start in magic combat mode
- Double click a landblock container (chest, corpse) while you are just outside the max looting range, so that your player walks (not runs) to the container
- Attempt to loot an item from the container
Expected:
Item is successfully looted, and container inventory window stays up
Actual:
Item is looted, although with some odd client errors such as 'can only move 1 item at a time', and the most important bug: the container inventory window is automatically closed on the client
This happens because magic combat mode appears to be the only stance where the player takes a small step back during the crouch down animation. This step back is just enough to move outside of max looting …
> fixing magic pickup issue

- Source/ACE.Server/Managers/RecipeManager.cs
- changelog.md
Given the small handful of recipes that use this enum and based on the properties involved, it's apparent the "source" should always be the player/crafter and not the "source" per the Recipe.
These are the only properties affected:
* ALLOWED_ACTIVATOR_IID
* ALLOWED_WIELDER_IID
* CRAFTSMAN_NAME_STRING
> Fixed issue with Recipe Manager CopyFromSourceToResult not using the player as the source.

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This PR fixes 2 types of inventory stack bugs:
Bug 1:
- Have a partial stack of an item (249/250 stack size, for example) in your main pack
- Have a partial stack of the same item in the landblock, where merging the stacks would exceed the MaxStackSize
- Have the main pack full
- Attempt to pick up the partial stack from the landblock
Result before patch:
- Error, and the landblock stack poofs completely
Bug 2:
- Have a partial stack of a wielded item, such as arrows or phials wielded
- Have another partial stack of the same item in main pack, where merging the 2 stacks would still be < MaxStackSize
- Try to dequip the wielded stack by double clicking on it
Result before patch:
The client sends a packet to try to merge the wielded stack into the inventory stack, which resulted in an error …
> fixing inventory stack bugs

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
* Adjust some debug output
* Add overridden properties for region encounter generators
- override_encounter_spawn_rates
- encounter_regen_interval
- encounter_delay
* Allow camp generators to despawn 
- When a full "camp" is wiped, if the camp has a parent generator, destroy it so the parent generator can roll the slot again
> More Generator Adjustments

- Source/ACE.Server/Physics/Common/ObjectMaint.cs
- Source/ACE.Server/Physics/Common/Position.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Player_Tick.cs
This fixes some bugs and gaps in the object visibility system, without any major architectural changes
- Instead of calling handle_visible_cells() in the Player heartbeats if it hasn't been run in the past 5 seconds, only the DestructionQueue needs to be called. This ensures that even if a player hasn't changes cells recently, their destruction queue is still accurately maintained.
This prevents odd state situations where a previously known object re-enters visibility to a stationary player after 25s. This previously known object should be an unknown object at that time, and it should have been cleared out of the DestructionQueue (which it would on the next call to handle_visible_cells), but due to some odd state swapping with multiple operations happening on the same server frame, some …
> ObjMaint updates 1

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/CraftTool.cs
- changelog.md
* Add DoNothing ActOnUse to CraftTool.
* Adjust EmoteManager
- Wire up EmoteType.LocalSignal.
- Wire up EmoteCategory.ReceiveLocalSignal.
- Adjust EmoteType.Activate to fall back to linked generator if no activation target is specified.
* Add Landblock.EmitSignal to support localized object interaction.
> Add support for LocalSignal emotes

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionAcceptTrade.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionAddToTrade.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionCloseTradeNegotiations.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionResetTrade.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/Player_Trade.cs
- Source/ACE.Server/WorldObjects/Scroll.cs
This fixes additional bugs while reading scrolls, where it was possible to give the scroll to another player, move it to a landblock container, sell it to a vendor, or trade it to another player while the scroll was being read, thereby bypassing the original player's TryRemoveFromInventory
This has been known about for some time, and was originally fixed with dropping into the landblock originally. IsBusy checks have been added for all of these possible scenarios. 
/removespell <spell id> has been added to complement /addspell, and removes a spell from the player's  known spells / spellbook. This was used during testing to repeatedly learn/unlearn the same spell
The client actually prevents an item from being used while it is in the trade window, but it was still possible to start reading …
> additional IsBusy checks

- README.md
The 8.0 branch has signifant performance improvements over the previously linked 5.7.
The 5.7 is still listed as the minimum requirement
> Link to latest MySQL

- Source/ACE.Server/WorldObjects/CombatPet.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
This is fixed in a much better way in https://github.com/ACEmulator/ACE/pull/2086, but this fixes the current memory leak in v2
Thanks for @Mag-nus for tracking this bug down
> hotfix for objmaint v2 references

- Source/ACE.DatLoader/Entity/SubPalette.cs
- Source/ACE.DatLoader/Entity/TextureMapChange.cs
This allows other tools to instantiate these objects and set new values.
This is used by OptimShis Palette decoder and my retail character importer.
I was always on the fence about these dat properties being public. The risk is that a developer could modify a property in ACE. That property would then persist to the cached at object, and would be re-used until ACE was restarted.
This happens because dat objects are cached, and that same instance is returned on subsequent requests.
However, if we are ever to have 3rd party Dat editor tools, these properties will need to be public anyway.
> Make Dat SubPalette and TextureMapChanges properties public

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Fix unintentional change in cantrip RNG code for Epic and Legendary
> Fix unintentional change in cantrip RNG code

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Aetheria.cs
- Source/ACE.Server/Managers/PropertyManager.cs
This adjusts the Aetheria drop rates to be better aligned with retail data, and from community feedback from knowledgeable players
Previously, level 1-3 Aetheria all had an equal chance of dropping, and level 4-5 Aetheria both had the same chance of dropping
Some initial retail data (albeit very sparse, esp. for level 4-5) can be found here:
https://cdn.discordapp.com/attachments/417074022237601802/600013535510003712/aetheria_stats.csv
Drop chances for the previous code per magical item generated (100m simulated rolls):
```
at least level 1: 1 in 10
at least level 2: 1 in 10
at least level 3: 1 in 10
at least level 4: 1 in 100
at least level 5: 1 in 100
```
Drop chances for the updated code:
```
at least level 1: 1 in 100
at least level 2: 1 in 200
at least level 3: 1 in 400
at least …
```
> adjust aetheria drop rates, fixing drop rate mods

- Source/ACE.Server/WorldObjects/Player_Xp.cs
This fixes a bug where EmoteType.AwardLevelProportionalXP -> GrantLevelProportionalXp() doesn't award any XP for max level players
This bug was fixed in GetXPBetweenLevels() awhile ago, where for max level players it uses the XP between 274-275, but there was still an if check in GrantLevelProportionalXp() lingering around
> fix bug with level proportional xp

- Source/ACE.Server/Command/Handlers/SentinelCommands.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
- Source/ACE.Server/WorldObjects/House.cs
This removes the (based on STRENGTH 100) display in the client for missile weapons
Searched the retail pcaps for any instances where MaxVelocityEstimated != 0, and couldn't find any examples. If this is supposed to be set for things like Thrown Weapons, not sure what values to place in here
> removing max velocity estimated, not found in pcaps

- Source/ACE.Server/Factories/LootGenerationFactory.cs
When comparing https://github.com/ACEmulator/ACE/pull/1892 to current, there appears to be a 200x gap to cover here
There appears to be a missing factor from 1892 where there would be a pre-roll, where T7 would have 25% chance to drop no epics. So that would reduce the gap to 150x
Prior to https://github.com/ACEmulator/ACE/pull/2101, the rates were briefly bumped up, and this version was well-received from the CE player feedback. This version would further reduce the gap to 15x
This PR sets the default rates back to the pre-2101 rates, which seem to be a good balance currently
> re-adjusting epic cantrip rates

- README.md
- README_linux.md
The instructions in README.md now ask the reader to set up `ace_world`
with WorldBase.sql before applying incremental updates. This prevents more
recent `ace_shard` updates from producing an error due to a failed join with a non-existing table when `ace_world` hasn't been set up yet.
> Updated database instructions in README.md to prevent an error

- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
This fixes a bug that can occur with Throwing Clubs for example, where StackSize=4 and StackSizeVariance=0.1
MinStackSize is set to Math.Round(0.4) in this case, which becomes 0. This ensures the minimum stack size cannot fall below 1
This also points to another issue in the WieldedTreasure StackSizeVariance code, where MinStackSize should actually be defined as StackSize * (1.0f - StackSizeVariance). However, due to monsters lacking the logic where they decide to switch between ranged and melee, this code currently provides a reasonable counterbalance for now
> fixing StackSize 0 bug in WieldedTreasure

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Managers/PropertyManager.cs
This PR seeks to improve the way properties are set and the visibility of the different properties.
First is the addition of the "showprops" command which enumerates the different properties (in order by their data type) and then shows both their name, description and default value.
Now validation is also done on values passed in when setting an option, ensuring that the user knows whether the value was successfully set, or whether no setting existed with the given key. It's worth noting that it will also complain a key does not exist if it exists but has a different data type (this could be improved if necessary).
> Command to list runtime configuration properties

- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Right now whenever you give an item to a player or an NPC, it omits the material name prefix. This material name prefix should be present at all times when passing around or tinkering items with a material type. This PR adjusts the text to include the material name, but ensures that the item is neither stackable (which should never have a valid material) and that it has a material name specified, prior to including it in the output.
> Include material in give item message

- Source/ACE.Server/Factories/LootTables.cs
Further refining of the epic cantrips that are eligible for dropping on items to align with retail. Attributes should never be dropping on jewelry with the exception of rares.
> Remove attribute cantrips from jewelry.

- Source/ACE.Server/WorldObjects/Creature_Melee.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Player_Monster.cs
Right now it is possible to attack players, and to gain aggro on mobs, while you are still in portal space. Retail behavior was that you were considered unattackable while in portal space, meaning nothing would aggro you and all attempts to attack would fail to do any damage.
This PR adds a check for the Teleporting flag in a few places where we determine whether a target can be attacked, namely a player, since this is not applicable for mobs.
> Unattackable until exited from portal space

- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
Right now it is possible to use multiple recall commands as well as the PKL command simultaneously. You can test on the master branch by typing /mp and then immediately typing /pkl. You will notice that you become PKL just before you teleport to marketplace. You can use these commands while teleporting in portal space which will begin the timer for the action concurrently with the current teleport/action.
This PR adds a common check to determine whether a recall (or entering PKL) is possible at that time. It checks for whether the character is busy or is already teleporting.
> Add busy checks for recall/PKL commands

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/Player_Xp.cs
- Source/ACE.Server/WorldObjects/WorldObject_Set.cs
Repro steps:
- set a bunch of aetheria in the same item set to ItemTotalXp 0, equip them
- appraise player, /grantitemxp 5000000000
- dequip aetheria
Expected:
no spells from aetheria item set active
Actual:
spells from aetheria item set active
The error was placing OnItemLevelUp() inside of the ActionChain. Simply moving this method call outside of the action chain fixes the bug
To fix existing players in this bugged state is a bit more complicated, and the AuditItemSpells() method was added to handle this
> fixing bug for multiple items leveling simultaneously

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- changelog.md
Fixes an issue where you were unable to pick up null EncumberanceVal items. Specifically, the Gelidite Dais, but possibly others, too.
Testing Steps: 
-	Proceed to 0x546302A5 [216.357574 -70.013016 -5.995000] 0.667876 0.000000 0.000000 -0.744273
-	Pick up the Gelidite Dais.
-	Pick up another. And another. BECAUSE YOU CAN!
-	Reference: https://asheron.fandom.com/wiki/Gelidite_Dais
> Picking up null Burden items

- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
- float.Round() should be used instead of Math.Round(), to avoid possible off-by-1 errors
- additives should be applied after all multipliers, including vitae
> fix various vital enchantment calc errors

- Database/Optional/Shard/2019-07-12-00-Match_World_Spells_In_Biota_Enchantment_Registry.sql
- Database/Optional/Shard/2019-08-04-00-Match_World_WeenieType_In_Biota.sql
Server operators can run these scripts to periodically re-sync with newer database changes.
> Add refresh from world db scripts

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/Enum/SessionTerminationReason.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- changelog.md
* Update AuthenticationHandler to boot oldest connection to account when new one connects with valid login/password.
- Added new server configurable property `account_login_boots_in_use`, enabled by default retail rule.
> Account In Use changes

- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
Allow characters of accounts that have monarch-only housing on another character to be able to swear allegiance
> Allow Account Characters to Swear Allegiance

- Source/ACE.Server/Network/Managers/NetworkManager.cs
On CE this is using ~3 - ~6 ms, this should drop it down to ~1 ms
On my local test env, this drops it down from 3 ms to 0.8 ms
> Switch TickOutbound back to parallel

- Source/ACE.Server/WorldObjects/Creature_Death.cs
This fixes the unable to move errors that occur for 25 seconds after death, as well as requiring reloading the corpse to see the items after they disappear the first time
> Fix issue with creatures dropping their wieldables to corpses

- Source/ACE.Server/Network/Managers/NetworkManager.cs
Reverts ACEmulator/ACE#2237
Rolling this back until I can come up with a better thread sharing plan.
> Revert "Switch TickOutbound back to parallel"

- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Managers/ServerPerformanceMonitor.cs
- Source/ACE.Server/Managers/WorldManager.cs
Landblock tick management has been moved from WorldManager to LandblockManager
Individual landblock physics ticking has been moved all the way down to Landblock
Landblock now includes a 5m rate monitor in addition to the 1hr it already had
landblockperformance /allstats now reports a combined report from both 5m and 1hr rate monitoring.
> Relocate landblock tick code and add more detailed landblock tick performance measurements

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Replaces the EmoteType.RemoveVitaePenalty stub with the correct call
- Adds /remove-vitae developer command
- Fixes a bug where death was clearing cooldowns
> adding EmoteType.RemoveVitaePenalty

- Source/ACE.Server/Entity/DamageEvent.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This bug is showing up in the logs as DamageType.Undef when a monster launches its last projectile, and switches to melee combat while the projectile is in-flight, before it hits the target
A similar bug can also be reproed by the player, where you launch a prismatic arrow, and then dequip bow before the arrow hits the target
> fixing some gaps for swapping weapons after launching a projectile

- Source/ACE.Server/Factories/LootTables.cs
- Remove weenies that don't belong in loot and add some missing ones, per ac.yotesfan.com data
> LootTable Clothing Fix-Up

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- According to loot tier breakdowns, tiers 1 through 3 should not have a chance for a wield requirement on the caster; ref. http://acpedia.org/wiki/Loot
> Fix the GetWield method for magic casters

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperDatabaseCommands.cs
- Source/ACE.Server/Command/Handlers/HelpCommands.cs
- Added an optional &lt;access level&gt; parameter to filter /acecommands
If this is specified, and the current user's access level is at least the requested level, the output will show the commands specifically for that access level.
ie., if an Admin types /acecommands developer, it will show them just the commands with AccessLevel.Developer
if a regular player types /acecommands developer, it will not show them the developer commands, and will just show them the regular commands they would see from /acecommands
- Added the ability search /acecommands by keyword. Ex., /acecommands house
- Started to clean up the text for all of the descriptions for display in-game. Some parameters that were directly in the descriptions were moved to the "parameters" section of the command.
The commands …
> starting to clean up /acecommands a bit

- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
Reverts ACEmulator/ACE#2069
PlacementPosition references enum Placement, See [LongBow](https://github.com/ACEmulator/ACE-World-16PY/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/MissileLauncher/MissileWeapon/00306%20Longbow.sql) and other MissileLaunchers for example.
> Revert "PlacementPosition is not an enum type. It's an inventory order (index)"

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
Adds two new admin commands for (1) modifying the max vitals for an NPC or player, (2) modifying the skill levels for an NPC or player
https://github.com/ACEmulator/ACE/issues/2209 and https://github.com/ACEmulator/ACE/issues/2208
> Commands to modify max-vitals and skills

- Source/ACE.Server/Managers/GuidManager.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Added code to send DestroyObject messages from objects being destroyed to those that know about it when it is not on a landblock (Corpse/Chest/Container)
- Re-enabled Guid Recycling
> Guid Recycle Redux

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Managers/PropertyManager.cs
This option was requested, it seems that a number of players (including myself) would like an option for the aetheria / healing over time message color to be green or blue, instead of the red combat text color
> adding server option for aetheria healing over time message color

- Source/ACE.Common/ThreadConfiguration.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Network/Managers/NetworkManager.cs
This doesn't persist to the actual .config yet, but still provides a local way to manage thread count allocation.
> Add configuration for number of threads

- Source/ACE.Server/Entity/AddEnchantmentResult.cs
- Source/ACE.Server/Entity/EnchantmentStatus.cs
- Source/ACE.Server/Managers/EventManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventSendClientContractTrackerTable.cs
- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/Network/Structure/EnchantmentRegistry.cs
- Source/ACE.Server/Network/Structure/SquelchDB.cs
- Source/ACE.Server/WorldObjects/Armor.cs
- Source/ACE.Server/WorldObjects/Creature_BodyPart.cs
- Source/ACE.Server/WorldObjects/Managers/ConfirmationManager.cs
- Source/ACE.Server/WorldObjects/Managers/ContractManager.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/Managers/SquelchManager.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This helps better visualize the manager usage between
- server wide
- world object localized
I'm doing this because as I travel down the rabbit hole of server-wide thread safety, these types of separations help make it easier to understand what managers need more attention for thread safety vs world object localized managers that sould be thread safe because their parent wo should be thread safe (key word *should*)
I'll be adding thread safety to these server-wide managers and want to organize them better first to reduce the size of the multi-threading PR. This makes it easier to read, and easier to roll back if needed.
QuestManager remains in the server wide folder because it is used for both WorldObjects and Fellowships.
> Move WorldObject specific managers to a different folder

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
recently players were reporting errors with their godString... after examining the strings it seems as if sometimes an extra blank 'skill' is inserted into the string
i havent worked out exactly why but i added a check to the process so you wont be able to enter godmode if the string is not the proper length. this should prevent characters being stuck in godmode after entering with an incorrect string length
> add a check before entering godmode

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
This function has been verified as producing the same results as the original, while updating it to make it clearer / more readable, and fixing some gaps for spells that were being miscategorized
> updating GetProjectileSpellType

- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This allows items like WCID 35555 - Burning Bow to cast untargeted spells when they proc. Thanks to Cyberkiller for reporting.
> Allow items that proc to cast untargeted spells.

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/Key.cs
- Source/ACE.Server/WorldObjects/Lock.cs
also fixes a crash when using keyrarevolatileuniversal in current master
> adding support for PropertyBool.OpensAnyLock

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
Per a discussion on LSD discord, it was determined that Covenant Armor that contains spells will have Impenetrability as one of them.  While I tested the added code in game, it should probably be tested by others before merging to ensure that I didn't miss something, especially in regards to array indexing, if the added code is deemed acceptable.
> Ensure that Impen spell is present on magical Covenant Armor

- Database/Updates/Shard/2019-10-31-00-Fix-Magic-Absorption.sql
- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Warning: there are currently items in the database that incorrectly have PropertyFloat.AbsorbMagicDamage=1.0, instead of the correct percentage for magic damage they can absorb. These items need to be fixed in sync with this code update -- ie. for any existing players on the servers that already have items with AbsorbMagicDamage=1.0, the data for these items needs to be fixed in tandem with this code change.
Please do not check in this code change before all of the data corrections have been added
Updated: this PR now contains recipe fix (was code-based instead of data-based), and the above-mentioned SQL fix. Please notify server operators to be sure to run the sql shard update when they update to this version of the code.
This fixes https://github.com/ACEmulator/ACE/issues/2373
> enabling magic absorption for missile/magic weapons

- Source/ACE.Server/Entity/Actions/ActionChain.cs
This will help OnDeath emotes with 0 delay run on the next tick. This also has the added benefit of not deferring action chains 1 tick when delays are 0. For that specific scenario, another stub function has been added.
It's more difficult to run them on the same tick due to the way Emotes tick. If you want to ensure OnDeath emotes are run on the same tick, you can modify EmoteManager (ExecuteEmoteSet or Enqueue) to execute the emote right away instead of enqueueing it.
> EmoteManager AddDelaySeconds() only when > 0

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Entity/Enum/Skill.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
added a valid skills hashset to the skillhelper so that it could be checked against when entering godmode. also added hard coded checks against the attribute and attribute 2nd types... figured they didnt need a helper
this change will only add entries to the godstring if they are valid. 
According to ripley, the bug is with the GetOrAddSkill function that adds a skill to a players biota_properties_skill table when checking for invalid skill types. if a player had an invalid skill (typically this was a skill with type 0) the string would be too long and cause the error. now when entering godmode invalid skill and attribute values will be ignored and everything should work as intended
the only way an error when attempting to god/ungod should happen now is if the db is externally corrupted …
> add valid skills hashset, check valid skills entering godmode

- Source/ACE.Server/Entity/DamageHistory.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
a new function has been added, DamageHistory.GetTopDamager(bool includeSelf)
new logic has been added to prevent the following scenarios:
- a player should not be able to suicide during a pk battle and have themselves detected as the top damager (jumping off a cliff, harm self to death).
if a player is pk / pklite, and they are their own TopDamager, GetTopDamager(includeSelf = false) is called, to check if it is another player. If so, that player becomes the effective TopDamager, and is awarded the looting rights.
- if a pk / pklite is their own top damager, and the next highest damager is not another player, then the player remains their own effective top damager.
after this 'effective top damager' is determined, the IsPKDeath(topDamager) / IsPKLiteDeath(topDamager) calls also have logic …
> improved pk/pklite top damager detection

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
thanks to Yeonan for spotting this one:
https://asheron.fandom.com/wiki/Announcements_-_2003/01_-_The_Slumbering_Giant#Letter_to_the_Players
Example 1 - A mage is taking damage and would like to recover some health quickly. Using the level 1 health transfer spell, he takes 30 points away from a monster attacking him and receives 60 points in return. He does this a few times to help keep him alive while he tries to make a speedy retreat.
Example 2 - A mage has taken some damage, but well within what she can handle. She targets a nearby creature that has quite a bit of health. Using the level 7 health transfer spell, she takes 180 points of health away from the creature, and receives 90 in return.
> applying TransferCap to both srcVital and destVital for life transfer spells

- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/Monster_Tick.cs
- Source/ACE.Server/WorldObjects/Projectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
This patch updates the monsters in CombatMode.Missile (bow/crossbow/thrown weapons) to fix some gaps in their logic, and to bring them closer to retail.
Currently in ACE, monsters are depleting ammo for their ranged weapons, and stand their ground until they run out of ammo.
In retail, monsters appeared to have infinite ammo for their ranged weapons, and they decided to switch to melee mode based on other criteria:
- A monster will switch from ranged to melee if their target is beyond their MaxRange. They will then run in to close the gap.
- A monster will switch from ranged to melee if it has too many attacks that miss the target completely, and hit the environment.
> fixing some gaps for ranged missile mobs

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/Spell.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionMoveToState.cs
- Source/ACE.Server/Network/Motion/InterpretedMotionState.cs
- Source/ACE.Server/Network/Motion/MoveToState.cs
- Source/ACE.Server/Network/Motion/MovementData.cs
- Source/ACE.Server/Physics/Animation/MotionTable.cs
- Source/ACE.Server/WorldObjects/Creature_Vitals.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Attributes.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
- Source/ACE.Server/WorldObjects/Player_Vitals.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
this PR builds on top of https://github.com/ACEmulator/ACE/pull/2415
key scenario: if i cast Slowness on another player who is running, that player's RunRate should be affected immediately on both the server and client
currently in master, the player will continue to run at the same speed, until they release/re-press a movement key on their client
some temporary developer debug commands have been added to help test this, /fast and /slow, which invisibly cast QuicknessSelf8 and SlownessSelf8, respectively. The /dispel command is also useful.
Other scenarios handled: any spells which affect quickness/run/strength, and the player raising their quickness/run/strength while running/sidestepping
The previous Exhaustion detection system has been updated with this, and hooks have been added for …
> improved RunRate handling for players

- Source/ACE.Server/Entity/Probability.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
This bug can happen when the target creature dies from something else in the world, at just the right time in the melee chain. Only happens when repeat attacks is disabled (usually players running with vtank)
Repro steps:
I was able to repro this bug with Dirty Fighting middle melee attacks (bleed dot when it lands). Set repeat attacks to disabled, and run with vtank
(also throwing in some random spellcasting helper functions that have been sitting around for awhile, currently just used for debugging / uncalled otherwise)
> fixing a possible lockup during physical combat when auto repeat attacks is disabled

- Source/ACE.Server/Entity/DamageHistory.cs
- Source/ACE.Server/Entity/DamageHistoryEntry.cs
- Source/ACE.Server/Entity/DamageHistoryInfo.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Move.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This patch minimizes the reliance on DamageHistory WeakReferences
The main purpose of this patch is to fix the effects of a long-standing bug where DamageHistory WeakReferences to valid Players and WorldObjects are somehow going null.
In current master, this results in PKDeaths not being detected as PKDeaths, and causes a bug where players drop their items and accumulate vitae in PKLite mode
This patch also fixes some other bugs with over-reliance on WeakReferences, such as:
- A monster damages a player for 75% of their health, and then the player kills the monster. Another monster then kills the player. In this scenario, the TopDamager for the 'Killed by' message on the player's corpse was reading 'Killed by misadventure.', since it was relying on a full reference to the TopDamager …
> minimizing DamageHistory.WeakReference

- Source/ACE.Server/Entity/IPlayer.cs
- Source/ACE.Server/Entity/OfflinePlayer.cs
- Source/ACE.Server/Managers/AllegianceManager.cs
- Source/ACE.Server/WorldObjects/Allegiance.cs
- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
This builds on https://github.com/ACEmulator/ACE/pull/2421 from @LtRipley36706 
The core scenario for this: join an allegiance, and then recall to allegiance housing with /hom. You will end up with a black screen.
You can also join an allegiance, and if you try to run into the allegiance house, you will run into a barrier still (not sure how this was missed..)
A similar situation, if you break allegiance to your patron while standing outside of the Allegiance house, you will still be able to run into it afterwards. Similarly, if you were standing inside the Allegiance house at the time of the break, you will not be booted.
The core issue for this was the client needs to be sent the MonarchID, and it uses this to determine / update the barrier protections.
This PR also fixes a bunch of …
> send updates to Monarch ID over network, and adding some missing calls to allegiance house boot

- Source/ACE.Server/Entity/DamageEvent.cs
- Source/ACE.Server/Factories/LootTables.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
So this started with digging into an off-by-1 error for Crippling Blow, and then went down the rabbit hole of fixing some issues with Critical Strike, and figuring out more of the details with that, which eventually lead to finding some scaling issues that mostly affect people who aren't at the caps for imbues yet.
Along the way, I ended up cleaning up a lot of WorldObject_Weapon, and moving around some of the functions in that file for better organization / readability. The moving around of some function positions in the file unfortunately makes the git diff a bit confusing to read through, but all of the functionality is the same there, just moved around and refactored a bit.
Tested the 4 key imbues: Critical Strike, Crippling Blow, Elemental Rend, and Armor Rend, and verified that all …
> WorldObject_Weapon / imbue refactoring

- Source/ACE.Server/Physics/Common/WeenieObject.cs
- Source/ACE.Server/Physics/ObjectInfo.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
This fixes the bug with TA char positions getting bumped around
> reversing exemption checks, adding missing WeenieObject.IsTypes

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Move.cs
When a corpse or a chest is double clicked, the server always performs a MoveTo and waits for it to successfully complete, before showing the container inventory
If the player then rotates their character away from the container, but stays within UseRadius range, and then loots an item, they should NOT be doing a 2nd MoveTo / rotate in this case.
See retail video:
https://youtu.be/JApdqG-oJps?t=155
Thanks to Damage Master for reporting this issue!
> removing player.rotate during looting that wasnt in retail

- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
This fixes a bug where a monster that wakes up from spotting a player, then the player goes out of range and the monster returns to home / falls back asleep, then another player wakes the monster up again, the monster was not returning to the correct combat state again.
Repro steps:
/teleloc 0x654A011E [54.633018 -31.307457 0.005000] 0.672991 0.000000 0.000000 -0.739651
Note any rock-throwing lugians and archer tumeroks are behaving correctly
Run back to the entrance portal of the dungeon, and exit the dungeon
Re-enter the dungeon portal
Run back to those same monsters
Expected: same as before
Actual: monster will be in non-combat mode, but launching projectiles without doing any animations. The tumeroks are especially bugged, where they are launching arrows faster than normal
This patch …
> fixing monster resleep -> wakeup cycle for combat mode

- Source/ACE.Server/Entity/DamageHistory.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
This fixes some subtle errors that were possible when divvying up XP earned from killing a creature
Example mob in all of these scenarios has 100/100 health
Scenario A:
Player deals 90 direct damage to monster, and then lands a DF bleed attack. The DF bleed deals 30 damage to the monster, resulting in 120 in the damage history. The player was earning 120% of the xp for the monster in this case.
Scenario B:
Player deals 90 damage to monster. Monster is now at 10/100 health.
Monster than casts a spell which raises its MaxHealth by 20. Monster is now at 10/120 health.
Player then kills the monster. In this case, the player was only earning ~83% of the XP for the mob.
Scenario C:
Player deals 90 damage to monster. Monster is now at 10/100 health.
In this case, the monster had a …
> xp divvy accuracy

- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Portal.cs
Moving objets across thread boundaries is a funciton of the WorldManager, not a Player
> Move ThreadSafeTeleport to WorldManager

- Source/ACE.Server/Physics/Common/EnvCell.cs
Repro steps:
```
DatManager.PortalDat.ReadFromDat<MotionTable>(0);
DatManager.PortalDat.ReadFromDat<ACE.DatLoader.FileTypes.Environment>(0);
```
> preventing crash in EnvCell constructor from other state in the system

- Source/ACE.Server/Program.cs
Bug: many game functions that don't explicitly specify InvariantCulture are breaking with other cultures
Repro steps:
Change the CultureInfo in the PR to sv-SE
```
/grantxp 1000
1 000 experience granted.
/tele 74.3S, 21.9E
North/South coordinate is not a valid number.
```
> setting default CultureInfo en-US

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/Enum/ResistMask.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
The main purpose of this patch was to fix a bug where appraisal was showing Mana Conversion Bonus: +0% for a many casting items
At first I thought this was a bug in the loot generator, but after discussing it with @harliq, it turns out there are actually many casting items with base weenies that have PropertyFloat.ManaConversionMod=0 in the data
So to account for this, Appraisal is now checking if ManaConversionMod exists, but is 0, it removes it.
I also noticed some possible bugs with Hermetic Void, which sounds like it is cast on the wand, similar to the other item debuffs. The logic for ManaConversionMod enchantments should be taking both auras and spells cast directly on the item into account for this.
Update: it has been discovered from retail pcaps that retail also had this bug. …
> mana conversion mod tweaks

- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
Adding this check just for completeness
I ran this additional check on the ce shard, and it found no instances of players having untrained skills where xp/ranks > 0
> additional check for verify-skill

- Source/ACE.Entity/Enum/CharacterOption.cs
This is an update from Yonneh, to fix an issue with decal plugins calling GameAction 5 - SetSingleCharacterOption for various options
Whoever originally wrote CharacterOption did not match up the names and ordering of this enum with PlayerOption in acclient. It looks like they started to, but then jumped around to use the ordering in the UI options display, and did not properly set all of the # values.
I have verified that this fix does not break any of the existing character options / db ordering in ace
> fix CharacterOption to match acclient PlayerOption ordering

- Database/Updates/Shard/2019-12-13-00-Remove-All-FirstEnterWorldDone.sql
- Source/ACE.Entity/Enum/Properties/PropertyBool.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionSetCharacterOptions.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
* Switch `FirstEnterWorldDone` to ephemeral property
* Add SQL script to remove all `FirstEnterWorldDone` properties from shard DB
* Set FirstEnterWorldDone to false in Player ctor if previous script is not run
* Existing code already sets to true appropriately, when client reports a successfully completed login.
* Add a check in GameActionSetCharacterOptions for FirstEnterWorldDone being completed before processing and persisting.
> Support FirstEnterWorldDone on Players

- Source/ACE.Server/Network/ClientPacket.cs
- Source/ACE.Server/Network/NetworkSession.cs
Fixed bug that occurs when client sends only a cleartext CRC NAK and ACE ignoring them, switch from honoring only ciphertext CRC NAK to honoring only cleartext CRC NAK
> fix for ignored C2S NAK

- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
It appears that the casting damage modifier being used for PvP mode is in fact unaffected by the PvP modifier for weapon damage, so it is using the PvM caster modifier instead. This patch includes the `modifier` which is the piece that includes reduction of the caster modifier for PK purposes.
> Fixed caster damage modifier to use appropriate PvP modifier instead of PvM

- Source/ACE.Server/Factories/LootTables.cs
Fixed the following Spell IDs to look up the correct scroll.  The last 2 errors are from invalid weenies (can't create weenie)
Spell IDs Errors from CreateRandomScroll
--
Old Spell ID | Spell | New Spell ID
1886 | Evaporate Creature Magic Self | 1888
1892 | Extinguish Creature Magic Self | 1894
1898 | Cleanse Creature Magic Self | 1900
1904 | Devour Creature Magic Self | 1906
1910 | Purge Creature Magic Self | 1912
1916 | Scroll of Nullify Creature Magic Self | 1918
1919 | Evaporate Item Magic | 1921
1925 | Extinguish Item Magic | 1927
1931 | Cleanse Item Magic | 1933
1937 | Devour Item Magic | 1939
1943 | Purge Item Magic | 1945
1949 | Scroll of Nullify Item Magic | 1951
1958 | Evaporate Life Magic Self | 1960
1964 | Extinguish Life Magic Self | 1966
1970 | Cleanse Life Magic Self | 1972 …
> Fix Spell IDs from CreateRandomScroll

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
Made getting MagicD and MissileD modifier the same across all weapon types.  Also fixes Missile Weapons not receiving a chance of getting a MagicD modifier bonus.
Also neatened up Melee Factory to comply with StyleCop
Tested with loot sim to make sure drops are correct.
> Magic and Missile Defense Modifier Bonus simplifcation/fix

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
/targetloc developer command now supports specifying an exact guid, in addition to the default mode of last appraised object
This guid can be a landblock object that is anywhere on the server, and it will find it
PhysicsObj.CurCell has also been added to the output, and these 2 features will help debug some of the generator issues that CE has been seeing
> improved /targetloc

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Database/ShardDatabaseWithoutCaching.cs
This makes the legacy code for bypassing EF tracking for non player biotas back into master, and optional.
This will make it easier for ACE devs to update this legacy code for those servers that still require it, reducing the amount of work they'll have to do to merge to latest when certain schema changes happen.
> ShardDatabaseWithoutCaching

- Source/ACE.Entity/Enum/Properties/PropertyFloat.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This fixes a bug where a successful appraisal could then blip off to an unsuccessful attempt again (possibly automatically, for appraised combat targets)
With this change, some rate limiting for unsuccessful attempts also needs to be introduced. If a player were to be allowed to spam the server with unsuccessful appraisal attempts in a non-throttled manner, they would be able to get that '1 successful attempt' near instantly, negating most of the appraisal skill check
> additional logic for repeated appraisals

- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Wired up AdminSpam and BLog for assumed alert/logging
- Wired up InqBoolStat based on emote tester npc from 16py
Not sure if TestNoQuality is used for any other Inqs, seems like if it is, it would have to be cascading based on existing emotes: 
InqXStat
Success, goto TestSuccess
Fail, If null goto TestNoQuality only if defined, else goto TestFailure?
> Add/Adjust some Emote handling

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/GeneratorProfile.cs
- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
http://acpedia.org/wiki/The_Moars
Use the Emerald Clasp on the Adjanite Gem to create Decorated Adjanite Gem.
Both objects are contained but Clasp has ItemUseable.SourceContainedTargetRemote flag, was also this way EoR
https://github.com/ACEmulator/ACE-World-16PY/blob/master/Database/3-Core/4%20CraftTable/SQL/04774%20Decorated%20Adjanite%20Gem.sql
> Fix issue with VerifyUse

- Source/ACE.Server/Managers/QuestManager.cs
- Source/ACE.Server/WorldObjects/Portal.cs
Some portals have quests that require reflagging after the flag "expires" based on quest definitions for max solves and min delta
Haunted Mansion, Aug Gem/Bellas are examples
> Enforce quest timers for Portal.QuestRestriction

- Source/ACE.Database/ShardDatabase.cs
This shouldn't happen under normal circumstances, but is possible if a player biota has been deleted from the db, or something has seriously gone awry..
> adding null pointer prevention to GetAllPlayerBiotasInParallel()

- Source/ACE.Server/Config.js.example
This lines up with the ACE install on windows wiki. I've seen others using the same directory structure as well before this documentation update:
https://github.com/ACEmulator/ACE/wiki/ACE-Hosting-Windows
> Update default dats path on windows

- Source/ACE.Server/Factories/LootGenerationFactory.cs
Upped Melee D Bonus for no wield wands up to 10% from 5%.  That is what data supports from Optim.
> Upped Melee D Bonus for no wield wands upto 10% from 5%. 

- Source/ACE.Server/Command/Handlers/CommandHandlerHelper.cs
With the latest appraisal changes, server commands which use the last appraised object were failing if the last appraised object was a monster that returned ???'s
Thanks to @harliq for discovering / reporting this bug
> updating GetLastAppraisedObject()

- Source/ACE.Server/WorldObjects/Player_Magic.cs
For PKTypes, if the target is removed from the landblock while the player is doing the initial TurnTo, there was a gap here where OnCastDone wasn't being called
> fixing 1 gap for pk casting

- Source/ACE.Server/WorldObjects/Player_Move.cs
This fixes the bug where a PK/PKL could 'use' an object on the other side of a trap, effectively running across the trap without triggering it
Thanks to @Jkurs and @CrimsonMage for reporting this issue
> ensure pktypes are calling the correct MoveTo function

- Source/ACE.Server/Command/Handlers/DeveloperLootCommands.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
- Source/ACE.Server/Factories/LootStats.cs
Added support for Armor Equipment Sets in armor table
Added Aetheria counters and table.
Added Logging LootSim stats. Example Command
```testlootgencorpse 998 100 armor -log```
File is written in startup folder (same as ACE_Log).  Its named "Loot-Sim" + Time and date.  Example ```LootSim-08-36-06-PM_02-04-2020.csv```
File is in csv format for using in spread sheet
> Loot sim update

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
Good description here: https://stackoverflow.com/questions/7499384/does-the-order-of-linq-functions-matter/7499454#7499454
This is something easy to get into master while we think about using the dictionary cache that Ripley has made.
> EmoteMananger: Where before OrderBy

- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes a bug with 32359 Glenden Wood Recall Orb
Repro steps:
/ci 32359
equip orb
go into magic combat stance
select self
try to cast built-in gw recall spell
Expected:
spell is cast successfully
Actual:
player has a chance of resisting spell, which they usually did in previous version
> cleaning up spell resistance code

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This will effectively make TakeItems not show output message if player has 0 items
@DridsGhost
> suppress TakeItems output when player has 0 items

- Source/ACE.Server/WorldObjects/Player_Spells.cs
Repro steps:
- equip 2 items from the same spell set
- dequip 1 of the items
- relog
Expected:
- no AuditItemSpells error, spells from 1st item remain
Actual:
- AuditItemSpells error, spells from 1st item do not remain
The reason for this is the way dequpping items from spell sets works for re-casting the previous level of spells. Instead of getting a new (random?) item that is still equipped from the set, it sets the caster guid to the item that was dequipped.
In the future, it could be investigated if we should set the caster guid to another (random?) item that is still equipped from the set
> fixing AuditItemSpells for spell sets

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
When specifying resource types, the order of the parameters no longer matters
These are all valid:
/import-sql tuskerguard
/import-sql tuskerguard weenie
/import-sql weenie tuskerguard
Similarly:
/import-json tuskerguard
/import-json tuskerguard weenie
/import-json weenie tuskerguard
Same for other content types:
/import-sql 1234 landblock
/import-sql landblock 1234
This feature has also been added to export commands.
In addition, when exporting weenies, either the wcid or the classname can now be specified.
> minor QoL improvements for content dev commands

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/LandblockManager.cs
scenario: some NPCs that continually cast spells at regular intervals / on heartbeat emotes, are now keeping landblocks alive forever
the 'rolling ball of death' rooms in gaerlan's citadel and oswald's dagger quests would be a good example of this
confirmed that updated version still fixes the original bug using previous setup and repro steps
> spell projectile dormant fix redux

- Source/ACE.Adapter/ACE.Adapter.csproj
- Source/ACE.Database/ACE.Database.csproj
Not sure why they were 2.1.
2.0 is the latest that's supported by desktop apps. Moving these two libraries back to 2.0 makes them easier to consume.
> Remove .net standard 2.1 from Adatper and Database

- Source/ACE.Server/Entity/MagicState.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionMoveToState.cs
- Source/ACE.Server/Physics/Managers/MoveToManager.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Tick.cs
Repro steps:
- Be in magic combat stance
- Be turned slightly away from target, ie. at a 45 degree angle
- Start running forward
- While running forward, press key to cast a targeted spell
Expected:
- Character stops, does a turn to, and begins casting spell
Actual:
- Character stops, would start turning to, but then would begin casting spell almost immediately, without fully turning towards target on client.
The server TurnToHeading method was not matched up with acclient, and was not waiting for the previously in-progress run animation to complete first, before performing the TurnTo
Updated - now includes much more significant improvements for taking manual control of TurnToTarget during magic casting
> fix minor sync issue in TurnToHeading, rework TurnTo during magic casting to allow for player manual control

- Source/ACE.Server/WorldObjects/Creature_Properties.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
A few bugs here:
- AugmentationResistance was in EnchantmentManager before, which was an odd place to put it. There might be caching issues if the enchantment cache isn't cleared out when augs change.
- AugmentationResistance in its previous EnchantmentManager location was only in GetResistanceMod(), which gets the combined prot + vuln resistances. 
This particular method was split up into 2 sub-methods when natural resistances were introduced: GetProtectionResistanceMod and GetVulnerabilityResistanceMod. So combat was effectively no longer calling the original combined method, yet some other odd places like appraisal were. It just seemed like AugmentationResistance was crammed into EnchantmentManager, even though it wasn't really the right place for it.
- AugmentationResistance was …
> fixing aug resist

- Source/ACE.Server/WorldObjects/Player_Magic.cs
Repro steps:
- Go into magic combat stance
- Turn away from target
- Start casting targeted spell
- Very quickly, right before the the TurnTo has completed, right before the Windup, tap ` to go out of combat mode
Expected:
Server doesn't crash
Actual:
Server crashes
> fix cast tick gap

- Source/ACE.Entity/Enum/Properties/PropertyFloat.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
Repro steps:
- /create 38446
- appraise chest
- /setproperty PropertyFloat.ResetInterval 15
- /crack
- open chest
- take a step back, to close chest immediately
- appraise chest, /crack
- wait until slightly before 15 seconds after last opening
- open chest
Expected:
- chest stays open for 15 seconds
Actual:
- chest was closing almost immediately
> fix chest reset interval

- Source/ACE.Server/Managers/HouseManager.cs
- Source/ACE.Server/WorldObjects/House.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
This fixes a couple of issues with HandleActionQueryHouse:
- If the house landblock / slumlord inventory takes a particularly long time to load on the server, the player would get a 'warning! you have not paid your maintenance costs' message, even if the slumlord inventory is potentially paid already.
This was the result of some older code that was commented as 'needing a slumlord inventory callback'. This callback system was already implemented for HouseManager, so HandleActionQueryHouse() has been updated to use a proper callback, instead of waiting an arbitrary amount of time for the slumlord inventory to load.
- For servers running in '1 house per account' mode (the default), if a player who wasn't the direct house owner logged in, the house panel was showing 'Bought: N/A', which was …
> update house query

- Source/ACE.Server/Network/NetworkSession.cs
- limit the number of sequence IDs per S2C NAK packet: this alleviates the problem of the server sending huge packets.
- fix possible problem with a C2S packet sequence received that is previous to the current position.
- NAK packets aren't re-transmitted in AC protocol, don't store them in S2C cache
This has been thoroughly tested locally and in CE and consensus is that the main problem of _oversize retransmission packets being sent to client_ is fixed by it.
> Fix oversize NAK packets being sent to client.

- Source/ACE.Server/Entity/DamageHistory.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Tracking.cs
- Source/ACE.Server/WorldObjects/Player_Vitals.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This PR replaces a bunch of hooks scattered around the codebase for UpdateHealth for the attacker
The 'selectedTarget' system has been upgraded to use WorldObjectInfo, and to have ties directly into DamageHistory
Some gaps that this covers:
- Player A and Player B are both attacking the same creature. While Player A is doing damage to the creature, Player B previously did not receive the instant health updates.
- A bunch of missing hooks all throughout the system, for healing, vital ticks, etc.
> filling some gaps for instant vital updates for targeted creature

- Source/ACE.Server/WorldObjects/Creature_Properties.cs
ironically, the original formula in enchantment manager was correct, just possibly in the wrong place..
> fixing resist aug (again)

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
This PR has further improvements for spell projectiles, regardless if spell_projectile_ethereal is enabled or disabled
- Point-blank collisions now play the effects more consistently across all spell types. The lightning bolts, for example, no longer linger around. The launch effects also always play for point-blank collisions (more particle effects)
- The network message broadcasting for point-blank collisions has also been cleaned up slightly, so that the special 'broadcaster' variable is no longer needed.
> further cleanup for spell_projectile_ethereal

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/PositionExtensions.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageUpdatePosition.cs
- Source/ACE.Server/Network/Structure/PositionPack.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Repro steps:
- /god (for mega jump)
- /pk pk
- do a standing jump forward, @ full jump power
- type /rip in chat window immediately after leaving the ground
Expected:
- corpse spawns in midair, near the apex of the jump, and continues the previous trajectory of the jumping player, eventually falling back to the ground
Actual:
- corpse spawns frozen in midair, near the apex of the jump
This PR persists the physics velocity (used only for jumping) of the dying creature to the corpse, causing the expected behavior
I have confirmed that ACE is correctly / automatically updating the latest position of the corpse to the database, after it lands. This can be seen with using /reload-landblock after the corpse falls to the ground.
One caveat is: since Velocity is a runtime-only field, and not …
> fix corpses spawning frozen in mid-air

- Source/ACE.Server/Entity/AddEnchantmentResult.cs
Repro steps:
- Cast Focus 1, Focus 2, and Focus 3
Expected:
- Enchantment message reads 'Focus 3 surpasses Focus 2'
Actual:
- Enchantment message reads 'Focus 3 surpasses Focus 1'
> fixing display bug for enchantment messages

- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
From Drid:
/teleloc @teleloc 0x58630188 [20 -80 -53.944] 0.9999459 0 0 -0.01039798
They rotate, but no longer cast spells in the correct directions, they're "stuck"
> update physics rotation on EmoteManager.Turn

- Source/ACE.Server/WorldObjects/Player_Magic.cs
Thanks to Murk for reporting these issues
For life projectiles, the calls to TryResistSpell and OnAttackMonster should not be happening in the base life magic method, at the moment these spells are cast. These were effectively duplicate calls for life projectiles, and the 'real' calls should be the only ones happening when the spell projectile hits the target creature.
> moving duplicate code for life projectiles

- Source/ACE.Server/WorldObjects/WorldObject.cs
With recent changes to ProjectileTarget, ranged mobs are (incorrectly) no longer launching projectiles if their shots are blocked by other mobs
> updating LoS tests for recent changes to ProjectileTarget

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Monster_Inventory.cs
Repro steps:
/create bandit
Expected:
Bandit is wielding normal weapons
Actual:
Bandit frequently spawns incorrectly wielding a bow and a melee weapon simultaneously
I tried implementing this PR a few different ways, and this is the current version. It changes things up a tad in CreateList and WieldedTreasure being wielded slightly, but it seems like it should produce the same results, with the expected behavior and bugs fixed
> fixing bandits dual wielding bow + melee

- Source/ACE.Server/Managers/RecipeManager_New.cs
In the final version of the trinkets that Drid made, the previous exclusion code in RecipeManager_New is no longer needed
The requirements were also slightly misunderstood, and things like applying Pine Salvage to trinkets should be possible.
This also ensures that applying cantrip salvage to trinkets is not possible
Thanks to @CrimsonMage for discussing some of the details for this part
> update coded recipes for trinkets latest version

- Source/ACE.Database/SQLFormatters/SQLWriter.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Entity/GeneratorProfile.cs
- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
This reverts commit 640847bf55f1de011f3d0a44569782f5c88a1895.
This patch causes the Pathwarden armor to appear as the wrong color (incorrect black color)
I think it might have something to do with null coalescing, ie. maybe the original data format had a way to distinguish between 'no shade' / null shade and shade=0
The current data format appears to be using non-nullables, so I'm not sure how to make this distinction with the current data format
Sending a revert for this patch until someone can chime in with the proper solution
> Revert "fixing shade=0, from optimshi (#2870)"

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
Currently if you `/god` and you can not `/ungod` you'll hit:
`Exception ( System.Private.CoreLib - Input string was not in a correct format. ) caught while {player} was attempting to return to normal from godmode.` Due to the godstate string having the string value of SkillAdvancementClass.
This PR serializes as uint, but also handles encountering the string in order to restore characters that have `/god` in the past week.
> Fix ungod failing on SkillAdvancementClass

- Database/Updates/Shard/2020-04-07-00-Add-Order-To-Biota-Properties-Palette.sql
- Source/ACE.Database/Adapter/BiotaConverter.cs
- Source/ACE.Database/Adapter/BiotaUpdater.cs
- Source/ACE.Database/Models/Shard/BiotaPropertiesPalette.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Entity/Models/Biota.cs
- Source/ACE.Entity/Models/IWeenie.cs
- Source/ACE.Entity/Models/PropertiesAnimPartExtensions.cs
- Source/ACE.Entity/Models/PropertiesPaletteExtensions.cs
- Source/ACE.Entity/Models/PropertiesTextureMapExtensions.cs
- Source/ACE.Entity/Models/Weenie.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
This fixes corpse palette ordering after a server restart.
This has a shard database update that is required.
> Add order to BiotaPropertiesPalette

- Source/ACE.Server/WorldObjects/Monster_Tick.cs
Repro steps:
- /create tuskerguard
- continuously walk backwards
Expected:
- Tusker Guard runs to target, stickies to them, takes a swing, then repeats this process
Actual:
- Tusker Guard continuously runs to target / stays stickied to them, but does not take swing
> improving monster sticky melee -- moving sticky update before position / distance check

- Source/ACE.Server/WorldObjects/Player_Location.cs
Repro steps:
- /pk pk
- go into magic combat mode
- /mp
- observe: /mp immediately goes into non-combat mode and makes the magic combat bar disappear from the client (correctly). however, the player is still left in magic combat mode on the server
- after recalled to mp, try to go into magic combat mode again
- observe: the magic combat bar comes up on the player's screen, but they remain in non-combat stance
- try to cast a spell
Expected:
- Player goes into magic combat stance correctly, and is able to cast a spell normally
Actual:
- Player doesn't go into magic combat stance the first time, and gets a Busy / stance error when trying to cast a spell
Also a subtle animation timing bug with many of these recall commands: if the player starts from a combat mode, the animation timer is not …
> fixing bug with marketplace recall

- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
This also fixes the error messages that were being thrown by MagTools:
```
<{Mag-Tools}>: Unable to parse damage element from: You bleed <name> for <amount> points of periodic damage!
```
> updating Surge of Affliction + show_dot_messages for something more appropriate

- Source/ACE.Server/Network/GameAction/Actions/GameActionBookData.cs
- Source/ACE.Server/WorldObjects/Player_Book.cs
When a book is blank, client automatically adds a "blank" page after opening, sends it to server and upon successful page add response it then sends 0x00AA, expecting BookData response or the page/book is not writable or usable, unless it is closed and opened again.
This fixes that.
> Fix writability issue with opening "blank/empty" books.

- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/Models/World/WorldDbContext.cs
- Source/ACE.Database/ShardDatabase.cs
This enables these options (that were originally added by Ripley) for release build on both shard and world databases.
It still remains disabled for Auth to avoid "secrets" being logged.
> EnableSensitiveDataLogging for shard and world

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Add missing stamp action on the update existing quest branch of UpdateFellowQuest and UpdateQuest emotes for the canSolve scenario
Tested failure and fix with Eldrista the Adventurer and turn-ins of Lilitha's Broken Bow.
http://acpedia.org/wiki/Lilitha%27s_Lost_Bow
> Fix gap in UpdateQuest emote

- Source/ACE.DatLoader/FileTypes/CombatManeuverTable.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This fixes the issue where certain combat maneuvers are cycling through 2 separate animations
These 2 separate animations should correspond to 2 different power levels
Thanks to @CrimsonMage for discussing this issue
> more CMT fixes for players

- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Corpses that generate rares can only be looted by killer
- Corpses for players killed by other players can only be looted by killer and victim, no permit/consent allowed
> Update Corpse permission conditions

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This should never happen under normal circumstances, but is possible if the player has an item in their inventory that is no longer in the world database
> preventing server crash / handling some edge cases more gracefully

- Source/ACE.Common/OfflineConfiguration.cs
- Source/ACE.Server/Config.js.docker
- Source/ACE.Server/Config.js.example
- Source/ACE.Server/Program_DbUpdates.cs
Adding 2 optional options for the auto application of world customization.  
A configurable array of added paths to source SQL files from on top  of the default/configurable value.
And secondly an option to search the individual paths recursively for SQL files.
This helps with enabling content teams to have their own content strategy as far as how they structure their output in different places with different levels of organization.
> Adding extra options for AutoApplyWorldCustomizations

- Source/ACE.Common/NetworkSettings.cs
- Source/ACE.Server/Config.js.docker
- Source/ACE.Server/Config.js.example
- Source/ACE.Server/Network/Managers/NetworkManager.cs
This will allow an IP exception list for the max number of sessions per IP.  The use case for this would be for accounts that may have multiple bot accounts (buffbot, craftbot, portalbot), but still may want to actively play their non-bot characters.  Or in the instance where an admin/dev needs to do testing of content across multiple accounts.
> Adding ability to exclude specific IPs from max session count.

- Source/ACE.Server/Command/CommandManager.cs
- changelog.md
Allowed console commands to start with "/" or "@". Would previously respond with "Invalid Command" if the command started with a "/" or "@". Also allows commands to be used consistent with the "acecommands" output.
> Made console commands consistent with in-game

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
This fixes a potential crash if magtools automatically does a background appraisal of an inventory object before /removeinst is run
Possible todo: since /removeinst is only run on landblock objects, we should be able to use 'currently selected target' instead of 'last appraised target' here
Negative on the last suggestion -- selected object only works for things with health / mana, so this wouldn't work for things like generators
> ensure object is on landblock for /removeinst

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
Repro steps:
teleport to an empty landblock
/createinst tuskerguard
/createinst tuskerguard FFF
/createinst tuskerguard
Expected:
1. Creates a new landblock instance for tuskerguard, using the next free static guid for the landblock (ie. 000)
2. Creates another using the highest static guid for the landblock (FFF)
3. Creates another using the next actual free static guid for the landblock, taking gaps into account (ie. 001)
Actual:
For this set of repro steps, the old version also had a preliminary bug for FFF. It originally considered FFE to be the highest static guid for that landblock, due to an incorrect concern that adding 1 to FFF in landblock FFFF would overflow back to 0. This is not the case however, as FEFE is the max landblock, and everything is prefixed with 7XXYY instead of …
> adding createinst gap finder

- Source/ACE.Server/WorldObjects/Player_Spells.cs
For non-set spells, this restores the original functionality to AuditItemSpells to check if the item is equipped, instead of just being in the player's inventory
This equipped check was originally in the game for both set and non-set spells, but due to the way set spells worked, it had to be scaled back to only checking 'allPossessions' instead of EquippedObjects
Tested and confirmed this works as intended, doesn't remove any erroneous spells, and retains the expected functionality for set spells as the existing master
> improving AuditItemSpells

- Source/ACE.Server/Entity/Cloak.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This starts to add support for PropertyInt.CloakWeaveProc=2 on cloaks, which was originally missed / possibly overlooked and assumed to be just another spell
Physical damage and spell projectiles are wired up for this proc type, with some life spells still pending after figuring out some more details
Updated: everything is now wired up: physical damage, spell projectiles, and life magic drain / harm other spells
Open questions:
- https://asheron.fandom.com/wiki/Cloaks has the message as 'Your cloak reduced the damage from 162 down to 0!'. Was this message sent only the wielder of the cloak, or was a version of the message also sent to the attacker, or broadcast to the local area, similar to Aetheria procs?
Resolved questions:
- Did this cloak proc message appear before or after the …
> adding support for cloak damage reduction procs

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
Example usage:
Appraise a landblock instance, ie. one previously created with /createinst
/nudge x 5
/nudge north 5
/nudge w 5
/nudge here
/rotate north
/rotate s
/rotate 0
/rotate 90
/rotate here
> adding /nudge and /rotate content dev commands for landblock instances

- Source/ACE.Server/WorldObjects/Creature_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
Scenario: A player attacks with a 2-handed weapon that can cleave 1 additional target.
With the previous logic, it was possible to kill a maximum of 3 targets with the 2 swings: the first swing kills the main target, and kills 1 add. The subsequent swing is always locked onto the main target, so the second attack against the dying main target is ineffective. But for the adds, each swing was previously re-selecting any valid nearby adds.
Here is a retail video demonstrating that the 2nd swing would still be locked onto the original add, and that each swing would not re-select any new adds:
https://youtu.be/F4rRCjiFqoI?t=578 (9:40-9:41)
So in essence, the adds are only selected once on the first swing, and the subsequent swing remains locked onto those same adds.
> adjust cleave logic based on player convos and retail vid

- Source/ACE.Server/Entity/Cloak.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Reduced Overall chance from 2.5 to 2.0, then added cloak level to proc chance equation.
Cloak Levels proc rates end up as the following
```
Level 1 - 2.1
Level 2 - 2.2
Level 3 - 2.3
Level 4 - 2.4
Level 5 - 2.5
> Added Variance for Cloak Proc Rate depending on the level of cloak.

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
Reversed the changes made by PR 2695 for no wield meleeD, and added variance to those via tier levels.    Also changed all the variances to <= and fixed some values there were being duplicated.  
All tiers have been tested through loot sim to confirm this PR
> Reversed the changes made by PR 2695 on No Wield MeleeD Bonus. 

- Database/Updates/Shard/2020-06-25-00-Update-Some-Items.sql
Per @bobigor377
Fixes errors in properties for existing items as follows:
PropertyInt.ClothingPriority - 25840 Snarl's Jerkin
PropertyFloat.SlayerDamageBonus - 35377 Replica BloodScorch
PropertyFloat.CriticalFrequency - 35377 Replica BloodScorch
PropertyFloat.ProcSpellRate - 35377 Replica BloodScorch
PropertyFloat.SlayerDamageBonus - 40652 Great BloodScorch
PropertyFloat.CriticalFrequency - 40652 Great BloodScorch
PropertyFloat.ProcSpellRate - 40652 Great BloodScorch
> Resync some item properties with world database

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Matched to retail message in pcaps via info from Trevis and Optimshi
```
You cast Heal Self I and restore 0 points of your health.
With Incantation of Heal Other you restore 150 points of health to Lothnar.
With Harm Other II you drain 10 points of health from Large Silver Rat.
Widgeon IV casts Incantation of Heal Other and restores 56 points of your health.
Void Knight casts Harm Other IV and drains 7 points of your health.
```
> updating heal/harm spell message for player caster on remote target

- Source/ACE.Server/Entity/SpellFormula.cs
Silver Scarab and Diamond Scarab spells were requiring 4 prismatic tapers to cast when they should have required 3. Corrected the logic to match the client.
> Corrected Prismatic Taper count on some Foci spells.

- Source/ACE.Server/WorldObjects/Player_Skills.cs
- Similar to always trained skills once they are Aug Speced
- XP is refunded via Skill Reset at Asheron's Castle.
- Skill Credits are not refunded.
- Fixed issue with Skill Reset adding skills that were not part of the reset
> Allow Specialized Skills via Augmentation Gem to refund xp spent

- Source/ACE.Server/WorldObjects/Player_Location.cs
This fixes some anomalies with the player restarting the recall animation after a jump, and the player appearing in falling state at the destination when this happens
There is still an open issue where the server should possibly be preventing the player from going into combat state after landing from the jump. The player is already set to IsBusy on the server during the recall animation, which prevents them from performing any actual combat actions. The client does not appear to go into busy state during the recall.
Thanks to @CrimsonMage for reporting this issue
> send recall animations as actions instead of forward commands

- Source/ACE.Server/Managers/RecipeManager.cs
According to the mutations for the Silk recipe (http://ac.yotesfan.com/loot/mutation_filters/?j=54.json), this operation should be = instead of +=
Thanks to Virindi for mentioning this
Todo: switch the RecipeManager over to using actual mutation filters
> updating silk recipe

- Source/ACE.Server/WorldObjects/PetDevice.cs
From @OptimShi and retail pcaps:
UpdateEnchantment (the cooldown)
TextboxString "Your summoning device does not have enough charges to function!"
UseDone
> updating PetDevice Structure==0 message

- Source/ACE.Server/Network/ClientPacket.cs
- Source/ACE.Server/Network/ConnectionListener.cs
Spelling fix.
Re-use the buffer in Connection Listener, and add ReleaseBuffer() method in ClientPacket to explicitly release references to the shared buffer.
This retains the optional ability to retain ClientPacket and it's underlying data for longer (server development, or 3rd party tool)
Thanks Paradox for the tip.
> Reuse buffer in ConnectionListener

- Source/ACE.Server/Network/Structure/ArmorLevel.cs
``* = Unenchantable`` is seen in the client appraisal window for creatures
in CharExamineUI::SetAppraiseInfo:
```
v43 = _prof->base_armor_head;
if ( v43 < 9999 )
AC1Legacy::PStringBase<char>::sprintf(&armorStr1, "%d", _prof->base_armor_head);
else
AC1Legacy::PStringBase<char>::sprintf(&armorStr1, "*%d", v43 - 9999);
```
sending 9999 + actual value for any body parts where all layers are unenchantable
> handle appraisal for * unenchantable body parts

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Unattackable creatures wielded items cast no spells on wielder
- CreateList wieldables take priority over WieldedTreasureDID wieldables
> Fix some issues with Creatures and EquipInventoryItems

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
From retail pcaps, when an item casts a spell on a player, the verbiage was 'cast' instead of 'casts'
> adjusting 'casts -> cast' verbiage for item spells

- Source/ACE.Server/WorldObjects/Vendor.cs
- Modify the selling process for attuned items to prevent them from being resold, which could allow other players to obtain quest items that are sellable, without having performed the quest -- Item was supposed to be attuned to the original recipient anyways; allowing attuned item "transfers" via vendor seems like an exploit.
> Modify selling attuned items to vendors

- Source/ACE.Server/Entity/Cloak.cs
Cloaks that have not reached at least level 1 no longer produce proc spell.  Also update to Proc Rates for Cloaks.  Cloaks were pulling Max Level, not current cloak level.  Also adjusted Proc Rate.  Now depends more on damage percentage.
> Update to Proc Rates for Cloaks. 

- Source/ACE.Server/Network/NetworkSession.cs
This fixes out of order NPC emotes, like this one:
https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/master/Database/Patches/2008-08-AncientPowers/9%20WeenieDefaults/Creature/Human/38388%20Kirina%20of%20the%20Celestial%20Hand.sql#L116
> Make sure UIQueue NetworkMessages are sent in order

- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
Verified the other properties in GetAugBonus() from augs and lum augs do boost the untrained / unusable skills... Enlightenment is the only outlier there
> enlightenment doesn't boost untrained / unusable skills

- Source/ACE.Server/WorldObjects/Creature_Magic.cs
Mana Conversion is listed as 'unusable' in client when not trained
Assuming unusable skills are truly unusable when not trained (aside from the magic school outliers)
Search ACE discord #general for 'mana conv' or 'Yeonan' for relevant discussion from 8/14/2020
> ensure mana conversion is trained to get any benefit from the skill

- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
`@teleloc 0x0287011C [70.305200 -35.835400 -11.995000] 0.000000 0.000000 0.000000 -1.000000`
`@smite all`
expect to see butterflies
> Fix issue with event generators 0 RegenerationInterval spawning their init when turning on

- Source/ACE.Server/Entity/DamageEvent.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
Repro steps:
- Equip an elemental bow, and prismatic arrows
- Stand within melee range of target creature
- Start charging accuracy bar (setting to max makes it easier)
- While accuracy bar is charging up, swap to a different bow
Expected:
Client does some silliness here, instead of cancelling the attack, it starts stance swapping to change bows, and then does a melee attack in the middle of the stance swap. This happened in retail too, should be a normal melee attack
Actual:
Same thing happens on client, it sends accuracy bar charge up as power bar charge up / melee attack to server, but server was interpreting this as a missile attack w/ prismatic damage, based on the player wielding a bow (even though it sends as melee attack)
The source of this bug is in the GetCombatType() function. …
> fixing 'prismatic damage' message

- Source/ACE.Server/WorldObjects/Player_Missile.cs
Repro steps:
In Player_Missile.cs, line 152, comment out the following block of code:
```
if (!TargetInRange(target))
{
// this must also be sent to actually display the transient message
SendWeenieError(WeenieError.MissileOutOfRange);
// this prevents the accuracy bar from refilling when 'repeat attacks' is enabled
OnAttackDone();
return;
}
```
/create drudgewoodtarget, and then run away, so it is on the very edge of radar range
disable the 'fast missiles' character option
launch some arrows at it, then repeatedly take a few steps backwards, repeating
eventually you should find a point where the player stops aiming way up high, and instead aims very low, and launches an arrow into the ground
there are some edge cases where the 'TargetInRange' pre-check can succeed, but then the actual …
> fix edge cases for player missile 'out of range' check succeeding, but actual velocity calc failing

- Source/ACE.Entity/LandblockId.cs
- Source/ACE.Entity/Position.cs
good loc:
0x00D10FFF [231.740707 -69.822220 -5.995000] 0.666223 0.000000 0.000000 -0.745753
bad loc:
0x00D1101E [240.058197 -69.525620 -5.995000] 0.989331 0.000000 0.000000 0.145685
> replacing MapScope concept with Indoors to fix Ancient Caves dungeon... MapScope wasn't a thing, afaik

- Source/ACE.Server/Managers/RecipeManager.cs
- original ace calculation was correct. damage variance reduction is multiplicative, not additive
- granite also has the same mutation script id as lucky rabbits foot. so granite was applying the correct calculation, and then the new bugged calculation for lucky rabbits foot
> fix granite bug introduced with lucky rabbits foot

- Source/ACE.Entity/Enum/DamageType.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
Currently in ACE, when either a weapon or a monster body part contains multiple DamageTypes, a random damage type is selected for each swing. An example of one of these weapons would be 9420 - Mattekar Claw.
In retail, the DamageType for the Mattekar Claw was tied to the PowerLevel of the swing, and worked similarly to Piercing/Slash weapons. When the power slider was set < 33%, a thrust would be performed w/ Piercing damage. Anything greater would be a Slashing attack.
For monsters, they always attack with PowerLevel = 0.5 simulated, as per retail. So to retain the existing ability for a monster body part with multiple DamageTypes, the existing RNG logic for monsters is kept the same.
For players, instead of adding a special case specifically for Slashing | Fire for the Mattekar Claw, …
> matching mattekar claw damage types up to retail

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
Currently in ACE, when a player uses /permit to grant access to another player to loot their corpse, this permission remains in effect until it automatically expires after 1 hour, the permitter removes the permission, or the permittee logs out.
In retail, after the permittee opened a locked corpse of the permitter, their permission for other locked corpses of the permitter was revoked at that point.
There are a few details with this, thank you very much to the community for having a discussion about this in Discord for figuring out the details:
- When a permittee opens/closes the locked corpse of a permitter, the corpse does not become available for anyone to access afterwards. Thus, it differs from the corpse owner opening/closing their corpse in this way. When a corpse owner …
> updating /permit logic to be closer to retail by default

- Source/ACE.Server/Factories/Entity/TreasureItemTypeChance.cs
- Source/ACE.Server/Factories/Enum/TreasureItemType.cs
- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
- Source/ACE.Server/Factories/LootTables.cs
- Source/ACE.Server/Factories/Tables/QualityChance.cs
- Source/ACE.Server/Factories/Tables/TreasureItemTypeChances.cs
This fixes an issue with Mixed Equipment Chests (DeathTreasureType 2001) such as 48743 - Legendary Chest, where they shouldn't be spawning regular gems.
This can be seen in the Mag-Loot logs from retail, ie. Container_Legendary_Chest_T8.txt. From 5,826 items in there, 255 were gems, and 100% of those gems were Aetheria. No regular gems appeared to have spawned in these chests in retail.
Aetheria is currently an 'additive' separate from gems, which can still be selected via these profiles. The MundaneItemChance for these chests is 100, but the Min/Max mundane items are 0... this has the effect in ace currently of allowing Aetheria to be spawned as an additive to mundane, even when no other mundane items can spawn.
This PR builds on the existing LootBias enum, with a structure that more …
> add treasure item type chance tables

- Source/ACE.Server/WorldObjects/AugmentationDevice.cs
AugmentationDevice.VerifyRequirements() was using AugmentationCost ?? 0, and the rest of the functions were using AugmentationCost directly
This had the effect of letting an AugmentationDevice w/ missing/bad data go through, resulting in undefined behavior afterwards, such as setting AvailableExperience to null
Adding check to AugmentationDevice.VerifyRequirements() to ensure AugmentationCost is not null
> add verification for AugmentationCost

- Source/ACE.Server/WorldObjects/ManaStone.cs
- Source/ACE.Server/WorldObjects/WorldObject_Decay.cs
- /ci 30187
- /ci manastonegreat
- double click mana stone
- click 30187 - Hunter's Crystal
Hunter's Crystal has ItemMaxMana=10000, but ItemCurMana=null
the server gets an exception, although it doesn't crash the server. the player is then locked in perma hourglass state.
the correct behavior from retail needs to be confirmed here. could mana stones give mana to items where ItemMaxMana has value, but ItemCurMana=null?
at the minimum, it shouldn't get an exception / lock player into perma hourglass state..
one thing to note about this, if this was possible in retail, then the current ace logic would then consider the rare to be in the 'potential pool' of items to give mana to afterwards, if the player double clicks a mana stone, and then clicks their character
> fix exception when giving mana to an item w/ ItemMaxMana, but not ItemCurMana

- Source/ACE.Server/Physics/Common/Landblock.cs
This fixes the 22257 - Fishing Holes getting their position bumped up ~0.35 by the server, which in turn caused them to appear floating above the water, and not animating.
Root cause in ObjCell.get_water_depth(), the LandCells were not linked up to their parent Landblocks, so calc_water_depth() was never being called. The default value of 0.1 was being returned in this case, instead of the intended 0.45 in calc_water_depth()
> fixing water depth for fishing

- Source/ACE.Server/Command/Handlers/PlayerCommands.cs
- Source/ACE.Server/Managers/QuestManager.cs
This fixes colo on servers where quest_mindelta_rate is not 1.
It allows other quest timers to be scaled, but keeps colo functioning as it did in retail.
> CanScaleQuestMinDelta

- Source/ACE.Server/Network/Structure/ContractTracker.cs
- ContractTracker.Contract now caches result from DAT
- Adjusted handling for QuestflagRepeatTime
- After repeat timer is up, recheck for other progress flags
> Adjustments to ContractTracker

- Source/ACE.Server/Entity/Cloak.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
This is still an 'invented' formula, but is in response to the player feedback about cloak proc rates being too high, esp. for the -200 proc
Here are the #s for the base proc rates for specific damage %s, and the chance of procing for a string of hits for that damage %:
Current proc rates: https://pastebin.com/P6QVFkze
New proc rates (base): https://pastebin.com/LaL6DDUS
New proc rates (level 5 cloak): https://pastebin.com/CAJgzwqX
For strings of low hits, the proc rates were fine. The issue was when the player took high damage, the cloak was procing way too often. The new formula simply adds a cap to the max proc rate. The item level increases this max proc rate
Current scale:
0
1 25%
2 26.25%
3 27.5%
4 28.75%
5 30%
Other scales considered:
0
1 25%
2 27%
3 29%
4 31%
5 33%
0
1 20%
2 22.5% …
> update cloak proc rate based on player feedback

- Source/ACE.Database/WorldDatabaseWithEntityCache.cs
The previous call would never select the last element of the list
Also updated the standard ThreadSafeRandom used in the rest of the project
> fix GetRandomWeeniesOfType rng bug

- Source/ACE.Server/WorldObjects/Creature_Rating.cs
- Source/ACE.Server/WorldObjects/PetDevice.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
For equipment ratings, such as Damage Rating on a piece of armor, ACE was previously looking at the DamageRating property on the armor, where it should have been looking at the GearDamage property, similar to PetDevices.
This can be seen in retail pcaps. previously in ACE, when appraising a piece of armor with a DamageRating, the rating was not visible in the appraisal window. It required the player equipping the armor, and seeing their character appraisal damage rating go up before.
With GearDamage, the armor appraisal window correctly shows the Damage Rating
(note that no data in ace world db, or lootgen currently assigns ratings to equipped items yet, afaik. this was purely a bug with the preliminary code added to support this feature in the future, and was only accessible by manually …
> update equipment ratings to Gear* properties

- Source/ACE.Server/Program_DbUpdates.cs
Changed version checking to be more discrete in inspecting major, minor and build for versioning. If version is higher it will update, but if lower or patch build is from a PR it will skip
> Adjust CheckForWorldDatabaseUpdate version handling

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
For spells from consuming food/drinks and activating gems, and the 'built-in' spells in the first slot of wands, the caster should be the player, and not the food/gem/casting item. The message for all of these should be 'You cast', and not 'Item cast'
Omitting the casting item in the full WorldObject_Magic pipeline, so that the player is entered into the enchantment registry, and not the item. This could prevent scenarios where multiple food items that each cast spells could be spammed, effectively protecting against dispels (similar to the Blackmoor's Favor issue)
> fixing some spell messages for item spells

- Source/ACE.Server/Physics/PhysicsObj.cs
Repro steps:
- /teleloc 0x89040339 [50.012718 -8.942079 24.004999] -0.010417 0.000000 0.000000 -0.999946
- stand at point-blank range to the closed door
- target one of the wisps behind the door
- /modifybool spell_projectile_ethereal false (default retail state, just ensuring)
- launch spell projectile
Expected:
spell projectile explodes on closed door
Actual:
spell projectile goes through this particular closed door
Note that with spell_projectile_ethereal true, the expected behavior happened already
Thanks for Ulrik for reporting this issue!
> fixing able to launch spell projectiles through some doors still

- Source/ACE.Server/Physics/Animation/MotionTable.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
also fixes a possible logic flaw for reverse animations, when first lookup isn't found
> rewrite get_link to match closer to original acclient implementation

- Source/ACE.DatLoader/FileTypes/LanguageString.cs
This is from OptimShi. I verified the string is now correct. Interestingly enough, tests still passed before with truncated strings.
All tests still pass
> Fix LanguageString

- Source/ACE.Server/Factories/Tables/ArmorCantrips.cs
- Source/ACE.Server/Factories/Tables/JewelryCantrips.cs
- Source/ACE.Server/Factories/Tables/JewelrySpells.cs
- Source/ACE.Server/Factories/Tables/MeleeCantrips.cs
- Source/ACE.Server/Factories/Tables/MeleeSpells.cs
- Source/ACE.Server/Factories/Tables/MissileCantrips.cs
- Source/ACE.Server/Factories/Tables/MissileSpells.cs
- Source/ACE.Server/Factories/Tables/QualityChance.cs
- Source/ACE.Server/Factories/Tables/ScrollSpells.cs
- Source/ACE.Server/Factories/Tables/SpellLevelChance.cs
- Source/ACE.Server/Factories/Tables/SpellLevelProgression.cs
- Source/ACE.Server/Factories/Tables/SpellSelectionTable.cs
- Source/ACE.Server/Factories/Tables/WandCantrips.cs
- Source/ACE.Server/Factories/Tables/WandSpells.cs
- According to spellSelectionGroup6, quickness buffs could be found on melee/missile weapons
- Added jump/run buffs to ArmorCantrips. These were already in ArmorSpells. (actually was already added to ArmorCantrips before, just updated comments)
In the pre-t7 retail data, jump/run buffs could only be found on certain types of armor/clothing, specifically those that only covered the feet or lower legs. We may want to consider adding a separate table for lower armor, or investigate if this was still the case @ eor
- Added SpiritDrinker to WandSpells table. SpiritThirst was already in WandCantrips table.
I can sort of see the reasoning behind why this was only in WandCantrips -- if this spell were to drop on a lower level item that didn't have elemental damage, it would be rather useless. …
> adding a few missing spells to spell tables

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
This is only for /lootgen dev command. Aetheria and PetDevices were already working fine in the regular lootgen system
The MutateItem() method used only by /lootgen dev command already had the logic for Aetheria and PetDevices, however an error was being shown beforehand, since these items do not contain PropertyInt.TsysMutationData
> adding missing piece for /lootgen dev command for aetheria and pet devices

- Source/ACE.Server/Physics/Common/ObjectMaint.cs
Repro steps:
/teleloc 0x76E90187 [128.597122 131.423340 88.805008] -0.999902 0.000000 0.000000 -0.014001
observe: a door in the path ahead is invisible
take a step forward, door suddenly pops into visibility
expected:
door should be visible from 187
For EnvCells that are SeenOutside, the server was previously only getting the outside cells, and any other envCells that are also seen outside
It should be getting all of the VisibleCells, as well as the previous filter
> adjust SeenOutside logic

- Source/ACE.Entity/Adapter/WeenieConverter.cs
This adds PropertiesBodyPart to the already established pattern for weenie collecitons that don't change.
The existing ones are:
weenie.PropertiesCreateList;
weenie.PropertiesEmote;
weenie.PropertiesEventFilter;
weenie.PropertiesGenerator;
This simply causes the Biota to reference the Weenie collection directly, instead of cloning it.
This should provide a very very small runtime memory improvement
> Add PropertiesBodyPart to the Weenie/Biota hybrid

- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
3189 changed some stuff to make the built-in spell for 41465 Casting Stein say 'You cast', instead of 'Item cast', but ended up breaking other stuff, like ItemSpellcraft
This re-implements the fix in a better way to fix both scenarios
> fixing more bugs from 3189

- Source/ACE.Server/Factories/Tables/TreasureMagicItemTypeChances_Orig.cs
- Source/ACE.Server/Factories/Tables/TreasureMundaneItemTypeChances_Orig.cs
This builds on PR https://github.com/ACEmulator/ACE/pull/3197
Similar to how 3197 mapped the treasure_death.ItemTreasureTypeSelectionChances column to chance tables, this does the same for MagicItems and MundaneItems
> adding magic/mundane item type selection profiles

- Source/ACE.Server/Entity/Spell.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
before:
Self:
You cast Superior Frore Ward on yourself
You cast Superior Frore Ward on yourself, refreshing Superior Frore Ward
Target: (no message, no enchantment, although there are visual effects on target)
---
after:
Self:
You cast Superior Frore Ward on yourself
You cast Superior Frore Ward on fellow
Target:
Fellow cast Superior Frore Ward on you
most likely only a bug with fellowship enchantments for MagicSchool.LifeMagic
> fixing fellowship spell messages

- Source/ACE.Server/Entity/Cloak.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
https://asheron.fandom.com/wiki/Master_of_Arms
Cloaks with the chance to reduce incoming damage by 200 have been reduced to 100 for PvP circumstances.
Thanks to Jkurs for reporting this issue
> adding pvp modifier for cloak damage procs, as per retail

- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
Overall, there was very little that could be improved. Caching is used properly throughout the entire object, except where improved in this PR.
HasVitae is now cached
Creature.RemoveItemSpell now involves one less lock/loop for every time a spell is found that needs to be removed
Networking AppraiseInfo sends all the active enchantments for MagicSchool.Item
The previous method cloned the entire collection and then ran this query:
- group e by e.SpellCategory
into categories
select categories.OrderByDescending(c => c.LayerId).First();
The new method uses the existing GetTopLayer without cloning the entire collection. It uses the following query:
- group e by e.SpellCategory
into categories
select categories.OrderByDescending(c => c.PowerLevel).ThenByDescending(c => …
> EnchantmentWithCaching Audit + Improvements

- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
The current feedback has been, for void pvp, dot damage is about on par with retail, but direct damage is still way too high
From the data provided from void pvp players in retail, it seemed like direct damage from void in pvp was still about double what it should be. This has me confused, because we were already applying this logic from retail dev notes:
```
// http://acpedia.org/wiki/Announcements_-_11th_Anniversary_Preview#Void_Magic_and_You.21
// Creatures under Asheron’s protection take half damage from any nether type spell.
```
The only thing I can imagine, is perhaps this logic applied *on top of* the player's natural resistance to void, instead of simply capping their natural resistance to void to 0.5
Some complications resulted from the original implementation of the …
> move void_pvp_modifier calcs for direct damage, based on feedback and data from void pvp players in retail

- Source/ACE.Server/Factories/Entity/MissileMagicDefense.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
Sampled from about 100k items from eor magloot logs
The tier divisions were found to be t1-t6, and t7-t8
These were the exact chances for each outcome
> updating WeaponMissileDefense / WeaponMagicDefense rolls to eor formula

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
Can possibly help out with https://github.com/ACEmulator/ACE/issues/3152
(on second thought, for 3152 specifically, would probably need to go through a 2-step process of untraining the skill via a SkillAlterationDevice, and re-training it. most of the xp from proficiency points automatically goes into the skill, so this xp would already be "spent" / not available in unassigned xp anymore)
> adding /delevel dev command

- Source/ACE.Server/Command/Handlers/PlayerCommands.cs
- Source/ACE.Server/Managers/PropertyManager.cs
Add `aceversion` command for players.
This can be used by players on bug reports as well as in getting assistance with debugging issues.
Command is disabled by default, but can be enabled by server operators with `version_info_enabled` property
> Add aceversion command

- Source/ACE.Database/WorldDatabaseWithEntityCache.cs
- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
- the .sql output of /addenc is now more consistent with /createinst, in that it adds the encounter to the db w/ checks, and then outputs the entire state of the encounters in the db for that landblock to the sql file. this includes the delete statement, and any pre-existing encounters that were already in the database
- a /removeenc command has been added, which works on the last appraised object
- cleaned up both /removeenc and /removeinst to properly handle removal when there is only 1 encounter / instance in the landblock remaining
> improving /addenc, adding /removeenc

- Source/ACE.Server/Entity/Landblock.cs
Landblock.SpawnEncounters is run from a separate Task.
It does a lot of position/cell work on that task and only enqueues the AddWorldObject onto the thread safe ActionQueue.
I suspect these tasks were hitting AdjustCells at the same time LandblockManager is unloading landblocks (and thus cells).
This caused thread collisions on the AdjustCells dictionary.
Wrapping all this work up into the thread safe ActionQueue should solve the issue.
> Landblock SpawnEncounters threading improvement

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
this fixes long-standing bug on server where merging from equipped ammo slot was not being handled correctly on server
repro steps:
/ci arrow 100
/ci arrow 100
equip one of the arrow stacks
double click the equipped arrows to dequip them
expected:
arrows are dequipped properly
actual:
arrows visibly disappear from equipped slot on client, but server actually returns an 'inventory saved failed', which the client might ignore / not be valid for this particular action, which the client sends as HandleActionStackableMerge.
this is because the server code was only checking for inventory item in some places, and was missing the check for equipped items
afterwards, if you try to equip the remaining stack of arrows, with the latest code you will get the error that there are already arrows …
> fix missing dequip calls from stackable merge

- Source/ACE.Entity/Models/PropertiesEnchantmentRegistryExtensions.cs
- Source/ACE.Server/Entity/AddEnchantmentResult.cs
repro steps:
/ci shirt
/ci pants
appraise shirt, /additemspell 6330
appraise pants, /additemspell 6331
equip shirt pants in different order, and notice discrepancies in the following areas: the spell the server thinks is at the top of the stack (matches client, in current master), and the spell the client thinks is at the top of the stack
this seems to be a bug on both the client and server. this patch fixes it for the server (unknown if retail server has this issue), but the visual display anomaly will still remain on the client
> fix spell stack calculation issue with set spells in multiple sets

- Source/ACE.Server/Factories/WorldObjectFactory.cs
ObjectGuid.Invalid is a valid use case for CreateWorldObject
> Fix Unhook

- Source/ACE.Server/WorldObjects/ManaStone.cs
- fixed a bug where LumAugItemManaGain was able to send an item's current mana beyond its max mana
- fixed a bug where LumAugItemManaGain was only taking effect for player targets
> fix 2 bugs with LumAugItemManaGain

- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
chickenhen has a NonCombat.Ready immediately after its Move emotes, with 0 delay in between. not sure if retail would have waited to perform the Ready until after the move was completed... ace emotes are currently setup to pre-calculate the delay to the next emote, and a variable delay / callback system is not implemented for this.
the way ExecuteMotion(Ready) is also called, it apparently stops the current Turning motion in progress, but does not call MoveToManager to stop the current MoveTo in progress. so MoveToManager was basically going into an infinite loop, detecting that no Turning progress was being made, and incrementing FailProgressCount each time, which the Move handler was not monitoring
the easiest fix for this is to just ignore Motion emotes if there is a MoveTo currently …
> fix chickenhen move emote

- Source/ACE.Server/Entity/Landblock.cs
Generators that have spawn circumferences that overlap water or cliff edges may fail to random spawn creatures.
This makes the message a debug level instead of a warn level
> Make generator spawn failures debug

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Database/ShardDatabaseOfflineTools.cs
- Source/ACE.Server/Program.cs
This patch attempts to workaround the order column for biota_properties_palette table being removed from shard database which causes corpse save failures.
It is unknown what exactly causes this table to lose this column but this workaround corrects it and retries saving
> Workaround fix for intermittent corpse save failures

- Source/ACE.Server/Entity/Spell.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Send the current attacker message to the client so that the client can
use the last attack keyboard shortcut to select the last attacker.
Note that these will be sent often when there are multiple attackers.
The message should only be sent when the attacker changes
> Send current attacker message to client.

- Source/ACE.Database/ShardDatabaseOfflineTools.cs
This particular select statement (which has an inner function call) doesn't work unless the results are pulled using a ToList first.
> Fix Allegiance Purging

- Source/ACE.Database/WorldDatabaseWithEntityCache.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
a set with 117% probability, for example, should be interpreted as 2 sets: the first set having a 100% chance of rolling one of the items in the range of 0.0-1.0, and the second set having a 17% chance of rolling an item in the > 1.0 range
this is similar to how the createlist probabilities work
previously ace was only performing 1 roll for this, between 0.0-1.17
also adds /show-wielded-treasure &lt;creature wcid&gt; developer command
> update wielded treasure roll to be closer to retail

- Source/ACE.Server/Entity/DamageEvent.cs
https://asheron.fandom.com/wiki/Announcements_-_2002/08_-_Atonement
It should be noted that any time a character is logging off, PK or not, all physical attacks against them become automatically critical.
(Note that spells do not share this behavior.) We hope this will stress the need to log off in a safe place.
> add 100% physical crit rate chance against players while they are performing logout motion

- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
http://acpedia.org/wiki/Announcements_-_2002/11_-_The_Iron_Coast#Release_Notes
"The chance for causing a critical hit with magic, both with and without a Critical Strike wand, has been increased."
Thanks to Xenocide for tracking down some solid dev notes for this!
Also updated the critical protection augmentation feedback messages for magic to match retail pcaps. It differed slightly from the messages for physical.
> update base magic crit rate for 11-2002 iron coast release notes

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
According to PCAPs vendors didn't seem to be making use of the Shop generator system to gate/limit amount of purchases or create stock scarcity.
This fixes shop spam for these items from 16py data
> Update Vendor generator sys to match EoR usage

- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/WorldObjects/Player.cs
Instead of enqueueing the work onto the player, we now enqueue it onto the WorldManager ActionQueue.
When players were getting stuck, the players were becoming detached from the landblock before the logout animation finished. I don't know why.
> Improve PK LogOut to help prevent stuck characters

- Source/ACE.Server/WorldObjects/ProjectileCollisionHelper.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
This helps reduce thread safety issues for the following scenario:
// sourceCreature and creatureTarget are now in different landblock groups.
// What has likely happened is that sourceCreature sent a projectile toward creatureTarget. Before impact, sourceCreature was teleported away.
// To perform this fully thread safe, we would enqueue the work onto worldManager.
// WorldManager.EnqueueAction(new ActionEventDelegate(() => sourceCreature.TryProcEquippedItems(targetCreature, false)));
// But, to keep it simple, we will just ignore it and not bother with TryProcEquippedItems for this particular impact.
> Ignore TryProcEquippedItems for Collisions when source/target are on separate landblock groups

- Source/ACE.Server/Network/Managers/NetworkManager.cs
This can happen when clients are connected to a server.
Those clients remain untouched.
Server crashes and restarts.
NEW clients connect.
The original clients are still open and trying to talk to the server, resulting in this message.
> Endpoint Mismatch should be debug, not warn

- Source/ACE.Server/WorldObjects/Player_Melee.cs
repro steps:
- this needs to be performed on a remote server with some amount of latency. clumsy can also be used w/ 50ms lag on local server
- start charging up a full power melee attack
- press the 'z' key as soon as the power bar starts charging
expected:
- powerbar continues to charge, player starts sidestepping
actual:
- powerbar resets and stops charging, player starts sidestepping
> fixing power/accuracy bar unintentionally resetting on remote servers

- Source/ACE.Entity/Enum/Properties/PropertyFloat.cs
- Source/ACE.Server/Entity/Tailoring.cs
note that only the [Ephemeral] fix is required for the issue.
the physics/sound table are just added for consistency.
it should still be investigated why EphemeralProperty=null retains the original value at runtime, when the EphemeralProperty originates from the base weenie
it should also be evaluated whether or not the tailoring intermediate items should have Translucency=0.5 on them
> fix semi-translucent items after tailoring until relog

- Source/ACE.Server/WorldObjects/Monster_Magic.cs
Scenario:
Monster targets player
Monster begins to cast a spell at player (windup)
Player teleports out
Monster windup completes and casts
TryResit code now accesses two threads at once determining if the spell can be landed on the player that's now gone.
> Fix multi-thread issue when monsters cast against players that left

- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
/ci 45967
current master, the bane spell does not show up in the items enchantments list in the appraise window
> Fix Appraise for equipment with banes

- Source/ACE.Server/Managers/ServerManager.cs
Logging off all players and disconnecting sessions will now be enqueued by the shutdown process, but the action performed by world manager, fixing some cross-threading issues previously seen.
> Fix Shutdown Thread Safety

- Source/ACE.Server/Network/NetworkSession.cs
Most uses of this function are a single message.
This removes the overhead of GroupBy() and ToList() for every call at the expense of retaking the lock in cases where multiple messages of the same group are sent.
> Improve EnqueueSend

- Source/ACE.Database/Adapter/BiotaUpdater.cs
In previous master, the full targetBiota spellbook was being iterated for each sourceBiota spell.
This was very time consuming with players with large spell books (100+ ms)
Now, a dictionary is made and that is used to perform the nested lookup.
New result is 0 ms.
> Improve UpdateDatabaseBiota()

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
This adds a IsDormant check on top of EmoteType.Motion, which already checked for PlayersInRange(). This should not change the result, but instead simply provide a more efficient way to filter this emote. IsDormant is less CPU then calling PlayersInRange, and there should never be PlayersInRange when IsDormant.
EmoteType.Move adds an IsDormant check.
These changes bring current master + 219 content to equal if not better performance than current master + 216 content.
> Filter Emotes when IsDormant

- Source/ACE.Server/WorldObjects/Player_Spells.cs
this fixes 1 instance of a bug that can still happen in AuditItemSpells
repro steps:
- equip item 1 from a spell set
- equip item 2 from same spell set, so that it boosts the spells
- dequip item 2 by *dropping it on the ground*, so it is no longer in player's possession
- relog
expected:
nothing
actual:
AuditItemSpells detects error, and silently removes the spells from the set
in the above scenario, when dequipping item 2, it removes the higher level spells, and re-adds the lower level spells. however, the lower level spells were being added with CasterGuid=item2 (the dequipped item), which can cause some confusion and inconsistencies with bookkeeping and AuditItemSpells
AuditItemSpells was previously upgraded to detect this scenario, however it relied on the item still being in the …
> improve CasterGuid bookkeeping for dequipping items w/ spell sets

- Source/ACE.Server/Network/GameAction/Actions/GameActionMoveToState.cs
(just pasting chat log for reference)
ok i found another bug
the server is dropping movement commands when you are in portal space
so if you press 'run forward' to run in a portal, and then release 'run forward' while you are in portal space, the server is not processing the 'release run forward' command correctly in portal space
i have a fix for current master for that, seems to prevent the oddities from happening in portal space
so that, coupled with the 'you have teleported too recently!', should fix any bugs and oddities for that from multiple angles
the physics engine also seems to handle different animations differently, like run forward, strafe, and run forward + strafe all display different stop motion properties in the physics engine, its weird
but out of everything i tried, it …
> improved move to state handling during pk teleport

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/Tables/GemMaterialChance.cs
- Source/ACE.Server/Factories/Tables/Wcids/AetheriaWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/ArmorWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/CloakWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/ClothingWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/GenericWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/JewelryWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/PetDeviceWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/ScrollWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/SocietyArmorWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/AtlatlWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/BowWcids_Aluvian.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/BowWcids_Gharundim.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/BowWcids_Sho.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/CasterWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/CrossbowWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/FinesseWeaponWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/HeavyWeaponWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/LightWeaponWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/TwoHandedWeaponWcids.cs
This update only affects the /lootgen admin/developer command, and nothing else
This updates the /lootgen command to fully use the updated loot system. The TreasureRoll structure that is normally populated during the wcid roll is now derived and passed to mutation. TreasureRoll not being null enables all of the latest lootgen logic (mutation scripts, rolling for spells/cantrips, and some other missing pieces)
> update /lootgen command for latest loot system

- Source/ACE.Server/WorldObjects/Healer.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
This fixes using keys in locked doors and chests remotely. The player now correctly performs a MoveTo/TurnTo the remote object, if necessary
> add MoveTo/TurnTo logic if needed to base Player_Use.HandleActionUseWithTarget

- Source/ACE.Server/Entity/MoveToParams.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Move2.cs
- Source/ACE.Server/WorldObjects/Player_Tick.cs
In retail, when a player double clicked an object in the world from far away, or when they tried to use an object in their inventory on another object in the world from far away, the server would have the player automatically MoveTo the remote object. If the player then manually pressed their movement keys while this automatic MoveTo was taking place, their client would automatically say 'Action Cancelled!', and their client would cancel the automatic MoveTo on its own.
However, the client wasn't really cancelling the action they were trying to perform at the end of the MoveTo -- they were only cancelling the MoveTo itself.
In this scenario, when the player released the manually pressed movement keys, the retail server would then attempt to perform the action from their current location. …
> improving MoveToManager for pk

- Source/ACE.Server/Physics/Animation/MotionTable.cs
This fixes some issues with certain animations being skipped on the server, and possibly other anomalies when building animation sequences
Re-confirmed with client code
> fix animation get_link, again

- Source/ACE.Database/ShardDatabase.cs
This query is described as being "very fast", but it takes over 60 seconds to run on my local computer for CE's database. Not sure if that is expected or not, but this extends the default timeout so the server doesn't crash on startup.
> extend timeout for GetSequenceGaps

- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
This updates monster max chase range to the originally intended value.
I can't believe this was set to 192 since inception... I am certain this was originally set to 96 during development, and an incorrect value must have gotten checked in. I don't want to think about all of the wasted CPU cycles from monsters chasing players a full landblock across the landscape from this...
Note that this is different from the default HomeRadius, which is still set to 192 by default, unless overridden by the mob. A mob will travel up to HomeRadius from its home to reach a target, before returning home. It will also return home if the target is more than than MaxChaseDist away.
For reference, approximate maximum distance a ranged player can launch a projectile is about 75 meters away.
> update max chase range to intended value

- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Database/WorldDatabaseWithEntityCache.cs
- Source/ACE.Server/Program.cs
This is significantly faster than what is currently in master, and just slightly slower than PR #3582
It is now a single threaded operation, just like #3582 but instead of stitching the objects together manually, it lets EF stitch the objects together.
EF Tracking is required for the stitching to work.
This is the recommended pattern for these types of actions when dealing with EF.
I think similar improvements can be made to startup player caching
> Improve World DB Startup Caching

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/Cloak.cs
- Source/ACE.Server/Entity/DamageEvent.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/ProjectileCollisionHelper.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Tick.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This PR starts with WorldObject_Weapon, for the following functions:
```
GetWeaponCriticalChance
* GetWeaponMagicCritFrequency
* GetWeaponCritDamageMod
* GetCasterElementalDamageModifier
GetMissileElementalDamageBonus
* GetWeaponCreatureSlayerModifier
* GetWeaponResistanceModifier
```
Previously, all of these functions were using GetCurrentWeapon(). These functions now accept a WorldObject weapon parameter.
A simple scenario to repro this issue would be to launch a spell projectile at something from far away, with a wand that doesn't have a Slayer property on it. Then switch to a wand that does have the appropriate Slayer property on it, while the spell projectile is in-flight. When the spell projectile that was launched with the non-Slayer wand hits the target, it will incorrectly have …
> improve spell projectiles to use weapon that launched the projectile for calculations, instead of current weapon

- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
This fixes various state issues with toggling house_15day_account and HousePurchaseTimestamp.
Although undocumented, house_15day_account was a bit different from other server config options. The state of this server config option was basically persisted to new characters on first login, and changing this server option afterwards basically had no effect for existing characters.
A common scenario for this: a server admin sets up a new server, and then later realizes they wish to disable the "accounts must be older than 15 days to purchase a house" restriction. So they set house_15day_account to false, and they are later surprised that existing characters on the server *still* cannot purchase a new house, only this time they are receiving the 30-day repurchase timer error, instead of the …
> fix issues with disabling house_15day_account for existing chars

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
The current mobs in the db that have ProcSpells directly on them:
31013,Wicked Skeleton,Blade Vulnerability Other VI
31014,Naughty Skeleton,Blade Vulnerability Other VI
31279,Bone Scourge,Blade Vulnerability Other VI
87173,Naughty Skeleton,Blade Vulnerability Other VI
87175,Wicked Skeleton,Blade Vulnerability Other VI
It was also found that Caster items having ProcSpells is not a thing in the current db, and it's unknown if it was ever a thing in retail.
Even when caster target procs are working 100% in theory, they still display some oddities. Since it's possible this was never even a concept in eor, procs from caster items are being disabled until if/when they are discovered to have been a thing.
> adding support for ProcSpell directly on mobs

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/ProjectileCollisionHelper.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Combat.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
For https://github.com/ACEmulator/ACE/pull/3589, it completely slipped my mind that even though no Caster items contain proc spells directly, procing on magic attacks is still definitely needed for Aetheria.
This re-enables procing for magic casting and spell projectiles, and finishes the complete pipeline in the proper way. When a spell is proced, a new bool 'fromProc' is passed around to the appropriate functions. This ensures when spell procs land, they don't make any attempt to re-proc. This avoids the multi-proc issues and chain proc bugs.
The procing code was also cleaned up a bit for missile projectiles, to further reflect how those should 'truly' work, for both phials, and missile launchers (ie. bows) with procs on them
The LandblockGroup thread safety code was updated to ensure …
> partial revert of 3589, full pipeline for proc spell handling

- Database/Updates/Shard/2021-06-17-00-Fix-Rynthid-Tentacle-Bow-WeenieType.sql
this updates weenieType from generic to missile launcher for rynthid tentacle bows generated in the first month before march 25th
> retroactively fix weenieType on rynthid tentacle bow

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
This PR extends the existing allow_summoning_killtask_multicredit bug (which defaults to true, as per retail) to fellowships, which is also per retail
What this PR does not do is allow fellowships to exploit this bug to any extreme, by default. It is theorized that in retail, it would have been possible for each person in a fellowship to possibly get *46 kill credits* from a single mob, if they knew how to exploit this issue to its maximum theoretical potential.
This PR adds a new server option, summoning_killtask_multicredit_cap, which defaults to 2. This new server option technically makes the old allow_summoning_killtask_multicredit server option obsolete, however the old server option is still supported for compatibility with existing servers who may have already decided to fix this …
> extend summoning killtask multicredit bug to fellowships, capped with new server option

- Database/Updates/Shard/2021-07-14-00-Fix-Defense-Imbues.sql
- Source/ACE.Server/Entity/Mutations/MutationCache.cs
MutationCache parser was picking up the wrong Enum type for defense skill names shared amongst Skill and ImbuedEffectType
> fix defense imbues

- Source/ACE.Server/Factories/LootGenerationFactory_Rare.cs
- Source/ACE.Server/Managers/PropertyManager.cs
Adjust the chance of a rare to spawn as a percentage. 
Default is 0.04, or 1 in 2,500. 
Max is 100, or every eligible drop (100%!)
> Added Double server property 'rare_drop_rate_percent'

- Source/ACE.Common/DerethDateTime.cs
- Source/ACE.Server/Entity/Timers.cs
This change switches PortalYearTicks from UtcNowToLoreTime to a new time called UtcNowToEMUTime.
This switch results in time always rolling forward, as well as syncing all emulated servers up to the same source. The in-game calendar, day-night cycles and weather patterns would be identical across all worlds going forward. Previously there was varied results depending on when the server started up as the "seed" changed at that time. 
As a side benefit to this change, the Journal section of the client (Quill, Journal pages with timers) will now track correctly should anyone wish to use that feature, which previously was unreliable since server time would roll backwards upon restart.
> Add and switch to EMU time for Game World

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- SplitTo3D was using ancient and bug-prone drop method. Updated to use common drop method
- SplitTo3D was destroying items on error. Updated to gracefully handle error scenarios
- Common drop method now slides items from player location to destination location behind the scenes. This retains the existing behavior in ACE to prevent items from being dropped on the other side of a wall, while also improving the previous scenarios which would have resulted in drop fails (dropping into a wall, dropping into a hillside) and now result in successful drops closer to the player location.
> drop item bug fixes and improvements

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This follows the pattern that players and landblocks use to save groups items.
> Deep save in parallel

- Source/ACE.Common/ACE.Common.csproj
- Source/ACE.Common/DerethDateTime.cs
See [here](https://devblogs.microsoft.com/dotnet/cross-platform-time-zones-with-net-core/) for issue explanation 
Adding and using [this](https://github.com/mattjohnsonpint/TimeZoneConverter) nuget package to resolve until .NET6
> .NET 6 will have built-in support for IANA and Windows time zones in a cross-platform manner, removing the need for the TimeZoneConverter library. If you are planning to use .NET 6 (or higher), you don't need to use the TimeZoneConverter library!
> Fix issue with TimeZones on platforms other than Windows

- Database/Updates/Shard/2021-07-21-00-Fix-Summon-Pets.sql
Fixes an issue where some older WeenieType.PetDevice (e.g. summoning essences) may be spawning pets of the wrong damage type.
> Reset PetDevices

- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
Aura of the Craftsman does not get applied in Base or Current skill universally, but instead appears to be applied only when in RecipeManager, or in other words, only at the time the player is using one object on another, and that recipe has a difficulty.
> Aura of the Craftsman applies to all RecipeManager interactions that have difficulty

- Source/ACE.Server/WorldObjects/Player_House.cs
They do not create a wait time nor extend it if one is already set
> Exclude Apartments from setting HousePurchaseTimestamp

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Managers/ServerManager.cs
- Source/ACE.Server/Network/Enum/SessionTerminationReason.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
Update forcelogoff command to work with any state the character may be in if requested. Previously the command was working for characters that were operating correctly, but does not help to un-limbo a character.
This should also resolve stuck in limbo for shutting down, while also not directly resolving the root cause for limbo at this time.
> Update forcelogoff command

- Source/ACE.Server/Entity/Fellowship.cs
- Source/ACE.Server/WorldObjects/Managers/ConfirmationManager.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
Confirmations had 30 second timeouts in retail.
Retail also seemingly could queue multiple confirmations up at the same time, however the client would only display the first one received. The others it would appear timed out. Since ACE doesn't really need to emulate stacking, instead we'll send feedback to initiator if confirmation would have been stacked. Self contained confirmations (Using an Gem, or similar from player inventory) likely do not need feedback on stacking, so continuing to ignore those duplicates for now.
Example would be two different characters (Player A and Player B) attempting to recruit a third character (Player C) into a fellowship. Player A's confirmation request is sent. Player B would get a Player C is busy message.
This also resolves issues with InqYesNo emotes, …
> Add automatic timeout to Confirmations

- Source/ACE.Server/Network/GameEvent/Events/GameEventHouseStatus.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
If a character/account has a house, the HousePurchaseTimestamp is synced across all characters so that they all have the same timeout restrictions
> Keep HousePurchaseTimestamp synced for roommates

- Source/ACE.Common/OfflineConfiguration.cs
- Source/ACE.Database/ShardDatabaseOfflineTools.cs
- Source/ACE.Server/Config.js.docker
- Source/ACE.Server/Config.js.example
- Source/ACE.Server/Program.cs
Adding some basic functions to prune some records at server startup.
This would prune friend lists of deleted friends (which are stuck in list, show up blank) and shortcuts to deleted objects which probably does not have any noticeable impact.
> Add some basic pruning for shard database

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Emotes were not using the proper value to compare the shade to see if it should set it or not resulting in items being the wrong color.
> Fix issue where Shade was not being properly set on items given from emote

- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
- Source/ACE.Server/Factories/PlayerFactory.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
Fix some issues with the verify command in addition to accurately using the DAT file and storing total on character as well
> Adjust verify-skill-credits

- Source/ACE.Server/Managers/PropertyManager.cs
The code that is present in the `MoveToManager.cs` is aligned with code in the original ac client, and the comparison thresholds used to determine rotation of movement in https://github.com/ACEmulator/ACE/blob/master/Source/ACE.Server/Physics/Managers/MoveToManager.cs#L433 suggest that the threshold is 20. This updates the default max angle to be aligned with the value in this file.
> Update spellcast_max_angle to align with MoveToManager

- Source/ACE.Server/Managers/AllegianceManager.cs
This follows the same thread-safety pattern used in other parts of AllegianceManager, like HandlePlayerDelete.
The intent here is that AllegianceManager should mange its own thread safety. Callers shouldn't have to worry about if an AllegianceManager action should be thread safe or not.
> Add Thread Safety to AllegianceManager PassXP

- Source/ACE.Server/WorldObjects/Entity/CreatureAttribute.cs
only happens when a monster has a base attribute < 10
> fix edge case for drudgewoodtarget showing green attributes

- Source/ACE.Server/WorldObjects/Portal.cs
This appears to have been a default, similar to Doors, Chests.
> Add default ActivationResponse to Portals

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
- Source/ACE.Server/Entity/PositionExtensions.cs
- Source/ACE.Server/Physics/Common/BuildingObj.cs
Allows the conversion of VI Coord database objects to AC/ACE compatible LOCs for content recreation.
Requires [vlocDB.txt](https://github.com/ACEmulator/ACE/files/7574049/vlocDB.txt) to be placed in Content folder under vlocs directory for use.
Examples:
> `/vloc2loc 0xCE95`
> `/vloc2loc 0x0007`
> `/vloc2loc 0x00AF`
> `/vloc2loc 0xF92F`
> Wire up vloc2loc command

- Source/ACE.Database/WorldDatabaseWithEntityCache.cs
We use a case incensitive collation, utf8_general_ci, so we do not need to specify StringComparison when querying the database.
Previously, this LINQ expression was done client side in the older EF versions.
> Fix IsCreatureNameInWorldDatabase

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
It appears that the `item.` reference was removed, so when the magic absorption calculation for a hit is being determined, it is fetching this property from the inbound projectile that is having the `AbsorbMagic` method invoked.
The code in a previous version of ACE where this was working checked against `item.MagicAbsorbDamage` and that works with the Fetish and Tomes.
> Fix magic absorption for Tomes/Fetish

- Source/ACE.Server/Factories/LootGenerationFactory.cs
repro steps:
- in "ciloot" developer command, add ``, TreasureItemType_Orig.Caster`` param to CreateRandomLootObjects_New call for testing
- /ciloot 8 3
expected:
3 casters are generated, same as loot system
actual:
3 unmutated casters are generated
cause:
when TreasureItemType.Caster is specified directly (which only EmoteType.CreateTreasure can do), a slightly different path is taken from regular lootgen. In regular lootgen, only TreasureItemType.Weapon can be rolled for initially, which then rolls for a WeaponType, which can end up as caster
if TreasureItemType.Caster is specified directly, that branch needs to manually specify TreasureWeaponType.Caster, and a missing branch for it needed to be added in mutation
Thanks to Ftuoil Xelrash for reporting this issue!
Also thanks to Ripley …
> fix EmoteType.CreateTreasure mutation when TreasureItemType.Caster is specified directly

- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
- Source/ACE.Server/Managers/ServerPerformanceMonitor.cs
- Source/ACE.Server/Network/Managers/NetworkManager.cs
cumulative monitoring can potentially add a bit of server overhead
/serverperformance stop cumulative
/serverperformance start cumulative
ProcessPacket monitoring now also commented out.
> ServerPerformance allow toggle cumulative

- Source/ACE.Server/Entity/GeneratorProfile.cs
- Source/ACE.Server/Entity/TreasureWieldedSet.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
Wielded Treasure table 178 (ex. wcid 8105 for Shadow Cyst) should have a ~19.7% chance of not wielding any items
TreasureWieldedSet was previously producing some unexpected results. This class made more sense for the original way ACE was handling > 100% overages, however it makes less sense now. There are some inter-dependencies between the 3 bools (SetStart/HasSubSet/ContinuesPreviousSet) that should be independent.
GenerateWieldedTreasureSets() is now 1 simple function that better aligns with the current requirements of the system. It should be a bit more performant and produce less memory churn as well.
> refactor wielded treasure, fixing some bugs

- Source/ACE.Server/Factories/LootGenerationFactory.cs
Previously, color code 0 was hardcoded w/ equal chances
This adds support for data-driven color code 0 in https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1244
This code update has support for both the old and new versions of the data, and will select the appropriate method based on which version of the database is installed.
Once all servers have updated to the latest database, the old method can be removed
> add support for data-driven color code 0

- Source/ACE.Server/Factories/LootGenerationFactory.cs
Fixes a small bug with /lootgen dev command only, for specific pieces of armor
todo: look into deprecating GetSpellSelectionCode_Dynamic and using the actual SpellCodes from PropertyInt.TSysMutationData. I believe I verified / updated all of the TSysMutationData spell codes at some point a long time ago, although I haven't tested it recently for newer items
todo: if BaseArmorLevel concept is still needed, look into just getting it from base Weenie when it's needed, instead of caching the value beforehand
> fix /lootgen dev command spell selection for head and foot armor

- Source/ACE.Entity/Enum/Skill.cs
Repro steps:
- /dispel
- open skill panel
- appraise self
- /castspell 5942
- observe red skills determined by client
- compare values with /showstats
- repeat with 5944
According to the client, Recklessness/DF/sneak are not considered attack skills that get affected by the DF high enchantments
Also according to the client, Shield is considered a defense skill that gets affected by the DF low enchantments
Thanks to Curryfury for reporting this issue!
> sync dirty fighting attack/defense skills to client

- Source/ACE.Server/Entity/PositionExtensions.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
reviewed all current calls to Position.ToGlobal(), and it looks like the skipIndoors = true default parameter is outdated for current usage. the bugs that parameter was originally intended to fix are no longer applicable to current calls. the 'indoorsMatch' concept when comparing 2 positions also doesn't apply to places they are used, and introduces additional bugs
> fix monster homesick radius when they start indoors and end up transitioning to outdoor chase

- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
Because of the way ACE handles default base values in recipe system (or rather the lack thereof)
we need to check the following weapon properties to see if they're below expected minimum and adjust accordingly
weapons with ImbueStackingBits 1 or 4
WeaponDefense
WeaponMagicDefense
WeaponMissileDefense
This doesn't resolve the data inconsistency, but runtime fixes the massive debuff a weapon gets when the following recipes modify a weapon that has no set value for the above properties.
[Magic Defense Weapon Augmentation](http://acpedia.org/wiki/Magic_Defense_Weapon_Augmentation)
[Missile Defense Weapon Augmentation](http://acpedia.org/wiki/Missile_Defense_Weapon_Augmentation)
[Gauntlet Defense Amplification](http://acpedia.org/wiki/Gauntlet_Defense_Amplification)
If something better can be …
> Address issue with some ImbueStackingBits recipe results

- Source/ACE.Common/OfflineConfiguration.cs
- Source/ACE.Server/Config.js.example
- Source/ACE.Server/Program.cs
- Source/ACE.Server/Program_BinUpdates.cs
- Source/ACE.Server/Program_DbUpdates.cs
- Source/ACE.Server/Program_Setup.cs
- Source/ACE.Server/ServerBuildInfo_Static.cs
New Config option `Offline.AutoServerUpdateCheck` configures if the server is to check at startup for a newer server binary version.
Changed AutoUpdateWorldDatabase functionality to only check the latest release. This was all it was doing anyways, but this just makes it more efficient.
> Added optional check for newer server binary.

- Source/ACE.Server/Managers/RecipeManager.cs
Removing the % sign and replacing with the word "percent".  This was retail, and affects plugins that were from retail.  Confirmed this fixes those issues
> Change crafting message to retail.

- Source/ACE.Server/Managers/AllegianceManager.cs
changes line 305 from patron.AllegianceXPCached += passupAmount; to patron.AllegianceXPCached = Math.Min(patron.AllegianceXPCached + passupAmount, uint.MaxValue); for retail alignment per https://discord.com/channels/261242462972936192/261242462972936192/965650285328486492
> changed line 305 for retail alignment

- Source/ACE.Server/Physics/PhysicsObj.cs
Reverts ACEmulator/ACE#3797
This needs more investigation. In concept, things with gravity should fall to ground if spawned above it, and this works for some setups, but not all, such as [Black Coral](https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/master/Database/Patches/9%20WeenieDefaults/Stackable/Misc/38613%20Black%20Coral.sql)
I'm sure what to key on specifically here vs something like say [Apple](https://github.com/ACEmulator/ACE-World-16PY/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Food/Food/00258%20Apple.sql)
however, the end goal would be to allow both objects to spawn any Z height, as specified by generator/instance data, and if above ground level, fall to ground so that the object would not remain floating in the air, and can be interacted with.
> Revert "Allow Scatter generators to use their Z instead of ground Z"

- Source/ACE.Entity/Enum/Properties/PropertyDataId.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
Based on property name found in older data (thanks to @OptimShi)
This property was only found 5 weenies, entirely contained in Focusing Stone quest.
Assuming that the value might have possibly allowed for either Death or Wielded treasure, but technically it might have only been the former, so for now, coded for checking both types.
Although the property's name seemingly was removed, either it's value was still used in code OR its value was moved into DeathTreasureType/CreateList because PCAPs for these 5 objects do show similar, if not exact, results on corpses.
[Lich Overseer](https://github.com/ACEmulator/ACE-PCAP-Dynamics-Exports/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Creature/Undead/04124%20Lich%20Overseer.sql)
[Cursed …
> Wire up InventoryTreasureType support

- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Container.cs
Reset now destroys all "unmanaged" inventory in addition to its managed inventory
> Update Containers/Chests to clear/destroy unmanaged inventory on reset

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPortalStorm.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPortalStormBrewing.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPortalStormImminent.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPortalStormSubsided.cs
Added a simple Developer Command to test a portal storm on yourself:
`portalstorm (storm_level [0=Brewing, 1=Imminent, 2=Stormed, 3=Subsided])`
`portalstorm 0` would cause the "This area is getting too crowded - a Portal Storm is brewing." message to display
`portalstorm 1` would cause the "A Portal Storm is imminent - leave this crowded area!" message to display
`portalstorm 2` will cause you to be portal stormed. For the purposes of testing, this location is hard-coded to 0N, 0E
`portalstorm 3` would cause the "The Portal Storm has subsided" message to display
> Wired up PortalStorm Events for potential future use

- Source/ACE.Common/ACE.Common.csproj
- Source/ACE.Common/DerethDateTime.cs
due to cross platform issues with native dotnet6 implementation
> Restore TimeZoneConverter

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
Technically field is supposed to be Amount64, currently all our emotes use HeroXP64 so using similar coalesced expression as other transposed fields
> Adjust Award/Spend Luminance Emotes to use correct field per PDB

- Source/ACE.Server/Program_DbUpdates.cs
Adds fallback using path of executing assembly to help determine the updates directory path and patch apply record file path when the current directory is set to an unexpected directory path.  This alleviates issue #3885
> Alternative determination of patch directory path and patch apply record file path.

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
This is a relatively simple server modification to fix a bug in acclient / odd network protocol. It does some very non-standard things with ObjectDescriptionFlags.Openable for Chests though.
Repro steps:
- Find any locked chest, ie. /teleloc 0xC6A90024 [104.717110 89.921745 42.005001] -0.839618 0.000000 0.000000 -0.543177
- Open network lag simulator https://jagt.github.io/clumsy/, and simulate 500ms of UDP lag
- Appraise chest, confirm it takes ~1s for appraisal window to come up
- Type /crack, press enter, and then immediately press R to open chest (before unlock sound plays)
Expected:
Chest opens, and chest inventory window is displayed
Actual:
Chest opens, but no chest inventory window is displayed. Effectively wastes a key for the player
acclient:
ClientUISystem::OnViewContents:
``` …
```
> adding non-standard server option 'fix_chest_missing_inventory_window' to fix chest bug

- Source/ACE.Server/WorldObjects/WorldObject_Combat.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
this fixes phials being able to cast imperil/vuln on NonProjectileMagicImmune mobs
thanks to Boskangeroe for reporting this issue
> adding NonProjectileMagicImmune check to target procs

- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
Adds support for the AuralAwarenessRange float to determine ally support range of an aggroed monster. If the value is not set, it will default to VisualAwarenessRange.
> Add support for AuralAwarenessRange

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
Allows importing of Weenie SQL within sub-folders in the content folder (this goes with the `export-sql-folders` command which exports to the `weenietype\itemtype` folder)
Syntax: `import-sql-folders <wcid>`, e.g. `import-sql-folders 12345` or `import-sql-folders all`
> Added import-sql-folders command

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/WorldObjects/WorldObject_Database.cs
This resolves the race condition described as follows:
Session 0 logins in, enters world.
Session 0 closes client with X.
Person reconnects asap.
Session 1 pulls a new, full character list from the DB. Session 0, Character does final logoff (Y logoff animation completes) and does final save Character in database is updated
Session 1 Character record is now not up to date with what exists in the DB.
This PR re-uses Character references when they exist, and thus, solving the race condition, because the character that gets updated during the Y logoff animation is the same reference that the relogged client is also holding onto (at the character selection screen).
The Character cannot be relogged (already existing) until the prev instance is fully out of world, thus, there is no worry of …
> Use existing Character Ref OnLogin, if exists

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
Syntax is:
`export-sql spell <spellId>` or `import-sql spell <spellId>`
> Added `spell` to import/export sql functions

- Source/ACE.Server/Command/Handlers/DeveloperContentCommands.cs
- Source/ACE.Server/Entity/CastSpellParams.cs
- Source/ACE.Server/Entity/MagicState.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- https://github.com/ACEmulator/ACE/pull/3924 introduced a bug where built-in spells are now using the init + ranks of the caster, instead of the ItemSpellcraft
- cleaned up 3924 to not introduce baseMagicSkill additional parameter
- added missing call to WorldObject.ClearSpellCache() for https://github.com/ACEmulator/ACE/pull/3925
- renamed parameter 'caster' to 'casterItem' for https://github.com/ACEmulator/ACE/pull/3835 to maintain existing consistency. although not the best names, the codebase had previously established these 2 names to mean different things. Specifically, 'casterItem' is always associated with casting the built-in spell in the first slot
> fixes for previous checkins

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Managers/RecipeManager.cs
A recent change https://github.com/ACEmulator/ACE/pull/3922 made it so players may no longer craft arrows while in combat mode.  Since most players don't seem to like this change, this PR adds a Server Property to control the behavior.  The default is to disallow combat mode crafting.  However, with this setting, server operators may choose to enable in combat mode crafting (generally arrows).
> Allow certain crafting to occur in combat based on server property

- Source/ACE.Server/Network/ConnectionListener.cs
There is no guarantee that OnDataReceive will be called asynchronously.
Every time it is called asynchronously, the stack is reset as it's called via a new task.
If it's called synchronously enough times consecutively, the stack will overflow. Ensuring that it's called on a new task in these scenarios will prevent stack overflows.
> Fix StackOverflow on consecutive syncrhonous OnDataReceive calls

- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Creature_Rating.cs
Required for 53441- Luminous Amber: Shield Fortification, which adds 5 to a shield's GearCritResist
Thanks to Xenocide for finding and reporting this issue
> add support for GearCritResist to equippable items

- Source/ACE.Server/WorldObjects/PressurePlate.cs
- Source/ACE.Server/WorldObjects/Switch.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
For PressurePlates and Switches, when on cooldown send player ActivationFailure text if object has property.
For Vendors, reset to Home position when left "idle" for a default of 300 seconds or whatever ResetInterval is defined to.
As far as I can tell, standard Creatures (NPCs) do not have any ResetInterval type logic seen in videos, while some use MoveHome emotes to effectively do the same thing.
> Wire up ResetInterval logic into some objects

- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/Network/Structure/HouseAccess.cs
- Source/ACE.Server/Network/Structure/RestrictionDB.cs
- Source/ACE.Server/WorldObjects/Managers/SquelchManager.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
looking up players by name or account id currently has O(n) performance characteristics, where n is the total # of online+offline characters on the server. for larger servers, this is starting to have scalability issues. this PR brings it down to O(1) by adding and maintaining 2 new dictionaries in PlayerManager -- 1 for player names, and another for account ids.
some areas that call these functions: friends list, house storage/permissions, corpse looting permissions, squelches, gags, allegiance management
> improve performance for looking up players by name or account id

- Source/ACE.Common/MySqlConfiguration.cs
- Source/ACE.Database/Models/Auth/AuthDbContext.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/Models/World/WorldDbContext.cs
- Source/ACE.Server/Program_DbUpdates.cs
- Source/ACE.Server/Program_Setup.cs
Refactored to a non-user configurable string reference, shared across all connection paths
Added AllowUserVariables=True to fix bug introduced as a result of switching to MySqlConnector
Thanks to @Fire-Chimp for reporting the bug with importing on startup
> Adjust connection options for SQL servers

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
repro steps:
- place a debug breakpoint on CalculateDotEnchantment_StatModValue -> GetCasterElementalDamageModifier()
- cast corruption or corrosion with a void wand, and observe that weapon is correctly passed in, and elementalDamageMod is correctly populated
- cast destructive curse
expected:
- elementalDamageMod is correctly populated for a void wand casting destructive curse
actual:
- elementalDamageMod remains at 1.0 for a void wand, because the weapon parameter was not being passed properly down the chain
Thanks for Xenocide for finding and reporting this issue!
> fix weapon parameter for HandleCastSpell -> CreateEnchantment

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
repro steps:
- go into combat mode
- dequip an item that isn't selectable in the 3d world (ie. a piece of armor, aetheria, or cloak)
- re-equip it
expected:
item is re-equipped as normal, similar to dequipping it
actual:
character automatically exits combat mode while re-equipping item
Thanks to ╞ô╡ for reporting this issue!
> fix equipping non-selectables in combat mode exiting combat mode

- Source/ACE.Server/Entity/Fellowship.cs
instead of evenly splitting between luminance-eligible fellows, retail supposedly split between *all* of the fellowship members, and then just "ate" the luminance for any fellows who weren't luminance-eligible
> update Fellowship.SplitLuminance() to better match retail

- Source/ACE.Common/ACE.Common.csproj
- Source/ACE.Common/Cryptography/BCryptProvider.cs
BCrypt.Net-Core was a 3rd party release to port BCrypt.Net to .NET Core in the early days of .NET Core.
BCrypt.Net-Next is the current standard for BCrypt.Net https://github.com/BcryptNet/bcrypt.net
The same hash method is still used.
> Switch from BCrypt.Net-Core to BCrypt.Net-Next

- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.Database/ACE.Database.csproj
Not sure why these were ever added in the first place. They are not needed as nuget to build.
> Remove some unreferenced System packages

- Source/ACE.Server/ACE.Server.csproj
This is the heaviest ref so it's nice to remove.
We used MySql.Data to execute database update scripts since this pr: https://github.com/ACEmulator/ACE/pull/2736/files
Now we use MysqlConnector
> Remove MySql.Data package ref

- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Database/ShardDatabaseWithCaching.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
PlayerManager saves offline players in bulk, once very hour. This is done in bulk to help avoid desync between offline player updates.
Player caching is typically set to 30 min.
What can happen now is that PlayerManager may save a bunch of offline players, that will then be loaded into the player biota cache (for 30 min)... then after 30 min, they all get unloaded because nothign touches those biotas, then 30 min later again the PlayerManager performs its hourly maint of bulk save, thus, re-caching all those biotas.
Caching is not necessary for these biotas.
Caching is designed for biotas that exist in an online or recently online state.
> Improve Offline Player Saving

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Program.cs
Maybe this will help recover long running servers that go into GC sawtooth pattern
> Enable LOH Compacting on forcegc

- Source/ACE.Server.Tests/Physics/SphereTests.cs
- Source/ACE.Server/Physics/Sphere.cs
Several of the functions in Sphere take parameters that were not used. This PR creates overloads that retain the existing signatures, marks them obsolete, and removes the unused parameters from the core function.
GetHashCode is optimized
FindTimeOfCollision is marked Static
> Improve Sphere stack usage

- Source/ACE.Server.Tests/Physics/SphereTests.cs
- Source/ACE.Server/Physics/Sphere.cs
Pass Center and Radius to static functions as parameters instead of instantiating a new Sphere on the heap and passing that through the code.
Reference: https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/performance/
This is built on top of the improve stack PR.
> Improve sphere heap usage

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Portal.cs
This is a minor change adding a server property to optionally disable the maximum level restriction on portals. Other restrictions are unaffected by this property.
Server owners can use this property to enable access to certain legacy content that is otherwise practically inaccessible, such as dungeons and quests associated with retired starter towns.
> Add use_portal_max_level_requirement server property

- Database/Updates/Shard/2024-02-10-00-Explorer-WCIDs-Inactive-Blank-Golem.sql
These correspond to ACE-PY16-Patches PR 1635.
> Shard SQL Updates to go with Patches PR

- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
According to PCAPs GameEventMagicPurgeBadEnchantments was sent to clients for players with Enduring Enchantment augmentation.
Client has slightly different check in CEnchantmentRegistry::PurgeBadEnchantmentList versus CEnchantmentRegistry::PurgeEnchantmentList
```cpp
if ( v4->data._smod.type & 0x2000000 || v4->data._duration == -1.0 )
```
vs
```cpp
if ( v4->data._duration == -1.0 )
```
> Wire up GameEventMagicPurgeBadEnchantments

- Source/ACE.Database/Models/Shard/CharacterExtensions.cs
- Source/ACE.Server/WorldObjects/Player_Character.cs
Check for existing SpellId on same SpellBar before attempting to add
> Adjust AddSpellToBar

- Source/ACE.Server/Physics/Common/PhysicsTimer.cs
PhysicsTimer.CurrentTime evalulated the stopwatch every single call.
This simply redirects the timer to use the master Timers.PortalYearTicks timer
> Switch PhysicsTimer

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
This is required for the functionality of the early part of Assassin's Roost where a player uses an item and an NPC sends the player a tell.
> Foward Player object to Activation Target in Activate Emotes

- Source/ACE.Server/WorldObjects/Creature_Networking.cs
Specifically, this fixes an issue with the Fort Tethana Sentry (24493) where the uppers of the boots were not visible. This is also likely to correct/change some similar minor appearance issues elsewhere.
> Fix layering issues with armor/clothing

- Source/ACE.Server/Entity/LandblockGroup.cs
This also reduces the spacing by 1 which should still be plenty safe.
> More aggressively try to split larger landblock groups

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
Swap out GetBiotaCount for GetEstimatedBiotaCount to explicit counting of all db records.
See https://mariadb.com/kb/en/incredibly-slow-count-on-mariadb-mysql/
> Adjust serverstatus command

- Source/ACE.Server/Managers/RecipeManager.cs
Adding inscriber, if found, to output
Additionally added some notes about differences from retail and ACE based on pcap finds.
Don't think its worth trying to replicate retail in this case because of how janky it actually was.
> Update Tinkering Broadcast message

- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
http://acpedia.org/wiki/Announcements_-_2007/02_-_Rekindling_the_Light
Spell Words and Squelching
Players who have another player squelched will now be able to see that players spell words, even though they are squelched. If a player has filtered spellcasting, they will still not be able to see the spell words.
> Remove Spell Words from Squelch

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Re-enforces expected default state of Ethereal after object is dropped by player
> Adjust Ethereal state on Drop

- Source/ACE.Entity/Enum/CharacterOption.cs
Improves performance with CharacterOptionExtensions. There is some overhead with calling GetAttributeOfType, so we are pre-caching these results.
Moves CharacterOptionExtensions from ACE.Entity to ACE.Server, as ACE.Entity's .NET Standard doesn't support FrozenDictionary or Enum.GetValues<T>.
I could rewrite this in a way that is compatible with .NET Standard, but it seemed more appropriate for the class to be in ACE.Server anyway so I moved it for now.
> Improve performance with CharacterOptionExtensions

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes issues with spells such as Hunter's Lash (built in spell on Weeping Wand and others) not firing.
Thanks to quakerowntmeal for the bug report.
> Add physical damage handling for Life Magic Projectile spells

- Source/ACE.Database/DatabaseManager.cs
- Source/ACE.Database/Models/Auth/AuthDbContext.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/Models/World/WorldDbContext.cs
Adjusted database connections so that they cache ServerVersion.AutoDetect result on first hit and reuse.
This resolves a current bug that exhausts or times out connections to database.
> Cache ServerVersion.AutoDetect

- Source/ACE.Server/Program_Setup.cs
Thanks to @LingradAC for finding this typo
> fix setup typo

- Source/ACE.DatLoader/DatReader.cs
Thanks to @bDekaru for reporting this issue, @paradoxlost for helping to track it down, and @OptimShi for authoring the fix
This fixes cell id 0x01580123 from being read incorrectly for the final bytes
See the full discussion here: https://discord.com/channels/261242462972936192/417073903094202371/1333891031351038066
> fix dat chunking

- Source/ACE.Server/Command/Handlers/DeveloperDatabaseCommands.cs
- Source/ACE.Server/Entity/CorePlating.cs
Also added a `fix-gear-plating` dev command which will check all existing Gear Plating Name values for inconsistencies. While some of these may be due to an item being plated, then reduced by a Tailor, it will just have the same effect as using the `Core Plating Deintegrator` and re-using the `Core Plating Integrator` again.
I ran this new function across all PropertyInt.Locations variations in the ace_world database and all are accounted for. Some custom content with unique coverage may cause some Gear Plating names to be incorrect, but nothing that will break.
Since this system appeared to be recipe based in retail, I took some liberties in standardizing some items and assigning a few that there were no logs/pcaps found into existing naming conventions.
> Reworked Gear Plating Name functionality to fix some gaps and omissions.

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Thanks to kewne for reporting this issue
repro steps:
- equip a thrown weapon
- enter combat stance
- equip a shield
expected:
- thrown shield stance is transitioned into without exiting combat stance
actual:
- shield is equipped and combat stance is exited
similar problems with unequipping shield while in thrown shield combat stance, and swapping between sword+shield and thrown+shield while in combat stance also fixed
> fix thrown shield stance swapping

- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
OnTalk was missing from Suicide and DoSpellWords, both of which used GameMessageHearSpeech
OnTalk is currently a player function, it is possible it should be moved up the chain so the two remaining GameMessageHearSpeech and similar messages for Creatures or WorldObjects should be included in making HearChat emotes be triggered by players and npc alike for custom content purposes, but there may be a hidden problem with expanding that scope, so I'm not doing that for now.
> Add missing OnTalk to a few places

- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
If a weenie no longer exists in `ace_world`, for example it was deleted or not re-importing back after updating `ace_world`, but still exists in the game world then getting the WeenieClassName would cause a crash (e.g. using `/getinfo` on the item).
> Handle getting WeenieClassName for missing weenie

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
Thanks to Raile for reporting this issue!
> add missing ServerSaveFailed messages for vendor transactions

- Source/ACE.DatLoader.Tests/ACE.DatLoader.Tests.csproj
- Source/ACE.Database.Tests/ACE.Database.Tests.csproj
- Source/ACE.Server.Tests/ACE.Server.Tests.csproj
---
updated-dependencies:
- dependency-name: MSTest.TestAdapter dependency-version: 3.10.1 dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: MSTest.TestAdapter dependency-version: 3.10.1 dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: MSTest.TestAdapter dependency-version: 3.10.1 dependency-type: direct:production update-type: version-update:semver-patch ...
> Bump MSTest.TestAdapter to 3.10.1

- Source/ACE.Server/Factories/Tables/Wcids/ArmorWcids.cs
not sure how this was missed, as i could have sworn i had programs that listed every wcid found in the magloot corpse logs, and cross-referenced that with the ace loot tables...
searching the discord history, it looks like this was known as far back as 2020. a content update needed to be made first to fix the 37210 wcid. after the content was updated, i forgot to update the code.
matched the %s up to other tables such as SedgemailLeatherWcids. ideally a format would be added to these tables to express an even chance for sets that are not evenly divisible.
thanks to Aristogeiton and Evanesque for reporting this issue!
> add missing olthoi koujia sollerets to loot tables
