ACEmulator/ACE

- Source/ACE/Network/Handlers/CharacterHandler.cs
It was not changing the AccountId in the database when saving leading to empty character list.
> Fixed bug in CharacterCreate.

- Source/ACE/ACE.csproj
- Source/ACE/Entity/Enum/AccessLevel.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionAdvocateTeleport.cs
- Source/ACE/Network/GameAction/GameActionOpcode.cs
> Adding in support for teleportation via clicking on the map panel.

- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Position.cs
Z position needs to be calculated from a file but since that isn't in the code yet, I'm defaulting it to 200.  For some places that is not high enough and you'll be in darkness, but at least this allows you to teleport using coordinates.
> Added /teleto command

- Source/ACE/ACE.csproj
- Source/ACE/Command/CommandManager.cs
- Source/ACE/Command/Handlers/AccountCommands.cs
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Command/Handlers/ConsoleCommands.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
Stubbed known admin commands with expected usage. not all could eventually be needed. Some example output could also be expanded upon as needed.
> Stubbed CommandHandlers for known AdminCommands

- Database/Updates/Character/2017_02_16_character_friends_create_table.sql
- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/ICharacterDatabase.cs
- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/Character.cs
- Source/ACE.Entity/Friend.cs
- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/WorldManager.cs
- Source/ACE/Network/Enum/AddFriendResult.cs
- Source/ACE/Network/Enum/RemoveFriendResult.cs
- Source/ACE/Network/GameAction/Actions/GameActionAddFriend.cs
- Source/ACE/Network/GameAction/Actions/GameActionRemoveFriend.cs
- Source/ACE/Network/GameAction/GameActionOpcode.cs
- Source/ACE/Network/GameEvent/Events/GameEventFriendsListUpdate.cs
- Source/ACE/Network/GameEvent/GameEventOpcode.cs
- Source/ACE/Network/Managers/PacketManager.cs
> Issue 39 friends list

- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameMessages/GameMessageChannel.cs
- Source/ACE/Network/GameMessages/GameMessageOnChannel.cs
- Source/ACE/Network/GameMessages/GameMessageOpcode.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageEffect.cs
- Source/ACE/Network/Managers/NetworkManager.cs
- Source/ACE/Network/ServerPacketFragment.cs
Forgive my get newb..
I added a method of picking your channels on each message type..
Example of creating a message with channel can be found..
```
public class GameMessageEffect : GameMessageOnChannel
//using the ChannelMessages.
//plays particle effect like spell casting or bleed etc..
public void PlayParticleEffect(uint effectid)
{
var effectevent = new GameMessageEffect(this.Guid, effectid);
NetworkManager.SendWorldChannelMessages(Session, new GameMessageOnChannel[] { effectevent });
}
```
> Network Channels + Player Effect to Test @effect 20

- Source/ACE/Command/Handlers/AdminCommands.cs
as provided by /loc command from client.
> Corrected Teleloc command to work with exact numbers

- Database/Updates/Character/2017_02_28_character_add_options_fields.sql
- Database/Updates/Character/updates.txt
- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/ICharacterDatabase.cs
- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/Character.cs
- Source/ACE.Entity/CharacterOptions1Attribute.cs
- Source/ACE.Entity/CharacterOptions2Attribute.cs
- Source/ACE.Entity/Enum/CharacterOption.cs
- Source/ACE.Entity/Enum/CharacterOptions1.cs
- Source/ACE.Entity/Enum/CharacterOptions2.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/Enum/CharacterOptionDataFlag.cs
- Source/ACE/Network/Enum/SingleCharacterOption.cs
- Source/ACE/Network/GameAction/Actions/GameActionSetCharacterOptions.cs
- Source/ACE/Network/GameAction/Actions/GameActionSetSingleCharacterOption.cs
- Source/ACE/Network/GameAction/GameActionOpcode.cs
- Source/ACE/Network/GameEvent/Events/GameEventPlayerDescription.cs
> Character options are saving/loading from database.

- Source/ACE/Entity/Player.cs
- Renamed abilityUpdate to skillUpdate, to reflect the correct function/variables.
- Refactored the SpendXp skills function to send a gamemessage on failed skill updates that prevents client from locking up the Rank Up interface buttons.
- Added an upper-bounds check to prevent skills from going out of bounds.
- Created an offset variable to prevent +10 from going out of bounds when the rank is to high.
- Changed the comment describing known issues on skillSpend
> A fix to Prevent Skill Spend server crash and allow for max Ranked Skills (Infinity!)

- Source/ACE.Common/ConfigManager.cs
- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.DatLoader/DatManager.cs
- Source/ACE/ACE.cs
- Source/ACE/ACE.csproj
- Source/ACE/Config.json.example
Obtains the two DAT file locations from the config.json file.  Code also handles file not found exceptions and prints out an error.
> Add DAT loading into main process

- Source/ACE/Network/Handlers/CharacterHandler.cs
When creating a character this will set several character options to true and save to the database.
The options set to true are the same ones when you click the "Default" button in the options tab.
> Save default character options when creating a character.

- Source/ACE/Entity/Player.cs
- I could not find a way to check the skill rank after it was set, so I added a function to check max rank. If the function returns a Boolean true, then the server will play fireworks when reached max rank
- Changed the message type to Advancement when increasing skills too reflect the correct skill advancement chat color.
- Added a few summary comments and fixed remarks/known issues.
> Max Rank Fireworks and Correct Skill Rank Up text Color

- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Database/ICharacterDatabase.cs
- Source/ACE/Command/Handlers/AdminCommands.cs
> Character Rename command added

- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE.Entity/Enum/StatusMessageType2.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameMessages/GameMessageOpcode.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageCharacterLogOff.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- Source/ACE/Network/Session.cs
Save character position implemented. Character position is not updated in-game yet.
> Logoff works.

- Source/ACE/Config.json.example
Should fix powershell script problem because our config.json was not in spec due to my comments.
> Bring Config.json.example into spec. 

- Source/ACE.DatLoader.Tests/DatTests.cs
- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.DatLoader/CellDatDatabase.cs
- Source/ACE.DatLoader/DatDatabase.cs
- Source/ACE.DatLoader/DatDatabaseType.cs
- Source/ACE.DatLoader/DatDatabaseTypeAttribute.cs
- Source/ACE.DatLoader/DatDirectory.cs
- Source/ACE.DatLoader/DatFile.cs
- Source/ACE.DatLoader/DatFileType.cs
- Source/ACE.DatLoader/DatFileTypeExtensionAttribute.cs
- Source/ACE.DatLoader/DatFileTypeIdRangeAttribute.cs
- Source/ACE.DatLoader/DatManager.cs
- Source/ACE.DatLoader/PortalDatDatabase.cs
- Source/ACE.DatLoader/Properties/AssemblyInfo.cs
- Source/ACE/Command/Handlers/ConsoleCommands.cs
* improved cell.dat and portal.dat exporting, created admin server commands for them as well as unit tests that can be uncommented.
* bug fix in DatFile with the FileOffset being wrong.  started detailed documentation on dat file contents.
* worked on some object parsing.  found a bunch more object types in the client - now categorizes ALL portal files.
> Dat File parsing

- Source/ACE/Command/Handlers/AdminCommands.cs
Original code only made client aware of change, didn't update the server's player object.
> Heal: Update Player object, then send its data

- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Network/Session.cs
Quick fix; had removed sequence initial value, but apparently it was needed. Testing fail.
Also moved Logout Enqueue to correct place per comment.
> Animation fix

- Source/ACE/Network/Handlers/CharacterHandler.cs
When using this IF statement you can remove the Welcome to this ACE
server!\nFor more information visit http://www.acemulator.org. from
inside the quotes in the config.json file and the popup box does not
appear.
> Created IF statement to remove Welcome popup box

- Source/ACE.Entity/CharacterPositionExtensions.cs
My last PR did not include a necessary file, so I am including it now.
The file is a helper for functions for positions that kept popping up everywhere.
> Fix: Include missing CharacterPositionExtensions.cs

- Source/ACE/ACE.cs
- Source/ACE/Network/ConnectionListener.cs
- Source/ACE/Network/NetworkSession.cs
Fixed issue in InboundFragmentCombining, also fixed exception in ConnectionListener which would stop the server from accepting connections, finally added Logging statement in Main which seems to allow log4net to work
> Network fixes

- Source/ACE/Network/ConnectionListener.cs
- Source/ACE/Network/NetworkSession.cs
Have a test case now.  Confirmed it works.
> REALLY fixed inbound packet combining

- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/AnimationOverride.cs
- Source/ACE.Entity/PaletteOverride.cs
- Source/ACE.Entity/TextureMapOverride.cs
- Source/ACE/Entity/ImmutableWorldObject.cs
- Source/ACE/Entity/ModelData.cs
no data yet, still debugging my exports
> animations, palettes, and textures for world objects

- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionDie.cs
- Source/ACE/Network/GameAction/Actions/GameActionTeleToLifestone.cs
- Source/ACE/Network/GameEvent/Events/GameEventYourDeath.cs
- Source/ACE/Network/GameEvent/GameEventType.cs
- Source/ACE/Network/Sequence/SequenceType.cs
- changelog.md
Simple player death that allows for @lifestone and @die functionality.
- Added YourDeath GameMessageEvent and interface
- Added suicide, killing, and death
- Added value checks on setcharposition
We currently do not yet have death messages or vitae penalties.
> Feature: Death

- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/MovementData.cs
- Source/ACE/Entity/PhysicsData.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Network/Enum/CombatMode.cs
- Source/ACE/Network/Enum/MovementStateFlag.cs
- Source/ACE/Network/Enum/MovementTypes.cs
- Source/ACE/Network/GameAction/Actions/GameActionChangeCombatMode.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageUpdateMotion.cs
- Source/ACE/Network/Managers/InboundMessageManager.cs
- Source/ACE/Network/Motion/GeneralMotion.cs
- Source/ACE/Network/Motion/MotionItem.cs
- Source/ACE/Network/Motion/MotionState.cs
- changelog.md
Added basic motion classes.
Added current motion state to PhysicsData, which can now be sent in CreateObject messages.
Updated GameEventUpdateMotion to use these new classes.
Updated any areas that were affected.
Basic Combat Stance changing.  Can go into UA.  For some reason, you can't get out right now.
> Further Animation/Motion work, half-working combat stance changing

- Source/ACE/Entity/PhysicsData.cs
- changelog.md
Not sure why this sequence was changed, but this fixes the issue.
> Fix for Animations

- Source/ACE/ACE.csproj
- Source/ACE/Command/CommandHandlerAttribute.cs
- Source/ACE/Command/CommandManager.cs
- Source/ACE/Command/Handlers/AccountCommands.cs
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Command/Handlers/CharacterCommands.cs
- Source/ACE/Command/Handlers/ConsoleCommands.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Command/Handlers/HelpCommands.cs
- Source/ACE/Managers/LandblockManager.cs
- Source/ACE/Network/GameAction/Actions/GameActionTalk.cs
- changelog.md
Should this PR be accepted, I would expect going forward all commands added to or implemented by the CommandManager should be required to have Description and Usage attributes properly set to be accepted for PR merge.
> Add @acehelp and @acecommands

- Source/ACE/Entity/PhysicsData.cs
- changelog.md
Partially fixes #246.
Need to look further at the portals found here
`/teleloc 0x00070163 85.16493988 -39.95851898 0.005 0.78485435 -0.61968029 0 0`
which would carry over to Portal to Town Network portals found on surface in towns.
@Lidefeath pointed this fix resolve issues with his creature spawning so I applied it to the main serializer which then corrected a lot of the exception errors being show in ACLogView
> Updated PhysicsData

- Source/ACE.Database/IWorldDatabase.cs
- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/AceCreatureGeneratorData.cs
- Source/ACE.Entity/AceCreatureGeneratorLocation.cs
- Source/ACE.Entity/PortalDestination.cs
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Factories/CorpseObjectFactory.cs
- Source/ACE/Factories/MonsterFactory.cs
- changelog.md
Corpses will despawn after a set amount of time for testing. The retail calculation for the despawn time is currently commented out. Creatures will respawn after a set amount of time too.
Introduced loading randomly generated spawns from the database. See changelog on which table to edit to alter the location.
Please don't mind the Remove Whitespaces commit that was an attempt to get my git to do what I wanted :-)
> Creature respawn, corpse despawn, random spawns

- Source/ACE/Entity/Player.cs
- changelog.md
…y other things which leads to issues.
> Kill UpdateObject sending until we use it right.

- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.DatLoader/Entity/CloObjectEffect.cs
- Source/ACE.DatLoader/Entity/CloSubPalEffect.cs
- Source/ACE.DatLoader/Entity/CloSubPalette.cs
- Source/ACE.DatLoader/Entity/CloSubPalleteRange.cs
- Source/ACE.DatLoader/Entity/CloTextureEffect.cs
- Source/ACE.DatLoader/Entity/ClothingBaseEffect.cs
- Source/ACE.DatLoader/FileTypes/ClothingTable.cs
- Source/ACE.DatLoader/FileTypes/PaletteSet.cs
- Source/ACE.DatLoader/FileTypes/SetupModel.cs
- Source/ACE.Database/CharacterDatabase.cs
- Source/ACE/ACE.cs
- Source/ACE/Entity/Player.cs
- changelog.md
Other minor misc updates/fixes relating to character display.
Moved "DatManager" initialization earlier in the process to prevent folks attempting to login prior to the dat files being loaded (since they are required now).
> Added ClothingTable object and loaded Startup Gear on characters. 

- Source/ACE.Common/ACE.Common.csproj
- Source/ACE.Common/Extensions/CharacterNameExtensions.cs
- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/Enum/IdLookupType.cs
- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/AdminCommands.cs
- Source/ACE/Network/GameMessages/GameMessageOpcode.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageBootAccount.cs
- Source/ACE/Network/Session.cs
- changelog.md
This request should allow a player or account holder, too be kicked from the server. There is an assumption that when the player is sent boot packet, the server will then receive a disconnect message from the client, where finally the server can process the session's finally "log off".
> Feature: Admin `@boot` command

- Source/ACE.Diagnostics/ACE.Diagnostics.csproj
quick fix for build platform x64
> fix built to set default x64

- Source/ACE/Command/Handlers/AdminCommands.cs
- changelog.md
* Built out the functionality to the `@save` admin command.
> Feature: `@save` Admin command

- Source/ACE.Entity/AcePortalObject.cs
- changelog.md
Having these variables changed to private was preventing the Position object from being created correctly.
> Fix bug in Ace.Entity\Ace_portal_object.cs

- Source/ACE.Common/DbGetListAttribute.cs
- Source/ACE.Database/Database.cs
- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/AceObjectPropertiesBigInt.cs
- Source/ACE.Entity/AceObjectPropertiesBool.cs
- Source/ACE.Entity/AceObjectPropertiesDouble.cs
- Source/ACE.Entity/AceObjectPropertiesInt.cs
- Source/ACE.Entity/AceObjectPropertiesString.cs
- Source/ACE.Entity/BaseAceObject.cs
- Source/ACE.Entity/Enum/PositionType.cs
- Source/ACE.Entity/LandblockId.cs
- Source/ACE/Entity/CollidableObject.cs
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/GameData.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/UsableObject.cs
- Source/ACE/Managers/AssetManager.cs
Ok - I have started this work and could really use a review before I get too far down the road.   Issues on the table:
We had 10 items still to determine a place for in the new db schema.   Four have been identified 6 remain.  You can look at and contribute to the ObjectXRef document here: https://goo.gl/mqRWST
Ok - have at it.   Let me know what needs to be changed or if this looks good.   
Link to latest ace_world ERD https://goo.gl/6lZ2wm
> Review & Comment only || Object overhaul - POC 

- Source/ACE.Common/ConfigManager.cs
- Source/ACE/Config.json.example
- Source/ACE/Managers/WorldManager.cs
- changelog.md
* Changed the configuration sections to allow for the "MaxSessions" setting.
* There is a default value of 128.
* Check the Config.json.example for help.
> Added Configuration for Maximum Allowed Sessions

- Source/ACE/Command/Handlers/DebugCommands.cs
- changelog.md
* Added a Helpful debug command for testing who is connected too your server.
> Added debug command @listplayers

- Source/ACE.Common/ConfigManager.cs
- Source/ACE.Database/Database.cs
- Source/ACE.Database/DatabaseManager.cs
- Source/ACE.Database/ICommonDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/AceCharacter.cs
- Source/ACE.Entity/AceObject.cs
- Source/ACE.Entity/AceObjectPropertiesInt64.cs
- Source/ACE.Entity/CachedCharacter.cs
- Source/ACE.Entity/TeleportLocation.cs
- Source/AppVeyor/Config.json
This further adds the ability to launch the client to the character list.
CAUTION: change your config.json to rename the "Character" section to "Shard". This only needs the view vw_ace_character, so as long as the basic fields in there are still provided this PR should work even with a new shard database.
This is the continued work from my first PR, so if you like this PR I'll close the first. If not then the first PR at least allows starting to the command line.
> Read cached characters and launch to char list

- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/Character.cs
- Source/ACE.Entity/DbObject.cs
- Source/ACE/Entity/Portal.cs
More cleanup of the comment errors and Portal object errors.
> Cleaning up error list

- Source/ACE.Entity/Enum/PositionType.cs
- Source/ACE.Entity/Enum/Properties/PropertyInstanceId.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
Additional enums for missing db columns
> ACE Enum adjustments

- Source/ACE.Entity/ACE.Entity.csproj
- Source/ACE.Entity/AceCharacter.cs
- Source/ACE.Entity/AceObject.cs
- Source/ACE.Entity/Enum/Channel.cs
- Source/ACE.Entity/Enum/SecurityLevel.cs
Adding two enums to bring them closer to client expectations, adjusting two objects to fit in to current enums
> More Enum and Object Realignment

- Database/Updates/Shard/001_vw_ace_character.sql
- Source/ACE.Common/ACE.Common.csproj
- Source/ACE.Common/DbGetAggregateAttribute.cs
- Source/ACE.Database/ConstructedStatementType.cs
- Source/ACE.Database/Database.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Entity/CachedCharacter.cs
- Source/AppVeyor/MySqlInstall.bat
implemented GetNextCharacterId using the MAX aggregate
> Extend ORM to allow aggregate functions i.e. MAX(column) and

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Entity/AceObject.cs
- Source/ACE.Entity/CachedCharacter.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
> Implements IsCharacterNameAvailable and fixes some errors

- Source/ACE.Entity/AceCharacter.cs
- Source/ACE.Entity/CachedCharacter.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
With this fixes the view vw_ace_character still works with inner joins.
> Fix the "You do not own this character" error.

- Database/Base/ShardBase.sql
- Database/Base/WorldBase.sql
- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Entity/AceCharacter.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/Portal.cs
- Source/ACE/Managers/LandblockManager.cs
- Source/ACE/Network/GameEvent/Events/GameEventPlayerDescription.cs
- changelog.md
* fixed issue with null exception
* Added OptimShi code to load the correct player appearance 
* Added sending the DataID and InstanceID fields on the player description event.
* Fixed assorted bugs.
* we can now go into and out of combat mode. 
* ci tested and working for all item types.
* telepoi tested and working.
* Trello board updated and cards moved into review - Pending Merge queue.
https://trello.com/b/DXQUfVHj/acemulator-server-project
> Fear the Walking Dead - More work on our object overhaul - bug fixes and continued work

- Source/ACE.Entity/AceObject.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/DebugObject.cs
- Source/ACE/Entity/PhysicsData.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- changelog.md
* Added getting and setting ContainerID and Wielder into AceObject and surfaced in worldObject
* Put in a hack to show how equipped weapons and shields work.   We will need to establish a place to store this data.
* I put in big TODO to identify the hack - it is benign and will not impact anything else other than to demo the placement
* of the spear in Rand the Game Hunters hand in Holtburg.
* Modified SetPhysicsDescriptionFlags so it can be container and weilder aware.
* Worked with OptimShi and we put in a temp fix for Lord BucketHead.   It is the hair - there is an issue loading hair.   I put a todo on it and commented it out.   Rest of the base model looks to be loading correctly.
> Lord BucketHead - temp fix.   Added start of equipping items and POC code

- Database/Base/ShardBase.sql
- Database/Base/WorldBase.sql
Hopefully this should bring the base scripts into alignment and trim out unnecessary tables from each.
> SQL Scripts Re-based

- Source/ACE.Entity/AceCharacter.cs
- Source/ACE/Entity/Player.cs
- changelog.md
Positions save now.
Also fixed initial level ??? bug.
> Fixed Position Saving.

- Source/ACE.Entity/AceCharacter.cs
- Source/ACE/Entity/PhysicsData.cs
- Source/ACE/Network/Enum/CoverageMask.cs
- Source/ACE/Network/Enum/EquipMask.cs
- Source/ACE/Network/GameAction/Actions/GameActionGetAndWieldItem.cs
* made a bunch of comments and notes…about things I discovered so they would not get lost.
Minor stuff, I can resubmit if it is not merge worthy.
> Fixed bug with player creation 

- Database/Base/WorldBase.sql
Syncing ACE-World and ACEmulator.
> Setting ON DELETE CASCADE for ace_poi

- Database/Updates/World/04-06-24-2017-generator-testdata.sql
- Database/Updates/World/04-06-25-2017-generator-trainingdungeon-testdata.sql
- Database/Updates/World/05-06-26-2017-generator-trainingdungeon-part1-testdata.sql
- Source/ACE.Entity/AceObject.cs
- Source/ACE.Entity/Position.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/DebugObject.cs
- Source/ACE/Entity/Generator.cs
- Source/ACE/Entity/Monster.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Factories/GeneratorFactory.cs
- Source/ACE/Factories/GenericObjectFactory.cs
- Source/ACE/Factories/MonsterFactory.cs
- changelog.md
Included test data for training dungeon part 1 which should provide a few objects to help with system build out, such as inventory, respawning, object tracking between clients...
> Add Generator object

- Source/ACE.Diagnostics/FrmMonitor.Designer.cs
- Source/ACE.Diagnostics/FrmMonitor.cs
- Source/ACE/Command/LandblockLoader.cs
- Source/ACE/Managers/LandblockManager.cs
Found small bug in diag tool + bug in load landblock.
should work now... hopefully..
Not the best at landblock understanding here.
But after talking with others.. it appears the landblock in ac are from 0 to 254 ?
I am still confused by this... and Honestly I am just tired of dealing with this... yet trying to fix it..
At this point.. someone else who is understands the landblock system better can patch it if its not right.
> Load alb quick fix / diag fix

- Source/ACE/Entity/WorldObject.cs
- changelog.md
* Fixed issue with the wrong data size being used in the weenie data serialization.
* Structure, Max Structure, StackSize and MaxStackSize were being sent as uint and they are ushort.  This caused intermittent alignment issues.
> Fixed serialization bug.

- Source/ACE.Entity/CreatureSkill.cs
- Source/ACE/Entity/MovementData.cs
Log in a second character, and watch them run around.
> Movement Speeds emulate properly

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE/Managers/GuidManager.cs
Problem with pulls today, simple bugfix.
> Fixed error on guid initialization if there are no players in sharddb.

- Source/ACE/Entity/Creature.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageUpdateMotion.cs
- changelog.md
Found bug - it was introduced by me as part of the fix limping.   This fix should make it all work.   I have tested running, animations and combat stances.   Looks to be working correctly.
> Update to fix animation.

- Source/ACE/ACE.csproj
- Source/ACE/Entity/Fellowship.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionCreateFellowship.cs
- Source/ACE/Network/GameAction/Actions/GameActionFellowshipUpdateRequest.cs
- Source/ACE/Network/GameAction/Actions/GameActionQuitFellowship.cs
- Source/ACE/Network/GameAction/GameActionType.cs
- Source/ACE/Network/GameEvent/GameEventType.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageFellowshipFullUpdate.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageFellowshipQuit.cs
- changelog.md
I don't think Fellowship.cs is in the right place. Wasn't sure where to put it. Any and all feedback is great.
> Some naive, simple fellowship code. Creating and leaving fellow works.

- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.DatLoader/Entity/Contract.cs
- Source/ACE.DatLoader/Entity/PhysicsScriptData.cs
- Source/ACE.DatLoader/Entity/PhysicsScriptTableData.cs
- Source/ACE.DatLoader/Entity/PositionExtensions.cs
- Source/ACE.DatLoader/Entity/ScriptAndModData.cs
- Source/ACE.DatLoader/FileTypes/ContractTable.cs
- Source/ACE.DatLoader/FileTypes/Palette.cs
- Source/ACE.DatLoader/FileTypes/PhysicsScript.cs
- Source/ACE.DatLoader/FileTypes/PhysicsScriptTable.cs
- Source/ACE/Command/Handlers/DebugCommands.cs
- changelog.md
* Added Palette (0x04...) parsing from the client_portal.dat.
* Added PhysicsScript (0x33...) parsing from the client_portal.dat.
* Added PhysicsScriptTable (0x34...) parsing from the client_portal.dat.
* Added ContractTable (0x0E00001D) parsing from the client_portal.dat.
> More Dat Parsing Updates

- README.md
- changelog.md
Based on discord pin yesterday - I thought this would be a good add to the readme.
> Added verbiage to the readme stating the projects educational purpose.

- Source/ACE.Entity/AceCharacter.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- changelog.md
I think I did this right. Thanks Og!
I identified what Unknown_386 was last night, wanted to get a pr in. :)
> Overpowered

- Source/ACE.DatLoader/FileTypes/MotionTable.cs
- Source/ACE.Entity/Enum/ClientProperties.cs
- Source/ACE.Entity/Enum/EmoteType.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Managers/RecipeManager.cs
- changelog.md
Added method to get animation timings out of MotionTable and updated several instances where we were faking it previously.
> Animation Length

- Source/ACE.Entity/AceCharacter.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- changelog.md
Optim and I figured out some more of the unknown enums today, here they are!
> Moar Enumz!

- Source/ACE.Entity/AceObject.cs
- Source/ACE/ACE.csproj
- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Food.cs
- Source/ACE/Entity/Key.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Entity/WorldObject.cs
- Source/ACE/Factories/WorldObjectFactory.cs
- Source/ACE/Network/GameMessages/Messages/GameMessageSetStackSize.cs
- Source/ACE/Network/Sequence/SequenceType.cs
- changelog.md
* Implemented Food class for consuming food items
* Stub created for handling Buffing food but implementation is not complete, as spellcasting has not been completed, yet
* Implemented a method for removing an item from inventory that also handles item stacks.
* Included a fix for stack splitting to create proper WorldObject, instead of defaulting everything to GenericObjects
> Feed my people -- Ready for review and merge

- Source/ACE/Command/Handlers/DebugCommands.cs
- Source/ACE/Entity/Container.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Factories/LootGenerationFactory.cs
- changelog.md
Introducing Vendor and Currency
- There are bugs in inventory in regards to moving things around packs.
- I will be doing another PR spec to fix up inventory tracking but I did not feel like it was for this PR
> Vendor currency

- Source/ACE.Diagnostics/FrmMonitor.Designer.cs
- Source/ACE.Diagnostics/FrmMonitor.cs
- Source/ACE.Entity/CharacterPositionExtensions.cs
- Source/ACE.WeenieEditor/Form1.Designer.cs
- Source/ACE.WeenieEditor/Form1.cs
- Source/ACE/ACE.csproj
- Source/ACE/Entity/Food.cs
- Source/ACE/Entity/Player.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- changelog.md
* Reconfigured and renamed functions to account for Potions being included in class Food
* Wired up applying the chosen starting town to the Training Academy path used
* Squashed some white space StyleCop warnings
> Imbibing in the Starter Towns -- For review and merge

- README.md
- Source/ACE.Api.Common/ACE.Api.Common.csproj
- Source/ACE.Api.Common/ServiceConfig.cs
- Source/ACE.Api.Host/ACE.Api.Host.csproj
- Source/ACE.Api.Host/Startup.cs
- Source/ACE.Api.Host/service_config.json.example
- Source/ACE.Api/Controllers/AccountController.cs
- Source/ACE.Api/Startup.cs
- Source/ACE.AuthApi.Host/ACE.AuthApi.Host.csproj
- Source/ACE.AuthApi.Host/Program.cs
- Source/ACE.AuthApi.Host/service_config.json.example
- Source/ACE.CmdLineLauncher/Program.cs
- Source/ACE.Common/ACE.Common.csproj
- Source/ACE.Common/ApiServerConfiguration.cs
- Source/ACE.Common/MasterConfiguration.cs
- Source/ACE/Config.json.example
- changelog.md
~~* Added lines too Copy `Config.json` too the `Api Host` and `Auth Host` build target directoriess.~~
~~* Changed `*` to `+`, on the Api.Host and Api.Auth.Host startup for non-admins.~~
~~* Added simple service configurations for the Api services, `service_config.json` now requires 2 fields.~~
* Updated README.md to include the required instructions for Api host support.
* Added a few null checks to prevent crashes.
* Added a config error check on the cmd line launcher
> * Api Updates, Cmdline Launcher update, Merged output build target, README updates

- Source/ACE.DatLoader/Entity/CBldPortal.cs
- Source/ACE.DatLoader/Entity/CellPortal.cs
- Source/ACE.DatLoader/FileTypes/CLandblockInfo.cs
- Source/ACE.DatLoader/FileTypes/EnvCell.cs
Cosmetic change pointed out by Rawaho.
> ACE.DatLoader flag fixes for Portals

- Source/ACE/Entity/Actions/ActionChain.cs
- Source/ACE/Entity/Landblock.cs
- Source/ACE/Entity/Player.cs
ActionChain null wrapper added to not crash server if teleporting player disconnects
Resolves 231
> Player teleporting away no longer leaves ghost of self.

- Source/ACE/Entity/Player.cs
- Source/ACE/Network/GameAction/Actions/GameActionGiveObjectRequest.cs
- Source/ACE/Network/GameMessages/GameMessageOpcode.cs
HearDirectSpeech  GameMessage added. Was not used here but was used for collector code I got rid of.
GiveObjectRequest GameAction added.
HandleGiveObjectRequest added to player.
> GiveObjectRequest

- Source/ACE/Entity/StarterHeritage.cs
- Source/ACE/Entity/StarterSpell.cs
- Source/ACE/Network/Handlers/CharacterHandler.cs
- Source/ACE/starterGear.json
- changelog.md
This adds support for all of the starter spells during character creation. Visual Studio auto expanded JSON data in starterGear.json... I'm not sure if that is going to be a big deal or not.
> Starter spells

- Source/ACE.Server/Physics/Collision/CollisionInfo.cs
- Source/ACE.Server/Physics/Common/SetPosition.cs
- Source/ACE.Server/Physics/CylSphere.cs
- Source/ACE.Server/Physics/PartArray.cs
- Source/ACE.Server/Physics/Physics.cs
- Source/ACE.Server/Physics/PhysicsGlobals.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/Scripts/PhysicsScriptTable.cs
- Source/ACE.Server/Physics/Sphere.cs
There are a few different naming conventions for the methods used here - a mixture of standard CamelCase, with some underscores also thrown into the mix. I'm still digging into the rhyme and reason behind the various styles, but this is what was pulled from the original game.
For initial development and debugging purposes, it would much easier for me to match things up 100% to the original game, and then after everything has been completed it can be refactored and the naming conventions can be standardized to match the rest of the ACEmulator project.
> Adding PhysicsObj stubs

- Source/ACE.DatLoader/FileTypes/MotionTable.cs
- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Player.cs
- changelog.md
with assistance of @gmriggs and @OptimShi 
* Added Corpse class and basic framework for spawning a corpse at death of creature.
* use /smite command when you have a creature selected.
> Smite + Corpse Spawning

- Source/ACE.Server/Network/GameEvent/Events/GameEventAllegianceAllegianceUpdateDone.cs
I noticed some parsing issues with this message when investigating the purple bubbles issue. This commit should fix it. I don't know if this will solve the purple bubble issue since I haven't been able to reproduce it with the current code.
> Fix for allegiance update done message.

- Source/ACE.DatLoader/Entity/AnimationHook.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This turns on physics for every WorldObject in game.
> Init All The Physics!

- Source/ACE.DatLoader/Entity/Polygon.cs
- Source/ACE.Server/Physics/Collision/BBox.cs
- Source/ACE.Server/Physics/Util/AdjustCell.cs
- Source/ACE.Server/Physics/Util/Environment.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Fixing the portals in Hotel Swank
https://i.imgur.com/sRCnXrU.jpg -- Keith#3971
> Swanky portals

- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This code submission is primarily to prevent a server crash, when an inventory item is selected as the target.
> Lets Make Some Magic Part 2

- Source/ACE.DatLoader/FileTypes/SpellComponentsTable.cs
- Source/ACE.Server/Command/Handlers/DebugCommands.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Creature, Life, and Item magic are included; no target verification implemented, yet
> Spellcasting Visuals

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Reorganize spell casting code and implement a busy casting state.  Divided casting methods into separate Player and Creature casting methods.
> Casting reorg and busy state

- Source/ACE.Server/Physics/BSP/BSPLeaf.cs
- Source/ACE.Server/Physics/Common/BldPortal.cs
- Source/ACE.Server/Physics/Common/BuildingObj.cs
- Source/ACE.Server/Physics/Common/EnvCell.cs
- Source/ACE.Server/Physics/Common/LandCell.cs
- Source/ACE.Server/Physics/Common/Landblock.cs
- Source/ACE.Server/Physics/Common/MasterDBMap.cs
- Source/ACE.Server/Physics/Common/SortCell.cs
- Source/ACE.Server/Physics/PartArray.cs
- Source/ACE.Server/Physics/Setup.cs
Initial physics engine coding and testing completed :)
> Transitions, collision detection, and sliding with building exteriors / interiors

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Switch Busy state flag from Creature level to WO level that was created in a recent pull request.
> Move busy state flag from Creature to WO

- Source/ACE.Server/WorldObjects/Creature_Vitals.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Next on the TODO list are the Life Bolt spells.
> Transfer spells working

- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Thanks to @Slushnas for the tremendous help with the recent PRs! =)
> Fixing sound events

- Source/ACE.Entity/Enum/Resistance.cs
- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/WorldObjects/Creature_Properties.cs
- Source/ACE.Server/WorldObjects/ProjectileSpell.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Beginnings of casting projectile spells
> Magic :: Lesson 7

- Source/ACE.Server/WorldObjects/ProjectileSpell.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Life and War projectiles now apply damage and XP
> Magic :: Lesson 8

- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Moved generic navigation functions from Player_Melee to a new Creature_Nagivation
- Adjusted Player spell cast timings to account for both self cast and short TurnTo()
- Added a temporary method for corpse cleanup, until more generalized cleanup management is implemented
> Magic :: Lesson 8.7

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Add fast casting
- Increase projectile velocity for Streak war spells
> Magic :: Lessen 9 :: Streaking

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Entity/Enum/EnchantmentCategory.cs
- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventMagicRemoveEnchantment.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventMagicUpdateEnchantment.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPlayerDescription.cs
- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/Network/Structure/EnchantmentRegistry.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureAttribute.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
- Source/ACE.Server/WorldObjects/Player_Xp.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Thanks to @Slushnas and everyone on the ACE team for helping with this latest update :)
> Adding vitae and enchantment registry

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventMagicRemoveEnchantment.cs
- Source/ACE.Server/Network/Structure/Enchantment.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
Thanks again to @Slushnas for helping with this patch!
- EnchantmentManager now supports adding/updating/removing all spells
- EnchantmentManager.HeartBeat() has been added, which maintains the spell duration in the database
- Gems added to enchantment registry for PoC
- Player health/stamina/mana updated on death
> Updating EnchantmentManager for handling all spells

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Creature_BodyPart.cs
- Source/ACE.Server/WorldObjects/Creature_Properties.cs
- Source/ACE.Server/WorldObjects/Creature_Skills.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/ProjectileSpell.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Armor
- Imperil
- Vulns
- Prots
> Adding life magic buffs / debuffs

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Swift Killer
- Heart Seeker
- Defender
- Impenetrability
- Banes
> Adding item enchantments to registry, ie. Blood Drinker

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Physics/Common/ObjectMaint.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Adjust missile spawn location
- Attack height trajectory
- Adding collision sound effect
- Fixing cross-landblock projectiles
- Fixing ghost projectiles in dungeons
> Additional bow/crossbow polish

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Removing delay when launching projectiles across multiple landblocks
- Removing Vitae from Life Spells category
- Adjusting player vitals on death
> Minor fixes

- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/Physics/Trajectory.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
> Magic :: Lesson 10 :: Arc spells

- Source/ACE.Server/WorldObjects/SkillCheck.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Implement a magic skill check for the spell being cast, with a chance for failure based upon said skill level
> Magic : Lesson 11 : No cheaters allowed

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootHelper.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
This creates working random loot for all tiers. There are some things that need to be added, or tweaked, but this is very much closer to being finished than not.
> Can we get some loot?

- Source/ACE.Server/Network/GameEvent/Events/GameEventInventoryServerSaveFailed.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Add new GameEvent message for InventoryServerSaveFailed
- Add attuned checking to HandleActionDropItem, with InventoryServerSaveFailed message response
> Implement the Attuned functionality

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootHelper.cs
Previously it was reading the old skill types from the database, such as dagger. Now it reads as light, heavy and finesse.
Also deleted unnecessary code.
> Updated weapon skill type.

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootHelper.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
Previously there was a difference between what the server thought was the skill max, and what the client thought. This fixing the issue.  Also, I know it is still showing my last commit with this PR. I apologize. I definitely need to spend  an hour learning git from the start.
> Fixing Skill Max Out

- changelog.md
A lot of interesting features were added over the last 2 weeks, but were not added to the change log!
- Added Change Log entries for commits between 2018-04-15 to 2018-04-29, including ACE-World-16PY commits.
- Added prefixes to commits for specific features.
> Change Log Catch-up (April 15 to April 29)

- Source/ACE.Server/Network/GameAction/Actions/GameActionGiveObjectRequest.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventInventoryRemoveObject.cs
- Source/ACE.Server/Network/GameEvent/GameEventType.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
GameEvent and Action changes, and re-implementation of the old code for HandleGiveObjectRequest.
Also, using branches now.... Trying to better use Git so I am more productive and more in line with team standards!
> Handing objects to other WO's

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/DebugCommands.cs
- Source/ACE.Server/Physics/Util/AdjustCell.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
Use /crack to unlock/pick/open doors and chests. (don't do drugs)
Use /nudge to correct player position cell ID after teleporting into black space. (experimental, debug)
> @nudge @nudge, got some @crack

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/Key.cs
- Source/ACE.Server/WorldObjects/Lock.cs
- Source/ACE.Server/WorldObjects/Lockpick.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/SkillCheck.cs
added interface for unlocking lockable world objects
added missing sound for pick lock fail
> reduced some code duplication for lockable world objects

- changelog.md
Dear Devs, update changelog.md as you go!
* Added Change Log entries of ACE commits from 2018-04-29 to 2018-05-22.
> Change Log Catch-up (April 29 to May 22)

- Source/ACE.Server/Command/Handlers/DebugCommands.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- changelog.md
Based on feedback and a discussion in the #development Discord channel with @jyrus and @gmriggs, I modified the addallspells code submitted in a previous PR to lay the ground work for learning spells in bulk via the Arwic spell vendors.
> Rework addallspells debug handler

- Source/ACE.DatLoader.Tests/DatTests.cs
- Source/ACE.DatLoader/Entity/Texture.cs
- Source/ACE.DatLoader/FileTypes/SurfaceTexture.cs
added Texture file and Texture file metadata getter
if a few things are mastered it might come in handy
> added SurfaceTexture parser

- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/Physics/Common/Random.cs
- Source/ACE.Server/Physics/Common/WeenieObject.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Hotspot.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
changed Random to a thread-safe singleton
brought WorldObject.HandleActionOnCollideEnd up from physics engine
> added Hotspot WorldObject

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootHelper.cs
Long Descriptions work.
Fixed Casters not having a current mana and just showing up as stored mana.
> Loot fixes/changes

- Source/ACE.Server/Network/NetworkSession.cs
- Source/ACE.Server/Network/Packet.cs
- Source/ACE.Server/WorldObjects/Player_Vitals.cs
fixed bug in Player_Vitals.cs causing a crash upon player disconnect
> implement server side request for retransmission

- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
Monsters should no longer move through walls or other impassable areas
> Adding monster physics-based movement

- Source/ACE.Server/Physics/Common/LandCell.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Fixed a bug where the current cell would be null after portal
> Updating cell transitions

- Source/ACE.Server.Tests/Physics/SphereTests.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageUpdatePosition.cs
- Source/ACE.Server/Physics/Animation/AFrame.cs
- Source/ACE.Server/Physics/Animation/AnimSequenceNode.cs
- Source/ACE.Server/Physics/Animation/MotionTable.cs
- Source/ACE.Server/Physics/Animation/Sequence.cs
- Source/ACE.Server/Physics/Animation/Transition.cs
- Source/ACE.Server/Physics/Common/EnvCell.cs
- Source/ACE.Server/Physics/Common/Landblock.cs
- Source/ACE.Server/Physics/Sphere.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Updated animation system to loop through linked anims properly
- Fixing creature sliding
- Adjusted monster movement speed
- Fixed a possible crash looping through CellArray (todo: use standard for loop to check for newly added cells)
- Temporary fix with mages not being able to loot corpses (todo: Player_Magic should be calling WorldObject.TakeDamage)
- Various bug fixes
> Improved monster movement

- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/Switch.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Rearranged code flow to remove some redundant code
-Aligned Magic damage application with Physical damage
-Added Crit and War skill bonus
> Adjusted Magic code :: WIP :: Testing needed before merge

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/ConsoleCommands.cs
- Source/ACE.Server/Command/Handlers/DebugCommands.cs
- changelog.md
Some commands defined as console or none (which is basically "any") either should not have been or had no handling if they were. Just some tidying up, really.
> Cleaned up some console commands

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Add null check at end of CreateEnchantment()
> Fix missing null check

- Source/ACE.DatLoader/FileTypes/SpellTable.cs
- changelog.md
In console, enter the following commands:
* getspellformula account 1
* getspellformula account 3452
* getspellformula account 3976
* getspellformula account 4024
All should generate appropriate looking results.
> Fixed Spell Formulas

- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
-Fix vendor buying
-Change Enchantment removal type on item running out of mana from DispelEnchantment to RemoveEnchantment
-Added removal of Enchantments when dropping or giving an item away straight from being wielded
> Misc. Fixes

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Adds functionality of redirecting Impen/Banes from a player to their equipped armor and undergarments.
- Mana consumption appropriate for number of WeenieType.Clothing items spells cast on
- Change damage calcs to point to armor pieces for enchants from the player wearing the items
> Redirect Impen/Banes from player to equipped armor and undergarments

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
-Add different wield requirement scenarios
-Fix removal of impen/banes cast by items on themselves
> Fix wield requirements and item enchant removals

- Source/ACE.Entity/Enum/EmoteCategory.cs
- Source/ACE.Entity/Enum/WeenieError.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Adjust Emote and Attuned item handling according to PCAP data findings
> Adjust Emote item interactions and Player and item interactions

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
-Allow giving Attuned items to appropriate NPCs but still prevent passing attuned items to other players
> Allow giving Attuned items to appropriate NPCs

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/Enum/WeaponMask.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
- Source/ACE.Server/Physics/Animation/MovementSystem.cs
- Source/ACE.Server/Physics/Common/EncumbranceSystem.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Vitals.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
- Source/ACE.Server/WorldObjects/Healer.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/Player_Vitals.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Updated EnchantmentManager queries to use the top layer for each SpellCategory
- Updated WeaponDefense and WeaponOffense enchantments to be additive floats
- Improved vital regeneration formulas / ticking
- Improved healing formulas
- Added stance and enchantments to vital regeneration (regeneration/rejuvenation/mana renewal)
- Added basic stamina usage on evasion / jumping
- Fixed a bug in Player_Use not picking up or using items correctly
> Improved vital regeneration, stamina usage

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Physics/Common/ObjCell.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This adds initial support for Volley type spells. I just put static creation offsets in for now until the correct formula is know for finding them.
Thanks to @gmriggs for some pointers on some of the physics related errors I encountered after implementation that needed to be fixed/tweaked.
> Add support for Volley spells

- Source/ACE.DatLoader.Tests/ACE.DatLoader.Tests.csproj
- Source/ACE.Database.Tests/ACE.Database.Tests.csproj
- Source/ACE.Server.Tests/ACE.Server.Tests.csproj
- Source/ACE.Server/ACE.Server.csproj
- appveyor.yml
- changelog.md
To develop, the .NET Core 2.1 x64 SDK is needed from here:
https://www.microsoft.com/net/download/visual-studio-sdks
> Target .NET Core 2.1 instead of 2.0

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Physics/Animation/AFrame.cs
- Source/ACE.Server/Physics/Animation/Transition.cs
- Source/ACE.Server/Physics/BSP/BSPTree.cs
- Source/ACE.Server/Physics/Common/EnvCell.cs
- Source/ACE.Server/Physics/Common/LScape.cs
- Source/ACE.Server/Physics/Common/ObjCell.cs
- Source/ACE.Server/Physics/Common/PartCell.cs
- Source/ACE.Server/Physics/Common/SetPosition.cs
- Source/ACE.Server/Physics/Common/ShadowPart.cs
- Source/ACE.Server/Physics/PhysicsGlobals.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/PhysicsPart.cs
- Source/ACE.Server/Physics/Polygon.cs
- Source/ACE.Server/WorldObjects/Monster.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
AddPhysicsObj() has been added, which calls PhysicsObj.enter_world() for proper initial placement
> Adding object spawning / initial placement system

- Database/Base/ShardBase.sql
- Database/Base/WorldBase.sql
- Database/Updates/Shard/2018-08-10.txt
- Source/ACE.Database/SQLFormatters/SQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/WeenieSQLWriter.cs
- appveyor.yml
Expanding comment data to restore lost output from conversion to ACE based SQL Writers
> Update SQL Writers for more comment output

- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/DeveloperDatabaseCommands.cs
- Source/ACE.Server/Command/Handlers/Processors/DatabasePerfTest.cs
My test results:
Starting Database Performance Tests.
Biotas per test: 1000
This may take several minutes to complete...
1000 individual add   . Duration:  29.9 seconds. Successes: 1000, Failures:    0. Average:  30 ms
1000 individual save  . Duration:  23.9 seconds. Successes: 1000, Failures:    0. Average:  24 ms
1000 individual remove. Duration:  23.7 seconds. Successes: 1000, Failures:    0. Average:  24 ms
1000 bulk add         . Duration:   8.5 seconds. Successes:    1, Failures:    0. Average:   9 ms
1000 bulk save        . Duration:   6.2 seconds. Successes:    1, Failures:    0. Average:   6 ms
1000 bulk remove      . Duration:   7.0 seconds. Successes:    1, Failures:    0. Average:   7 ms
Database Performance Tests Completed
Next step is to modify the save to detect …
> DatabasePerfTest developer command added

- Source/ACE.Entity/Enum/Skill.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Added some dual wield combat formulas
- Fixed a bug where some untrained skills were marked as unusable
- Fixed an attribute formula bug for Item Tinkering
> Adding weapon swapping between hands, and some basic dual wield combat

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Entity/PositionExtensions.cs
- Source/ACE.Server/Physics/Common/BuildingObj.cs
- Source/ACE.Server/Physics/Common/LScape.cs
- Source/ACE.Server/Physics/Common/Landblock.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation_Simple.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This PR includes some refactoring that should make it cleaner/easier to add the missing spell types. It should also fix issues with projectiles not spawning in the correct cell (previously they were assumed to be in the same cell as the caster).
> WIP - Add new spells and some refactoring

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
-Fix casting spells on WeenieType.Cow
-Add EmoteManager.Heartbeat() call to Creature.Heartbeat()
> Couple of fixes

- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Program.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
UpdateWorld sleep/tickCalc should be last thing loop does
Don't show decimal places for debug logs that show time elapsed
PropertyManager less debug output
> Property manager logging tweaks + misc

- Source/ACE.Server/Managers/WorldManager.cs
Group the session maintenance together under the same lock.
Group the landblock functions closer together
> UpdateWorld improvements

- Source/ACE.Entity/Enum/EndTradeReason.cs
- Source/ACE.Entity/Enum/TradeSide.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionAcceptTrade.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionAddToTrade.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionCloseTradeNegotiations.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionDeclineTrade.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionOpenTradeNegotiations.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionResetTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventAcceptTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventAddToTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventClearTradeAcceptance.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventCloseTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventRegisterTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventResetTrade.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventTradeFailure.cs
- Source/ACE.Server/WorldObjects/Player_Trade.cs
- changelog.md
Some of this may be less than elegant, but it appears to work just fine!
> Implement secure trade

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
-Change 'Bonus' suffix to 'Modifier', in WorldObject_Weapons.cs
-Add missile launcher Elemental damage modifier
> Add missile launcher Elemental damage modifier

- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
This also improves the accuracy bar refilling when combat has ended, and when the player doesn't have the auto-attack option selected
>  Adding accuracyMod for missile weapons

- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/HousePortal.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
Seems to fix the MoveTo when using a Portal
> Portal Updates, plus fix IsWithinUseRadiusOf()

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Rating.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Added Ratings formulas
- Fixed a bug where player couldn't appraise items equipped by players or creatures
> Adding Recklessness combat skill

- Source/ACE.Common/GameConfiguration.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Config.json.example
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Program.cs
-Add functionality for preloading landblocks and making them perma-loaded
> Landblock Preloading PoC

- Source/ACE.Entity/Enum/MovementParams.cs
- Source/ACE.Server/Network/Motion/UniversalMotion.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Container_Properties.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Creature_Networking.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Lock.cs
- Source/ACE.Server/WorldObjects/PKModifier.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/Switch.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Fixed a bug where player would switch to Peace mode to open containers
- Fixed a bug where player would return to an open container for closing
- Fixed a bug with arbitrary delays for using / rotating towards items (0.5s/1.0s)
- Improved animation timing when using consumables (food/drink)
- Fixed various bugs with player switching to Peace mode to perform various actions, instead of using the current stance
- Fixed a bug where NPCs were running Actions before completing rotation towards player
- Refactored MoveToChain a bit
> Improved player movement when using items (corpses/chests/doors)

- Source/ACE.Server/Entity/Actions/ActionChain.cs
- Source/ACE.Server/Entity/Generator.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Tracking.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
- Fixed a bug where Olthoi Swarm Eviscerator would spawn a quarter staff in its inventory, and attempt to wield it
- Fixed a bug where some linkable generators were not being classified correctly, and not spawning all of their objects
- Fixed a bug where '/adminvision on' would not take effect immediately
- Fixed a bug where larger monsters were not being detected as within melee range of player
Thanks @kdmxp256 for finding and reporting these bugs
> Some bug fixes - Resolves #1061, #1062 & #1063

- Source/ACE.DatLoader/Entity/AnimationHook.cs
- Source/ACE.DatLoader/FileTypes/ParticleEmitterInfo.cs
- Source/ACE.Entity/Enum/EmitterType.cs
- Source/ACE.Server/Physics/Common/DBObj.cs
- Source/ACE.Server/Physics/PartArray.cs
- Source/ACE.Server/Physics/Particles/Particle.cs
- Source/ACE.Server/Physics/Particles/ParticleEmitter.cs
- Source/ACE.Server/Physics/Particles/ParticleEmitterInfo.cs
- Source/ACE.Server/Physics/Particles/ParticleManager.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/PhysicsPart.cs
Much thanks to Pea and parad0x for their pioneering work to RE these systems
> Adding particle emitters

- Source/ACE.Server/Network/Structure/HousePayment.cs
- Source/ACE.Server/Physics/Common/GfxObj.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/Player_Monster.cs
- Source/ACE.Server/WorldObjects/WorldObject_Equipment.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
> Make StackSize an int instead of ushort

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventIdentifyObjectResponse.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/WorldObjects/Chest.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Fix issue with appraisal of Doors and Chests with respect to lockpick chances, resists and false "bonus"
> Fix Door/Chest appraisal issue

- Source/ACE.DatLoader.Tests/DatTests.cs
- Source/ACE.DatLoader/Entity/FontCharDesc.cs
- Source/ACE.DatLoader/FileTypes/Font.cs
- Source/ACE.DatLoader/FileTypes/LanguageString.cs
- Source/ACE.DatLoader/FileTypes/RenderTexture.cs
- changelog.md
Added RenderTexture, String and Font to DatLoader.FileTypes
> Added three new dat FileTypes

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/WorldObjects/Chest.cs
The treasure feels kind of lite, but it matches with the max items field...
Also, fixed the long description for casters/weapons, for now.
> Treasure for chests.

- Source/ACE.Server/Command/CommandManager.cs
- Source/ACE.Server/Command/CommandParameterHelpers.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Command/Handlers/SentinelCommands.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionTalk.cs
- Source/ACE.Server/Network/NetworkSession.cs
command parser and invoke resiliency
fix /grantxp command so it doesn't overflow
> various fixes

- Source/ACE.Server/Entity/Strings.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Missile.cs
- Source/ACE.Server/WorldObjects/Player_Tick.cs
- Source/ACE.Server/WorldObjects/Player_Vitals.cs
- Source/ACE.Server/WorldObjects/Projectile.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Tick.cs
- Fixing PK death message broadcasts
- Instant player health bar updates
- Adding lifestone protection system
> Adding lifestone protection system

- Source/ACE.Server/Managers/EmoteManager.cs
This resolves https://github.com/ACEmulator/ACE/issues/1128
> Fixing NPCs not returning to default MotionStance

- Source/ACE.Entity/Position.cs
- Source/ACE.Server/Physics/Managers/MoveToManager.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Tick.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Monster.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Improving monster AI to send alerts to nearby friends
- Adding monster max home distance
- Improving monster turning on server while chasing target
> Improving monster AI to send alerts to nearby friends

- Source/ACE.DatLoader/FileTypes/MotionTable.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/Network/Enum/WeaponMask.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionTell.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
- Source/ACE.Server/Physics/Animation/MotionTable.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
- Fixed a bug where item enchantments weren't being calculated correctly between Auras on the player, and the individual items
Thanks to @OptimShi for finding these animation hooks for the attack frames
> Improving per-animation attack frame timing for players and monsters

- Source/ACE.Server/WorldObjects/Vendor.cs
This fixes https://github.com/ACEmulator/ACE/issues/1154
> Fixing vendor prices for stacks

- Source/ACE.Common/Extensions/ListExtensions.cs
- Source/ACE.Server/WorldObjects/Monster_Inventory.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
This also moves ListExtensions to ACE.Common.Extensions
> Fix infinite loop in GetCombatManeuver

- Source/ACE.Server/WorldObjects/WorldObject.cs
This addresses the issue detailed in https://github.com/ACEmulator/ACE/issues/1212
> Adding handler for EmoteSet.Refuse for NPCs

- Source/ACE.Server/WorldObjects/Creature_Networking.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
Also included fix from @OptimShi
> Fixing CombatManeuver multistrike search

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventStartBarber.cs
- Source/ACE.Server/Physics/Common/PartCell.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- changelog.md
Instead of just saving positions, we need to store as DIDs and do proper lookups back to the original weenie for restrictions and other variables.
> Store and Use DIDs for Portal magics

- Source/ACE.Server/WorldObjects/Monster_Inventory.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This fixes https://github.com/ACEmulator/ACE/issues/1249
> Fixing monsters with thrown weapons and shield

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/SkillFormula.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This patch resolves https://github.com/ACEmulator/ACE/issues/1248
> Adding proper handling of KillTaunts

- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/Transition.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This addresses https://github.com/ACEmulator/ACE/issues/1246
> Adding max missile range

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
This addresses https://github.com/ACEmulator/ACE/issues/1245
> Adding vendor handling for unsellable items

- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This resolves https://github.com/ACEmulator/ACE/issues/1258
> Adding all of the wield requirement checks

- Source/ACE.Server/WorldObjects/Monster_Inventory.cs
We must RemoveFromInventory before TryEquip
> Fix monster infinite ammo

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/PetDevice.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Adds missing features for https://github.com/ACEmulator/ACE/issues/1243
> Adding gem activation requirements, and cooldowns

- Source/ACE.Server/Network/GameAction/Actions/GameActionCreateTinkeringTool.cs
- Source/ACE.Server/WorldObjects/Player_Crafting.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This patch refactors the salvaging system, and addresses most of the issues reported https://github.com/ACEmulator/ACE/issues/1226
> Salvaging refactoring

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
This fixes https://github.com/ACEmulator/ACE/issues/1286
> Fixing house hooks + use chains

- Source/ACE.Server/Physics/Common/Landblock.cs
This resolves https://github.com/ACEmulator/ACE/issues/1285
> Asuger Temple fix

- Source/ACE.Server/WorldObjects/Player_Use.cs
This fixes https://github.com/ACEmulator/ACE/issues/1296
> Fixing gem cooldowns

- Source/ACE.Server/Entity/Fellowship.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionFellowshipCreate.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventFellowshipFullUpdate.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
This resolves https://github.com/ACEmulator/ACE/issues/1279
> Adding fellowship loot sharing option

- Source/ACE.Server/WorldObjects/Portal.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes https://github.com/ACEmulator/ACE/issues/1308, https://github.com/ACEmulator/ACE/issues/1310, and https://github.com/ACEmulator/ACE/issues/1312
> Fixing portal recall, adding some feedback messages

- Source/ACE.Database/Models/Shard/CharacterExtensions.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionSetDesiredComponentLevel.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventPlayerDescription.cs
- Source/ACE.Server/Network/Structure/PackableHashTable.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellComponent.cs
This resolves https://github.com/ACEmulator/ACE/issues/1224
> Adding /fillcomps persistence to server

- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
This resolves https://github.com/ACEmulator/ACE/issues/1320
> Adding vendor services

- Source/ACE.Entity/Enum/EquipMask.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
This fixes https://github.com/ACEmulator/ACE/issues/1329
> Fixing putting pants on

- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
This fixes https://github.com/ACEmulator/ACE/issues/1324
> Adding fellowship spells

- Source/ACE.Server/WorldObjects/Player_Magic.cs
This addresses https://github.com/ACEmulator/ACE/issues/1282
> Adding player movement checks to spellcasting

- Source/ACE.Server/Entity/Strings.cs
- Source/ACE.Server/Physics/Common/WeenieObject.cs
- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Move.cs
This addresses https://github.com/ACEmulator/ACE/issues/1311
> Adding falling impact damage

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionBookAddPage.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionBookData.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionBookDeletePage.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionBookModifyPage.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionBookPageData.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventBookAddPageResponse.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventBookDeletePageResponse.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventBookPageDataResponse.cs
- Source/ACE.Server/Network/Structure/PageData.cs
- Source/ACE.Server/WorldObjects/Book.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This adds https://github.com/ACEmulator/ACE/issues/1337 features
> Adding scribing abilities

- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/Network/Enum/ArmorMask.cs
- Source/ACE.Server/Network/Enum/WeaponMask.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/Network/Structure/ArmorProfile.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This fixes https://github.com/ACEmulator/ACE/issues/1336
> Reworking IsEnchantable for unenchantable items

- Source/ACE.Entity/Enum/TargetingTactic.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Monster_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Source/ACE.Server/WorldObjects/Monster_Missile.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This resolves https://github.com/ACEmulator/ACE/issues/1280
> Adding monster targeting tactics

- Source/ACE.Server/Entity/PutItemInContainerEvent.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This fixes https://github.com/ACEmulator/ACE/issues/744
> Handle weapon swapping between hands for dual wielding

- Source/ACE.Server/Entity/Generator.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
This fixes https://github.com/ACEmulator/ACE/issues/1355
> Adding shop generators for vendor

- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes https://github.com/ACEmulator/ACE/issues/1358
> Adding messages for unaffected PK targets

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/QuestManager.cs
- Add support for TOD+ Kill Task quests
- Update AwardLevelProportionalSkillXP and AwardLevelProportionalXP to use emote.Max64
> Emote fixes additions

- changelog.md
- Updated changelog enties for commits in January by Jyrus
> Update Changelog entries for Jyrus

- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
Code in wrong place, moved to correct place.
> Portals should show "Burden Unknown" on ID panel

- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- changelog.md
Create piles of Treasure for weenies marked with TreasureCorpse bool
> Add support for TreasureCorpse

- Source/ACE.Server/Managers/EmoteManager.cs
This fixes https://github.com/ACEmulator/ACE/issues/1420
> Fixing Shadow Armor quest

- Source/ACE.Server/Managers/RecipeManager.cs
This fixes https://github.com/ACEmulator/ACE/issues/1422
> Adjust imbue chance

- Source/ACE.DatLoader/DatManager.cs
- Source/ACE.DatLoader/FileTypes/SpellTable.cs
- Source/ACE.DatLoader/FileTypes/StringTable.cs
- Source/ACE.DatLoader/LanguageDatDatabase.cs
- Source/ACE.Entity/Enum/WeenieError.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Player_Character.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/Player_Trade.cs
- Source/ACE.Server/WorldObjects/Portal_Properties.cs
- Source/ACE.Server/WorldObjects/SlumLord.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Also fixes numerous bugs reported in https://github.com/ACEmulator/ACE/issues/1405
> Adding house deeds, purchase requirements w/ config options

- Source/ACE.Database/WorldDatabase.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Program.cs
- Source/ACE.Server/WorldObjects/House.cs
GetHousePortals
GetHousePortalsByLandblock
> This switches two world db house functions to use caching

- Source/ACE.Database/SQLFormatters/World/EncounterSQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/HousePortalSQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/RecipeSQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/TreasureDeathSQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/TreasureWieldedSQLWriter.cs
- Source/ACE.Entity/Enum/HouseBitfield.cs
- Source/ACE.Entity/Enum/HouseStatus.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- changelog.md
Added null check for DeathTreasure and changed the code so it wasn't generating items twice, once on the dead creature and then again on the corpse, in two separate but substantially similar functions
> Changes to GenerateTreasure

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
We need to add the result to EncumbranceVal/Value, not subtract.
> AdjustStack adding negative numbers

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Add three null checks in EnchantmentManager.cs
- Add null check to showstats, in DeveloperCommands.cs
- Correct the enchantments sent for removal from items, in Creature_Magic.cs, to those of on items
> Fix bugs in showstats and RemoveItemSpell

- changelog.md
> February Changelog Updates

- Source/ACE.Server/Factories/LootHelper.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- changelog.md
- Enable basic functionality for InqOwnItems in EmoteManager, with code suggested by gmriggs
- Fix array indexing in LootHelper ( array indexes begin with 0 )
> Enable InqOwnItems

- Source/ACE.Server/WorldObjects/Player.cs
- changelog.md
This resolves https://github.com/ACEmulator/ACE/issues/1475
> Fix appraisal when objectGuid = 0

- Source/ACE.Server/Managers/EnchantmentManager.cs
This resolves https://github.com/ACEmulator/ACE/issues/1460 and prevents the crash from a possible data issue, although we have been unable to repro the bug to find how it happened
> checking for unknown spells in EnchantmentManager

- Source/ACE.Server/Config.js.example
- Source/ACE.Server/Physics/Managers/TargetManager.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Player_Monster.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
This resolves https://github.com/ACEmulator/ACE/issues/1473
> Adding monster spawning aggro

- Source/ACE.Entity/Enum/MaterialType.cs
- Source/ACE.Server/Entity/SalvageResults.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventSalvageOperationsResult.cs
- Source/ACE.Server/Network/Structure/SalvageResult.cs
- Source/ACE.Server/WorldObjects/Player_Crafting.cs
This resolves https://github.com/ACEmulator/ACE/issues/1464
> Adding salvaging output messages

- Source/ACE.Server/WorldObjects/Healer.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
This addresses https://github.com/ACEmulator/ACE/issues/1457
> Updating spellcasting / healing movement check messages to match retail

- Source/ACE.Server/WorldObjects/Player_Death.cs
This patch addresses https://github.com/ACEmulator/ACE/issues/1486
> ensuring player death sequence

- Source/ACE.Server/WorldObjects/Player_Networking.cs
This resolves https://github.com/ACEmulator/ACE/issues/1484
> Adding substates to CurrentMotionState

- Source/ACE.Common/GameConfiguration.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
This addresses https://github.com/ACEmulator/ACE/issues/1459
This normalizes some of the config settings for welcome message / server motd
Note that 'Welcome' stored in Config.js is now deprecated, as Config.js should only be used to store config settings that are required to start the server
The declaration and default values for runtime config properties are shown in PropertyManager.cs. If the server operator would like to change the welcome_msg or server_motd, the following commands should be used:
/modifystring server_motd "Welcome to the custom server!\nHave fun"
> Cleaning up welcome message / server motd

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
This resolves https://github.com/ACEmulator/ACE/issues/1496
> Adding /teletome

- Source/ACE.Server/WorldObjects/WorldObject_Database.cs
Also adds logging to detect other missiles that are getting around the WeenieType check.
> Dont persist missiles to shard

- Source/ACE.Server/WorldObjects/Scroll.cs
This resolves https://github.com/ACEmulator/ACE/issues/1501
> Adjusting training check for reading scrolls

- Source/ACE.DatLoader/DatDatabaseType.cs
- changelog.md
Language and Highres were incorrectly set in DatDatabaseType
> Corrected DatDatabaseType values

- Source/ACE.Server/Entity/Fellowship.cs
This resolves https://github.com/ACEmulator/ACE/issues/1507
> logging off while in fellowship

- Source/ACE.DatLoader/FileTypes/LanguageInfo.cs
- Source/ACE.Server/Command/CommandManager.cs
- changelog.md
Added LanguageInfo to DatLoader (0x41 in client_local_English.dat)
Added improved feedback when issuing invalid console commands or using incorrect syntax
> Dat update

- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
This resolves https://github.com/ACEmulator/ACE/issues/1518
> Adding fellowship name to player appraisal window

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
- Source/ACE.Server/WorldObjects/Player_Move.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
This resolves https://github.com/ACEmulator/ACE/issues/1528
> additional error messages for allegiance swearing

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This resolves https://github.com/ACEmulator/ACE/issues/1534
> pluralizing give messages w/ stacksizes

- Source/ACE.Server/Network/GameEvent/Events/GameEventPlayerDescription.cs
- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/Player_Tracking.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- changelog.md
* Skip Burden in CreateObject if object is Creature
* Update PlayerDescriptionEvent for pulling correct WeenieType and HasHealth bool
* Stop sending all children equipped items
> Odds and Ends

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Server/Managers/EnchantmentManager.cs
This resolves https://github.com/ACEmulator/ACE/issues/1547
> retaining item enchantments on death

- Source/ACE.Server/Managers/HouseManager.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- changelog.md
* Appraised items on housing hooks now show the details on the hooked item.
Fixes Issue #1524
> Hook appraisals

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
/teledungeon A Red Rat Lair
/teledungeon 103
/teledungeon 0x103
/teledungeon 0x103FFFF
> adding /teledungeon

- Source/ACE.Common/Extensions/StringExtensions.cs
- Source/ACE.Database/Models/World/WeenieExtensions.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventApproachVendor.cs
- Source/ACE.Server/Network/Structure/HousePayment.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This resolves https://github.com/ACEmulator/ACE/issues/1574
> Adding alternate currency for vendors

- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
This fixes https://github.com/ACEmulator/ACE/issues/1455
> fixing sentries running in circles

- Source/ACE.Server/WorldObjects/Storage.cs
This resolves https://github.com/ACEmulator/ACE/issues/1582
> updated house storage for Chest.CheckUseRequirements()

- Source/ACE.Server/WorldObjects/Hotspot.cs
- changelog.md
No more hot spot of doom in Frore
> Prevent HotSpot instant-kill

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
this fixes the issue w/ vtank casting delays
> updating war magic projectile spell messages

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- changelog.md
Only items of matching ItemType are allowed to be sold to/bought by vendor
> Update Vendor to use MerchandiseItemTypes field

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- changelog.md
Server should send 0x0022 to remove item from player's inventory and place it in vendor's
> Change Message Sent for Vendor Sell Item

- Source/ACE.Server/WorldObjects/Corpse.cs
This fixes https://github.com/ACEmulator/ACE/issues/1612
> updating monster corpse looting permissions

- Source/ACE.Database/AuthenticationDatabase.cs
- Source/ACE.Database/SerializedShardDatabase.cs
- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/HelpCommands.cs
- Source/ACE.Server/Command/Handlers/PlayerCommands.cs
- Source/ACE.Server/Entity/IPlayer.cs
- Source/ACE.Server/Entity/OfflinePlayer.cs
- Source/ACE.Server/Factories/PlayerFactory.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Sentinel.cs
- changelog.md
* Update Logout to include server population and limits when character list is resent.
* Updated @acehelp and @acecommands to not be individual messages, so not to be broken up by other chat spew.
* Added @pop command -- Tells you how many players are online.
* Added @watchmen command -- Displays accounts of a specific access level.
* Added @finger command -- Displays information about a character and/or account.
> Several Command Updates

- Source/ACE.Server/Entity/Generator.cs
- Source/ACE.Server/Entity/Landblock.cs
> Change generator AddWorldObjectInternal failures to Debug

- Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
> Change StopConditionsInit and StopConditionsMax to log.Warn

- Source/ACE.Server/Entity/Generator.cs
Further efforts to reduce console output chatter
> Generator Console.WriteLine -> log.Debug

- Source/ACE.Database/Models/Shard/BiotaExtensions.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Managers/HouseManager.cs
Also fix a HouseManager exception
> Add biota id:name to db exceptions

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Player_Crafting.cs
also adds "salvage_handle_overages" property, which defaults to retail behavior
> fix salvaging workmanship bug

- Source/ACE.Common/Time.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventIdentifyObjectResponse.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Trade.cs
- Source/ACE.Server/WorldObjects/Vendor.cs
- changelog.md
* Can ID items in trade window properly
* Only initiator does MoveTo/Rotate now
> Fix some issues with secure trade.

- Source/ACE.Server/Command/Handlers/AdminShardCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperDatabaseCommands.cs
- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/Enum/SessionTerminationReason.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/Network/SessionTerminationDetails.cs
- Source/ACE.Server/Program.cs
- changelog.md
- Update to latest master
- Start ACE and close world using `world close boot`
- Run `fix-shortcut-bars` command
- if there are bugged players, issue `fix-shortcut-bars execute` command
- Once that is finished, world is ready for stage two update
> Shortcut Fix Stage 1

- Source/ACE.Server/Command/Handlers/AdminShardCommands.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Network/Session.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
- changelog.md
Non player objects, activating other non player objects
Example: Scold @teleloc 0x64480106 [47.215000 -14.227200 -30.000000] 0.000000 0.000000 0.000000 -1.000000
> Fix issue with Activate emote

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
* Send contents of container when given one by a player
* Attempt to return failed given item back to giver
> GiveObjectToPlayer fixes

- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/Enum/CharacterError.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
added element descriptions copied from old comments
confirmed AccountInUse and Undefined are not real character errors
> replaced character errors with confirmed working list

- Source/ACE.Server/Managers/EmoteManager.cs
- changelog.md
Only known use case:
Blank Augmentation Gem -> Donatello Linante -> Asheron's Lesser Benediction
> Add support for AwardXP "spending" xp

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Rare.cs
- Source/ACE.Server/Factories/LootTables.cs
- Source/ACE.Server/Program.cs
- Add Covenant Armor
- Add setting of a default Material Type
- Add Thrown weapons
**Caveat: flatware won't appraise correctly and are currently infinite usage**
> Covenant Armor, default Material Type, and thrown weapons

- Source/ACE.Server/Factories/LootTables.cs
- Updated loot table with correct weenie to drop Yoroi Sleeves
> Yoroi Sleeves

- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootTables.cs
> Align Scroll loot with wiki

- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Add ability to apply Ivory salvage to Attuned items
> Wire up Ivory salvage application

- Source/ACE.Database/SQLFormatters/World/RecipeSQLWriter.cs
- Source/ACE.Entity/Enum/CompareType.cs
- Source/ACE.Entity/Enum/ModificationOperation.cs
- Source/ACE.Entity/Enum/ModificationType.cs
- Source/ACE.Entity/Enum/RecipeSourceType.cs
- Source/ACE.Entity/Enum/RequirementType.cs
- Source/ACE.Server/Managers/RecipeManager.cs
- changelog.md
This swap fixes mods for dyeing
> Change RecipeManager.ModifyX to follow rules of operation

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/CombatPet.cs
- Source/ACE.Server/WorldObjects/PetDevice.cs
- Update Geomancer Golems to actual weenies
- Add option to enable CombatPets to cast spells, as a first step for Advanced Combat Pets, that is defaulted to off
> Updates for CombatPet

- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootTables.cs
- Remove some extra unneeded code from the clothing/armor loot gen
> Little bit of LootGen code cleanup

- Source/ACE.Server/Entity/Actions/DelayAction.cs
volatile is not the proper way to handle this, interlocked is.
> Fix concurrency issue in DelayAction

- Source/ACE.Entity/Enum/XpType.cs
- Source/ACE.Server/Entity/Proficiency.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
- Source/ACE.Server/WorldObjects/Player_Xp.cs
- Rough fix to SpendSkillXP for arbitrary Rank increases
> Skill XP Rank increases

- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- changelog.md
Allow DestinationType.Treasure, Shade 0 items drop to corpse
> Change CreateListSelect to be more inclusive

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Source/ACE.Server/Factories/LootTables.cs
- Consolidate assignment of spells
> Loot Generation Changes

- Source/ACE.Server/WorldObjects/Hook.cs
- Source/ACE.Server/WorldObjects/Hooker.cs
- Fix house hook items with emotes
> Fix house hook items with emotes

- Source/ACE.Server/WorldObjects/WorldObject.cs
> PhysicsObj.Destroy on AddPhsyicsObj failure

- Source/ACE.Server/WorldObjects/Player_Death.cs
- changelog.md
Fix issue that allowed recovering PKs to attack other recovering PKs on PK worlds.
> Tweak MinimumTimeSincePk

- Source/ACE.Server/Entity/Fellowship.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/QuestManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventFellowshipFullUpdate.cs
- Source/ACE.Server/WorldObjects/Player_Fellowship.cs
- changelog.md
> Add expanded support for Fellowship quests

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Decay.cs
- changelog.md
* Prevent items being added to corpses by players
* Changed Landblock.Tick to not decay on first tick
* Update logging for decay of corpses
> More updates for Corpses

- Source/ACE.Server/Entity/DamageEvent.cs
> Features debug

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This fixes https://github.com/ACEmulator/ACE/issues/1986
> adding multiple wield requirements

- Source/ACE.Server/Entity/Landblock.cs
Bit cleaner, doesn't need the warn message.
> LandblockDecay Code Cleanup

- Source/ACE.Server/Entity/Actions/ActionEventDelegate.cs
- Source/ACE.Server/Entity/Actions/ActionQueue.cs
> WRAP_AND_MEASURE_ACT_WITH_STOPWATCH

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/AllegianceNode.cs
- Source/ACE.Server/Entity/Confirmation.cs
- Source/ACE.Server/Entity/Fellowship.cs
- Source/ACE.Server/Entity/IPlayer.cs
- Source/ACE.Server/Entity/OfflinePlayer.cs
- Source/ACE.Server/Managers/AllegianceManager.cs
- Source/ACE.Server/Managers/ConfirmationManager.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/RecipeManager.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionConfirmationResponse.cs
- Source/ACE.Server/Network/Structure/AllegianceData.cs
- Source/ACE.Server/WorldObjects/AttributeTransferDevice.cs
- Source/ACE.Server/WorldObjects/AugmentationDevice.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
- Source/ACE.Server/WorldObjects/Player_Move.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
- Source/ACE.Server/WorldObjects/Player_Xp.cs
- Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
This adds some missing confirmation types (swear allegiance, skill alteration, attribute transfer) and is in preparation for adding some other missing features to swearing allegiance
> ConfirmationManager refactoring

- Source/ACE.Entity/LINQExtensions.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/Fellowship.cs
- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Player_Xp.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
This also has the fixes for lever motion, and also fixes https://github.com/ACEmulator/ACE/issues/2015
> updating fellowship level proportional xp sharing

- Source/ACE.Server/Factories/LootTables.cs
fix revit other VI and switch up nullify item magic id
> fix revit other VI

- Source/ACE.Server/Network/ConnectionListener.cs
> ConnectionListener: Add NetworkReset error handling

- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Hooker.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This also, as a byproduct, fixes character creation for accounts with player or advocate access
> Further refinement for Hookers

- Source/ACE.DatLoader/Entity/AnimData.cs
- Source/ACE.DatLoader/FileTypes/MotionTable.cs
Thanks @OptimShi for finding this
> fixing highframe bug

- Source/ACE.Server/WorldObjects/Player_Xp.cs
- Vitae should not be lowered by Allegiance passup xp
- Possible fix for the remaining vitae > 1.0 bug
> fixing some vitae bugs

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/QuestManager.cs
- changelog.md
* Expand `qst` command.
* Code fix for out of order emote sets.
> Qst command expanded use + rng code fix for emote sets

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
this fix has been backported from 1991
instead of trying to shoehorn the specific functionality that food motions need into the existing EnqueueMotion, this reverts EnqueueMotion to the original, and adds the food-specific functionality to EnqueueMotion_Force
> further adjusting food motions

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
This fixes https://github.com/ACEmulator/ACE/issues/1921
> fixing edge case for equipping thrown weapon w/ dual weapon wielded

- Source/ACE.Database/SQLFormatters/Shard/BiotaSQLWriter.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Entity/Enum/Properties/PropertyString.cs
- Source/ACE.Server/WorldObjects/WorldObject_Set.cs
Also fixed an exception in WorldObject_Set when an wo didn't have an ItemLevel value
> Few more very minor things

- Database/Updates/Shard/2019-06-25-00-Add-Biota-WCID-Index.sql
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
This improves House.SetLinkProperties() performance while loading into mansion/villa basement dungeons by a factor of ~2000% on current CE database
> adding biota wcid idx

- Source/ACE.Server/Entity/Spell.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes the Portal Device bug introduced in https://github.com/ACEmulator/ACE/pull/2043
> do not resist irresistible spells

- Source/ACE.Entity/CharacterCreateInfo.cs
- Source/ACE.Server/Command/CommandManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventChannelIndex.cs
- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
This is just the first pass. More orgnization and work needs to be done to the entire AccessLevel and CommandManager system in the future.
> Convert Envoy use to Sentinel

- Source/ACE.Server/Managers/EmoteManager.cs
- Source/ACE.Server/Managers/QuestManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventBookDataResponse.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Hook.cs
- Source/ACE.Server/WorldObjects/Hooker.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Book.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- changelog.md
Only Hookers can be used on Hooks, everything else is not usable
> Fix several issues with hooks

- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Add RandomizeColor() to Jewelry
- Adjust GetElementalBonus() coding
> Tweaks to LootGen

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Update Creature combat skills for MoA, authored by @gmriggs
> Update Creature Combat Skills for MoA

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
This fixes a last minute bug that snuck into https://github.com/ACEmulator/ACE/pull/2043, where throwing Phials at a target incorrectly sent the wrong message to the thrower (cast spell on you, instead of cast spell on target)
The bug also had a side effect of hiding messages for the target when casting on their equipped items
The code has been normalized a bit to better describe what is going on, and to reduce the chance for these types of errors
> updating enchantment messages

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
Update Vendor to send GameEventInventoryServerSaveFailed on selling 0 items
> Update Vendor Sell Fail Condition

- Source/ACE.Server/WorldObjects/Creature_Magic.cs
mana usage for over 15,000 level 8 bolt casts in retail:
```
Total Casts: 16,520
1: ***************************************************************************
2: ***********************
3: *********************
4: ******************
5: ******************
6: ****************
7: ***************
8: ************
9: *************
10: ***********
11: ***********
12: **********
13: *********
14: ********
15: *********
16: *******
17: ********
18: *******
19: *******
20: ******
21: ******
22: *****
23: ****
24: ****
25: ****
26: ****
27: ***
28: ***
29: **
30: ***
31: **
32: **
33: *
34: **
35: *
36: *
37: *
38:
39:
40:
```
profile of updated formula:
```
1: ***************************************************************************
2: ***********************************
3: …
```
> updating mana conversion to better match retail

- Source/ACE.Server/Entity/SpellProperties.cs
- Source/ACE.Server/WorldObjects/Creature_Magic.cs
- Source/ACE.Server/WorldObjects/Monster_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This will likely need more testing to verify everything behaves like retail but from my own tests everything appears to work properly.
> Add Curse of Raven Fury spell

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Adding some code for https://github.com/ACEmulator/ACE/issues/1583
> adding prevention/debug code for spellbook probability 0

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Attempt at preventing item rollback on crashes
> Save Item to DB in TryCreateInInventoryWithNetworking

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
A few people mentioned interest in this and since it seemed like an easy enough task, I've attempted to add a PKL-mode to servers, so that people can be permanently killable but need not incur vitae or drop items.
> Added ability to have a PKL server

- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This fixes the bug with scatter generator position broadcasting
> adding SyncLocation for enter_world()

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
some types were parsed as an int, but needed to be a long and would cause an exception causing the player to be stuck in godmode
> fix parse types

- Source/ACE.Server/WorldObjects/Hook.cs
- Source/ACE.Server/WorldObjects/House.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Fix issue with invisible hooks on relinks (buy/abandon): bool/physicsstate mis-matches
- Fix issue with RDB on house buy: missing InstanceIID update
- Fix issue with logging into open houses: missing IsOpen check
> Hook & House Fixes

- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
- Source/ACE.Server/Factories/LootTables.cs
- Fix a possible array out of bounds exception in LootGenerationFactory_Magic.cs that could happen with tier 8
- Add OverRobes to clothing drops
- Remove unneeded return for OlthoiKoujiaArmor AL assignment
> Three changes

- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
- Source/ACE.Server/Managers/GuidManager.cs
This also adds dynamic guid information to /serverstatus
> Add some debug messages to GuidManager

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/SkillFormula.cs
This updates the Finesse Weapons attribute mod to use Coordination instead of Strength
It also keeps the same attribute mod factor as the other melee weapons
> finesse attribute mod

- Source/ACE.Server/Physics/Entity/GfxObjCache.cs
This reverts commit 509ebd6148fb71ef4d884333924eb1d0a7284ef1.
Not needed anymore.
> Revert "prototype: GfxObjCache + WeakReference (#1692)"

- Database/Updates/Shard/2019-08-21-00-Fix_Aetheria_SpellBook.sql
- Source/ACE.Server/Entity/Aetheria.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- changelog.md
- Skip adding ProcSpell to Aetheria's spellbook
- Add ProcSpell to appraisal messages
> ProcSpell Changes

- Source/ACE.Server/WorldObjects/Player_Location.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Update code to magic retail messaging
> Update PortalSending and FellowPortalSending

- Source/ACE.Server/WorldObjects/Hook.cs
Per retail, after 03-2006 all characters of an account could manage hook contents
> Allow Hooks to be used by roommates

- Source/ACE.Common/Performance/RateLimiter.cs
- Source/ACE.Common/Performance/RateMonitor.cs
- Source/ACE.Common/Performance/TimedEventHistory.cs
- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/Managers/HouseManager.cs
- Source/ACE.Server/Managers/LandblockManager.cs
- Source/ACE.Server/Managers/ServerPerformanceMonitor.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/Managers/NetworkManager.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
- Source/ACE.Server/WorldObjects/Monster_Navigation.cs
- Source/ACE.Server/WorldObjects/Monster_Tick.cs
This mainly refactors the performance monitoring like RateMonitor.
This will allow monitoring of systems that function under multiple threads simultaneously.
> ServerPerformanceMonitor Refactor

- Source/ACE.DatLoader/Entity/SpellSet.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Player_Spells.cs
- Source/ACE.Server/WorldObjects/WorldObject_Set.cs
> Support SpellSets for Items that don't level

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Dont' replace the item object with a possible null reference on failure
> HandleActionDropItem_Inner fix

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Managers/GuidManager.cs
revert /serverstatus to how it was
improve the output of /idlist
add comments to help describe some functions and properties
remove public properties that could be misused by a developer that doesn't read the summary
> cleaup guid debug info

- Source/ACE.Server/Entity/DeathItem.cs
> removing debug logging for unknown death item types

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Also fixes a bug in dispel trap variances
> allowing Dispel Item Magic to be cast on items

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Move.cs
> Adjusting AddPickupChainToMoveToChain

- Source/ACE.Server/WorldObjects/Creature_Vitals.cs
> CurrentMovementData.Invalid null fix

- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
This fixes the player null exception
> EnchantmentManagerWithCaching Player Null Fix

- Source/ACE.Server/Network/Sequence/SequenceManager.cs
This really doesn't do much, just rearranges some chairs on the titanic really.
Next up, investigate any thread safety requirements on the different sequence classes, or possibly make that a function of SequenceManager.
> SequenceManager tweak

- Source/ACE.Server/WorldObjects/Player.cs
This fixes an exception.
This does not fix the root issue
> Another CurrentMovementData.Invalid is null fix

- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
Thanks @dgarson for discovering this
> handle special case for PKType deaths + Enduring Enchantment + DoTs

- Source/ACE.Database/SQLFormatters/Shard/CharacterSQLWriter.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
Fix CharacterSQLWriter for CharacterPropertiesContractRegistry
PropertyInt, add comments for PlacementPosition and add InventoryOrder for future use.
> CharacterExporter fixes

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Managers/QuestManager.cs
> Add server option for adjusting quest timers

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Managers/QuestManager.cs
- Source/ACE.Server/WorldObjects/Creature.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player.cs
This builds on Ripley's PR https://github.com/ACEmulator/ACE/pull/2427
> adding support for Creature.QuestManager

- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
- Source/ACE.Server/Command/Handlers/PlayerCommands.cs
- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/Managers/ServerManager.cs
- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/Session.cs
This returns the count, when required, without having to create new lists.
> PlayerManager GetOnlineCount() and GetOfflineCount()

- Source/ACE.Server/Network/Structure/HouseData.cs
- Source/ACE.Server/Network/Structure/HousePayment.cs
- Source/ACE.Server/Network/Structure/HouseProfile.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/SlumLord.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
This builds on fartwhif's https://github.com/ACEmulator/ACE/pull/2510 pr, and also fixes some pipelining issues in the original housing functions, for consuming that data w/ full logging for players trying to send any invalid data to the server
> improved handling for overages for house payments

- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This fixes https://github.com/ACEmulator/ACE/issues/2507
> adding CS support for Martyr's Hecatomb

- Source/ACE.Server/Network/ClientPacket.cs
> minor math optimization

- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
> Removed Unused Pet Var that was causing LinuxCompile Warning

- Source/ACE.Common/ConfigManager.cs
- Source/ACE.Server/Program.cs
In current master, on a windows platform, ACE requires the current environment directory to be the same location that the ACE.Server.exe (.NET core 3.1) exists.
If you try to startup the application from an outside directory, the Config.js and log4net.config will not be found as only the Environment.CurrentDirectory were searched.
Now, that directory is searched first. If the files are not found, the ExecutingAssembly Location is searched next.
This needs to be tested on Linux.
> Support application startup from outside directory

- Source/ACE.Server/Entity/Spell.cs
> _spell was null Error -> Debug

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
This command was requested by content devs, so they don't have to go searching through /propertydump
> adding /getinfo command to get basic weenie info

- Source/ACE.Server/Managers/QuestManager.cs
verified all the InqQuestSolves emotes in the database retain their existing behavior
> normalized defaults for InqQuestSolves to match other emotes

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Factories/PlayerFactory.cs
- Source/ACE.Server/Factories/PlayerFactoryEx.cs
- Source/ACE.Server/WorldObjects/Container.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
This is mostly in preparation for another PR which will add logic around these parts, ie. adding support for PropertyInt.Unique
> normalizing some attuned / bonded logic

- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
Updated Door code to make use of properties in the database, whereas previous code was still using the data from pcap model
> Use DefaultOpen / DefaultLocked properties from DB

- Source/ACE.Server/Physics/PhysicsObj.cs
- Source/ACE.Server/Physics/Transition.cs
This fixes some contact plane and landblock transition bugs which could result in the player taking invisible fall damage
Thanks to @CrimsonMage for providing accurate repro steps for this bug
> fix cliff slide, contact plane, and landblock transition bugs

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Thanks to Crimson Mage for spotting this
> adding missing swirlies to recall spells

- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
Thanks to @CrimsonMage for finding this
> show dot resistance on appraisal panel

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
Matched up to video here, and tested w/ vtank 'fastbuff' option:
https://www.youtube.com/watch?v=meqiZTS96sc
Thanks to @CrimsonMage for reporting this issue
> adding support for fastbuffing

- Source/ACE.Server/WorldObjects/Creature_Equipment.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Thanks to @OptimShi for discovering this bug
> moving dequip item spell code from Player.TryDequipObjectWithNetworking to Creature.TryDequipObjectWithBroadcasting

- Source/ACE.Server/Factories/LootTables.cs
> Fix to Spine Glaive to stop Double dropping Mazule

- Source/ACE.Server/Physics/Animation/MotionTable.cs
- Source/ACE.Server/WorldObjects/Door.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- Source/ACE.Server/WorldObjects/WorldObject_Use.cs
- UseTimestamp and ResetTimestamp should not be using non-standard ++ = set the current unix time obfuscation
- Reset() should be checking precise values, and not be prone to subtle action chain / unix time / floating point bugs
> cleaning up door patterns

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/DamageEvent.cs
- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Player_Combat.cs
- Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
This enables /debugdamage being able to target CombatPets and other creatures
> adding /debugdamage support for all creatures

- Source/ACE.Entity/Enum/EquipMask.cs
- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
- Source/ACE.Server/Entity/TinkerLog.cs
Should be reviewed by @ziang4891 and @harliq
> adding verify-armor-levels admin command

- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
- Source/ACE.Server/Factories/LootStats.cs
Added Jewelry Table (for testing Trinkets) and some cleanup
> Loot Factory Simulator Jewelry

- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootTables.cs
Adding Trinkets to Jewelry Drops, Refactored LootGenFactory_Jewelry.cs
Following World PR adds the Trinket Weenies (must be added before or the same time as this PR)
https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/323
> Add trinkets, Refactored Jewelry 

- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/Player_Move2.cs
- Source/ACE.Server/WorldObjects/WorldObject.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
https://asheron.fandom.com/wiki/Dispel_Spells
https://asheron.fandom.com/wiki/Announcements_-_2004/04_-_A_New_Threat
> prevent player-initiated dispels while pk timers active

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/Player_Use.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
> add support for gems with UseUserAnimation and UseSound

- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Allow shields to be included in bonus AL assignment
> Fix lack of Shield AL assignment

- Source/ACE.Server/WorldObjects/Creature_BodyPart.cs
- Source/ACE.Server/WorldObjects/Monster_Melee.cs
confirmed this code is not in acclient
> remove buggy -al code

- Source/ACE.Database/WorldDatabaseWithEntityCache.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/Handlers/CharacterHandler.cs
- Disable creating players with names of creatures in world
- Adjust other checks
> Check player names against creature names in world db

- Source/ACE.Server/WorldObjects/Door.cs
If a player a monster try to both open a door around the same time, some weird state thrashing can apparently occur
> prevent door thrashing

- Source/ACE.Server/Managers/HouseManager.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/SlumLord.cs
This fixes https://github.com/ACEmulator/ACE/issues/2906
Thanks to @imamastermind for reporting this issue!
> adding support for mansion_min_rank 0

- Source/ACE.Entity/Models/PropertiesEnchantmentRegistryExtensions.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
Now all enchantments will have their StartTime reduced by heartbeatInterval, instead of just the TopLevel enchantments
> Fix EnchantmentManager Heartbeats

- Source/ACE.Server/WorldObjects/Player_Death.cs
> adding retail message for Enduring Enchantment

- Database/Updates/Shard/2020-04-13-00-Fix-Copper-Silver-Salvage.sql
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Managers/RecipeManager.cs
Requesting a review from @ziang4891 and @harliq
> fix copper / silver salvage

- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
Added Burden to Loot Sim Tables
> Added Burden to tables

- Source/ACE.Entity/Enum/AppraisalLongDescDecorations.cs
- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
set to match the flags currently on melee weapons
> setting AppraisalLongDescDecoration on missile weapons

- Source/ACE.Common/OfflineConfiguration.cs
- Source/ACE.Server/Config.js.docker
- Source/ACE.Server/Config.js.example
- Source/ACE.Server/Program.cs
- Source/ACE.Server/Program_DbUpdates.cs
- Source/ACE.Server/Program_Setup.cs
- Support automatic database patching
- Support automatic updating of world database to latest release
- Support automatic re-application of world database customization
> Wire up automatic database updates

- Source/ACE.Entity/Enum/CharacterOption.cs
- Source/ACE.Entity/Enum/CharacterOptions2.cs
- Source/ACE.Server/Entity/TurbineChatChannel.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/GameAction/Actions/GameActionSetSingleCharacterOption.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventSetTurbineChatChannels.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageCharacterList.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageTurbineChat.cs
- Source/ACE.Server/Network/Handlers/TurbineChatHandler.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Allegiance.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
> Enable global chat toggling

- Source/ACE.Server/WorldObjects/ProjectileCollisionHelper.cs
Fix gap for projectiles being left behind in the database after collisions
> Destroy projectiles on collision

- Source/ACE.Server/Network/Session.cs
This "hack" deviates from known retail pcaps/behavior, but appears to be the least harmful way to work around something that seemingly didn't occur to players using ThwargLauncher connecting to retail servers.
In order to prevent the launcher from thinking the session is dead, we will send a Ping Response every 100 seconds if the session is not in world/at character selection screen, this will in effect make the client appear active to the launcher and allow players to create characters in peace.
> Add ping to clients at character select

- Source/ACE.Server/Factories/LootGenerationFactory_Rare.cs
- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/WorldObjects/Corpse.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
- appveyor.yml
> Add RealTime Rare chance modifications

- Source/ACE.Server/WorldObjects/ProjectileCollisionHelper.cs
> Revert "Destroy projectiles on collision"

- Source/ACE.DatLoader/DatDatabase.cs
- Source/ACE.DatLoader/DatManager.cs
- Source/ACE.DatLoader/FileTypes/Iteration.cs
- Source/ACE.Server/Entity/CAllIterationList.cs
- Source/ACE.Server/Managers/WorldManager.cs
- Source/ACE.Server/Network/Extensions.cs
- Source/ACE.Server/Network/GameMessages/Messages/GameMessageDDDInterrogation.cs
- Source/ACE.Server/Network/Handlers/DDDHandler.cs
- Source/ACE.Server/Network/Session.cs
- changelog.md
* Added dat file Iteration checking to server files
* Handled DDD_InterrogationResponse to check clients connecting for up-to-date dat files and display a warning upon login.
* Use command "modifybool show_dat_warning true" to show warning to clients upon login.
* Fixed ACE.Server.Network binaryReader.Align() function.
> Dat file iteration checking

- Source/ACE.Server/Command/Handlers/PlayerCommands.cs
- use quest_mindelta_rate server prop when displaying myquests output
- add 'Quest list is empty' response to myquests
> Myquests command fixes

- Source/ACE.Server/WorldObjects/Monster_Inventory.cs
Thanks @DridsGhost and @OptimShi
> Add cloaks to SelectWieldedClothing()

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
Added GUID to /getinfo.
Outputs as hex.
Useful for getting the Guid easily for content creation.
Output Example:
```
GUID: 7A9B404F
WeenieClassId: 509
WeenieClassName: lifestone
> Added Guid to /getinfo

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
MagicSchool.LifeMagic + MetaSpellType.Projectile, ie. 5530 - Bloodstone Bolt VI
Not to be confused with MagicSchool.LifeMagic + MetaSpellType.LifeProjectile
> adding support for life magic projectiles that act like war bolts

- Source/ACE.Database/SQLFormatters/World/EncounterSQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/HousePortalSQLWriter.cs
- Source/ACE.Database/SQLFormatters/World/SpellSQLWriter.cs
- Source/ACE.Entity/Enum/PortalBitmask.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Portal.cs
> SQL Writer tweaks

- Source/ACE.Entity/Enum/Properties/PropertyBool.cs
- Source/ACE.Server/Command/CommandManager.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventBookDataResponse.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
Fixes https://github.com/ACEmulator/ACE/issues/3034
> Fix for sentinel/envoy access level [#3034]

- Source/ACE.Server/Command/Handlers/DeveloperLootCommands.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
- Source/ACE.Server/Factories/LootStats.cs
Added Jewelry table, Arcane req for armor and jewelry, Removed Math rounds
> LootSim Update

- Source/ACE.sln
Updated ACE.sln to use VS2019.
> Update Solution to use VS2019/ver 16

- Source/ACE.Server/Entity/Cloak.cs
based on convos in ace bugs channel
> updating cloak proc spells to skip chance to resist

- Source/ACE.Entity/Models/PropertiesEnchantmentRegistryExtensions.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
This adds functional support for 5753 - Cloaked in Skill
After installing https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/508 :
- /addspell 5753
- cast spell
- /showstats
- wait for spell to expire, /showstats
> adding support for EnchantmentTypeFlags.MultipleStat

- Source/ACE.Server/Entity/AddEnchantmentResult.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
Repro steps:
/ci 36524
/dispel
/buff 7
equip shield
Expected:
Pumpkin Shield casts Web of Deflection on you, surpassing Aura of Deflection
Pumpkin Shield casts Web of Defense on you, surpassing Aura of Defense
Actual:
Pumpkin Shield casts Web of Deflection on you, refreshing Aura of Deflection
Pumpkin Shield casts Web of Defense on you, refreshing Aura of Defense
> ensure refresh layers have same spell id

- Source/ACE.Database/SQLFormatters/SQLWriter.cs
- Source/ACE.Entity/Enum/Properties/PropertyDataId.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Dinnerware.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
Moving properties to runtime only + some SQL writer updates
> Some Appraisal changes

- Source/ACE.Server/WorldObjects/Healer.cs
- Source/ACE.Server/WorldObjects/Player_Location.cs
Fixes issue with VTank double using healkits
> Switch Healer usage to Motion with Commands

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
/ci 28833
Use food
Thanks @bobigor377
> Add Food to LifeMagic

- Source/ACE.Entity/Enum/EmoteType.cs
- Source/ACE.Entity/Models/WeenieExtensions.cs
- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
- Source/ACE.Server/Entity/Enlightenment.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/Player_Skills.cs
- Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
- appveyor.yml
Backend support for using the Font of Enlightenment and Rebirth found in the Temple of the Font located at Viridian Rise
> Add support for Enlightenment

- Source/ACE.Server/Factories/LootTables.cs
- Source/ACE.Server/Program_DbUpdates.cs
Looked to be missing. People were stating on DnF that they never seen them drop!
> Adding Knorr Academy Girth to Loot Table

- appveyor.yml
Update to this latest release and world database to resolve issue with players client crashes and getting stuck in bubbles on login
> Update to resolve Tou-Tou client crashing

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
This bug only happens with the /lootgen dev command... there is no wield difficulty bug for casters in the regular lootgen system
Thanks to 4eyebiped for reporting this issue
> fixing /lootgen caster wield difficulty

- Source/ACE.Server/Managers/RecipeManager.cs
Fixes https://www.reddit.com/r/AsheronsCall/comments/if2211/trade_skills/
> add call to proficiency on successful recipe application

- Source/ACE.Server/ACE.Server.csproj
Since we now have built in setup, we can have the pre build setup skip copying files if they don't exist because ACE will create them for you anyway
> Adjust ACE.Server PreBuild events

- Database/Updates/Shard/2020-08-23-00-Steel-Salvage-Target-Type.sql
- Source/ACE.Server/Managers/RecipeManager_New.cs
This was a change later in retail
Requires https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/602
> allow clothing w/ armor level that only covers extremities (head / hands / feet) to be tinkered with steel profiles

- Source/ACE.Server/WorldObjects/Container.cs
I believe this addresses the issue #3113. Sorry if this was discussed in a dev channel as I don't frequent them as much as I'd like, and is somehow not the right fix. Just let me know and I'll close it out.
> Fix for trading from characters at 300% burden

- Source/ACE.DatLoader.Tests/DatTests.cs
- Source/ACE.DatLoader/DatFile.cs
- Source/ACE.DatLoader/DatFileType.cs
- Source/ACE.DatLoader/FileTypes/LanguageInfo.cs
Mostly just adding file types to DatFile.GetFileType() to help with the test functions.
> Fix DatLoader.Tests

- Source/ACE.Server/Physics/Common/BuildingObj.cs
/tele 15.7S, 65.3W
Expected:
Teleport
Actual:
Caught exception, There was a problem with that location (bad coordinates?).
> fixing specific /tele coord error

- Source/ACE.Server/Entity/SpellProperties.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
** This PR must be installed in tandem with https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/606 **
(will add a more appropriate description for this pr, instead of the copy/paste from the content pr)
For the DoT enchantment.StatModValues sent over the wire in retail, these were based on the amount per tick, and not total amount over the course of the duration of the spell.
DoTs were a bit weird in this regard, void DoTs especially, as the StatModValue in the enchantment that was sent across the wire would not always equal the StatModValue in the base spell. For void DoTs especially, a 'pre-calculation' would be done, that would factor in things that would buff the outgoing damage, and then it would write this buffed value to the enchantment. ie. for void dots, …
> updating DoTs in EnchantmentManager to use retail enchantment.StatModVal format (per-tick, instead of total damage)

- Database/Updates/Shard/2020-09-05-00-Update-Bloodstone-Wand-Crit-Rate.sql
https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/618/
> update crit rate for existing bloodstone wands

- Source/ACE.Server/Command/Handlers/DeveloperLootCommands.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Test.cs
- Source/ACE.Server/Factories/LootStats.cs
Creating 10000 corpses.
before:
StatsTimer: 63.8822824s
after:
StatsTimer: 0.311643s
> improving loot stats performance

- Source/ACE.Server/Physics/Collision/BBox.cs
Repro steps:
/teleloc 0x8766002A [120.211113 44.779186 51.914539] 0.706729 0.000000 0.000000 -0.707484
take a few steps on the rock ramp, and then wait a few seconds
Expected:
nothing
Actual:
player takes fall damage after a few seconds
> add missing calls to adjust bbox

- Source/ACE.Server/WorldObjects/Food.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
blackmoor's favor should not be affected by player's increased spell duration aug
this really is garbage code, but it's required because the magic pipeline is still poorly designed in many areas..
> fixing more fallout from food msg

- Source/ACE.Server/WorldObjects/Player_Tick.cs
/teleloc  0xD6990117 [10.744077 179.707047 374.005005] -0.706488 0.000000 0.000000 -0.707725 run straight to wall, 180 and run back
10:03:29 Your location is: 0xD6990112 [0.425325 178.418182 374.005005] -0.023942 0.000000 0.000000 0.999713
10:03:35 Your location is: 0xD599012C [191.466156 178.372208 374.005005] -0.023942 0.000000 0.000000 0.999713
> suppress server error from bugged cells in asheron's castle

- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
- Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
[See Treestats for example](https://treestats.net/Frostfell/Spqrs%20Mule)
> Adjust Arcane Lore handling in GetTotalSpecializedCredits

- Source/ACE.Server/Factories/Tables/Wcids/Weapons/AtlatlWcids.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/BowWcids_Aluvian.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/BowWcids_Gharundim.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/BowWcids_Sho.cs
- Source/ACE.Server/Factories/Tables/Wcids/Weapons/CrossbowWcids.cs
from pre-t7 data + ace + magloot log archive
> adding post-tod missile weapon chance tables

- Source/ACE.Server/Factories/Tables/Wcids/Weapons/CasterWcids.cs
from pre-t7 data + ace + magloot log archive
> adding post-tod caster weapon chance tables

- Source/ACE.Server/WorldObjects/Player_Xp.cs
This should fix the UpdateXpVitae exception where vitae is null, most likely due to a race condition.
What this does is ensures UpdateXpAndLevel() is called on the players thread.
What this also does though is defer the UpdateXpAndLevel call to later in the same tick, or, the next tick. In the future, i'd like to come up with a system that doesn't defer if the operation can be executed immediately while guaranteeing thread safety.
> Make GrantXp more thread safe

- Source/ACE.Server/WorldObjects/Creature_Death.cs
this fixes a possible null pointer exception if lastDamagerInfo is null
> append hotspot fix

- Source/ACE.Server/Entity/Landblock.cs
- Source/ACE.Server/WorldObjects/Player_Tick.cs
also reduces log spam from untargeted spell projectile waves in neftet
> fix z-pos hacking false positive when jumping into portals w/ airborne destinations

- Source/ACE.Server/Network/NetworkSession.cs
This fixes:  ERROR (ACE.Server.Program) System.InvalidOperationException: Sequence contains no elements
> NetworkSessionExceptionFix

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
s/succesfully/successfully/g
HT @Cyberkiller
> Fix typo in @rename success message

- Database/Updates/Shard/2020-10-20-00-Sync-Level-200-PetDevice-Names.sql
this should be checked in after the db update for the level 200 pet device names
> add shard update script to sync level 200 pet device names

- Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
Hopefully this is this last one....
> Adjustment to Arcane Lore specialization

- Source/ACE.Server/WorldObjects/Creature_Melee.cs
- Source/ACE.Server/WorldObjects/Player_Melee.cs
reverts https://github.com/ACEmulator/ACE/pull/3025
https://youtu.be/gvHtVaWXaR8?t=863
> revert 3025, update two-handed combat cleave distance to be based on CylDist

- Database/Updates/Shard/2020-10-23-00-Update-Rare-ItemCurMana.sql
should be checked in after https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/682
> add missing ItemCurMana fields to rares

- Source/ACE.Server/WorldObjects/Corpse.cs
for https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/695
> add Frozen Cave to nodrop landblocks

- Source/ACE.Server/WorldObjects/Corpse.cs
pk corpses also possibly become open to all after the killer loots, according to jkurs / sapphire / fire chimp
> update pk corpse permissions based on player feedback

- Source/ACE.Server/Factories/PlayerFactory.cs
- if the server is sent attribute values that are less than 10 or greater than 100, previously the server was munging these values, and clamping them to the allowed ranges. it should be returning an error.
- if the server received values of all uint.MaxValue, for example, the character would previously result in the following attributes: 100/100/100/30/0/0, which are invalid values for focus and self
> improved attribute validation

- Source/ACE.Server/Managers/RecipeManager.cs
> update copper/silver salvage to match mutation filter

- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
ce just experienced their first concurrency-related crash from this, after about ~1 year from when this code was added
> adding concurrency support to some projectile setup caches

- Database/Updates/Shard/2020-11-02-00-Grub-TTR.sql
this should be checked in after https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/713 and https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/714
> add cleanup script for grub / pack doll TTR

- Source/ACE.Database/Models/Auth/AuthDbContext.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/Models/World/WorldDbContext.cs
- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Database/ShardDatabaseOfflineTools.cs
- Source/ACE.Server/WorldObjects/Player_Database.cs
- global.json
Resilient Connections have been added.
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections
https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency
some comments have been removed
NoTracking has been added where it was missing
> Misc Database Improvements/Cleanup

- Source/ACE.Server/Factories/WorldObjectFactory.cs
- Source/ACE.Server/WorldObjects/Player.cs
found originally by gmriggs, then submitted via Ripley
> ObjectGuid fixes

- Database/Updates/Shard/2020-11-13-00-T7-T8-Non-Elemental-Caster-Fix-Appraisal-Missing-Level-Req.sql
- Source/ACE.Server/Factories/Entity/MutationCache.cs
- Source/ACE.Server/Factories/Entity/Mutations/Casters/caster_non_elemental.txt
todo: investigate why script compiler was not showing warning
> WieldSkill -> WieldSkillType for t7+ non-elemental casters

- Source/ACE.Server/Network/NetworkSession.cs
race condition between listener thread and NetworkManager parallel threads
> NetworkSession Sequence Exception Fix

- Source/ACE.Server/Factories/LootStats.cs
Added Type of Element for Casters in the TestLootGenCorpse Tables (for Testing to see what elements drop). (its just the name of the caster).
> Added Type of Element for Casters in the TestLootGenCorpse Tables.

- Source/ACE.Server/WorldObjects/Player.cs
synced with spell projectiles, tested
> ensure 2-way collision detection on all missiles

- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/Managers/PropertyManager.cs
this enables the updated loot system by default
> replace updated_loot_system server option w/ legacy_loot_system, disabling by default

- Source/ACE.Server/WorldObjects/Entity/CreatureSkill.cs
- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
these syncs are testable with /showstats, 40% vitae, setting large values for things like Enlightenment, and examination of the client code
> further updates to base vs. current to sync up exactly with client

- Source/ACE.DatLoader.Tests/ACE.DatLoader.Tests.csproj
- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.Database.Tests/ACE.Database.Tests.csproj
- Source/ACE.Database/ACE.Database.csproj
- Source/ACE.Server.Tests/ACE.Server.Tests.csproj
- Source/ACE.Server/ACE.Server.csproj
This is kind of a meh update.
I checked the changelogs and there's really nothing major here.
> Update all the non-EF packages to latest

- Source/ACE.Server/Entity/Tailoring.cs
confirmed with verb in retail, the preliminary tailoring operation would fail
> prevent 'difficult to master' weapons from being turned into unusable intermediate tailoring kits

- Dockerfile
- Dockerfile.arm64
See https://github.com/dotnet/dotnet-docker/issues/2375
> Update Docker files due to NET 5.0 changes

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
- Source/ACE.Server/Factories/LootGenerationFactory.cs
- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- Source/ACE.Server/WorldObjects/Player_Inventory.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Verified proper support using creatures existing in 16PY dataset.
> Wire up proper support for EmoteType.CreateTreasure

- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Spells.cs
- Source/ACE.Server/WorldObjects/Creature_Navigation.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
> legendary cantrips do not add level 180 requirement to items that don't already have a level req

- Source/ACE.Server/WorldObjects/Monster_Melee.cs
thanks to MySpace for reporting this issue!
> fix 27864 - Mosswart Muckstalker + Katar + Kick

- Source/ACE.Server/WorldObjects/Player.cs
similar to previous changes for house recall
> send pkl motion as actions

- Source/ACE.Server/WorldObjects/Player_Xp.cs
from retail info provided by @sLackeR-hub
> apply trinket/aug bonuses to level proportional xp

- Source/ACE.Server/Entity/GeneratorProfile.cs
thanks to TCK for helping to figure this out!
> spawn generated object positions relative to generator orientations to match retail

- docker-compose.arm64
- docker-compose.yml
Limit MySQL to 8.0.21 due to issue with GUID gap query
> Update docker-compose files

- Source/ACE.Database/ShardDatabase.cs
- docker-compose.arm64
- docker-compose.yml
Resolves GUID recapture issue with MySQL 8.0.22+
> Fix query issue with recent MySQL versions

- Source/ACE.Server/Program.cs
This is very useful for anyone running multiple servers on the same machine (particularly windows servers).
> Update console title to show server name

- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
- Source/ACE.Server/WorldObjects/House.cs
- Source/ACE.Server/WorldObjects/HousePortal.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
Corrects bugs with Villa permission propagation, correctly uses OpenToEveryone property instead of Open, and allows all in to basements if OpenToEveryone is true
> Adjust some House permissions

- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
> Partial revert for HouseOwner in CreateObject

- Source/ACE.Database/Models/Shard/CharacterExtensions.cs
- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventCharacterTitle.cs
- Source/ACE.Server/Network/GameEvent/Events/GameEventFriendsListUpdate.cs
- Source/ACE.Server/WorldObjects/Managers/ContractManager.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
This (in addition to the quest thread safety PR), makes the character entity full thread safe.
> Contract registry thread safety

- Source/ACE.Server/Network/Handlers/AuthenticationHandler.cs
- Source/ACE.Server/Network/Session.cs
This fixes a couple of race conditions
> Improve Character Save Process

- Source/ACE.Server/WorldObjects/Player_Magic.cs
test for pvp servers, feedback provided by Curryfury
> verify cast radius during manual movement after windup

- Source/ACE.Server/Managers/RecipeManager.cs
The rare item 'infinite leather' wasn't applying the Retained property to the items
> fix infinite rare leather

- Source/ACE.Server/WorldObjects/Player.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
I'm not too happy with the back/forth state machine, but it's a difficult thing to fix "cleanly" without something like a serial pipeline/work queue that can be manipulated and injected into..
What we're trying to solve are two cases:
1) Player dies and disconnects/logs out during the animation
2) Player starts logout, dies during logout animation
These cases can end up with no corpse being generated and the player not being teleported back to sanctuary
The idea is pretty simple.
We now set isInDeathProcess when Player_Death.Die() is called
We check for isInDeathProcess  in Player.Logout_Inner and LogOut_Final to ensure that the player isn't removed from the world until after isInDeathProcess completes.
This is handled by Player_Death.ThreadSafeTeleportOnDeath() checking for IsLoggingOut …
> Fix corpse creation and player location when dying and logging out at the same time

- Source/ACE.Server/Network/Structure/AppraiseInfo.cs
This fixes items showing up in Mag-Tools mana tracker with a red 'no' symbol
> fixing item appraisal active enchantments missing some spells

- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
Thanks to @TectonicRifts for sharing his recollections of this behavior from retail
It was originally implemented after being mentioned by @dgatewood awhile ago, however it was later commented out since we couldn't find any other confirmation of it being a thing, and also concerns that some players would be able to abuse it.
@TectonicRifts also happened to independently mention it, confirming that it was indeed a thing in retail. He also filled in some missing details that weren't in the original implementation.
> re-enable monster alert logic based on latest info

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
this emote appears to be unused so far in the current world db, so adding this logic before the old branches are called
> adding logic for InqFellowNum

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
- Source/ACE.Server/Entity/Aetheria.cs
- Source/ACE.Server/Factories/LootGenerationFactory_Aetheria.cs
For those who don't have the Chaos Helper plugin installed
> adding /ciaetheria dev command

- Source/ACE.Server/Command/Handlers/DeveloperCommands.cs
Changed `showstats` command to output to game and to include any creature type, not just current player.
> Updated `showstats` command

- Source/ACE.Server/Physics/Common/ObjCell.cs
Don't know what the root cause is yet
> Temp fix to allow physics landblock GC

- Source/ACE.Server/Managers/HouseManager.cs
Added to make it more clear when debug logging what the variables are at time of processing
> Update debug logging for ProcessRent

- Source/ACE.Server/Entity/Fellowship.cs
- Source/ACE.Server/WorldObjects/Player_Fellowship.cs
BowDeep on the recruiter occurs on successful recruitment
> Add motion to Fellowship recruiting

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Co-Authored-By: gmriggs <8909245+gmriggs@users.noreply.github.com>
> Save item on Wield if from sidepack

- Source/ACE.Server/Managers/PropertyManager.cs
- Source/ACE.Server/Network/Enum/WeaponMask.cs
- Source/ACE.Server/Network/Structure/WeaponProfile.cs
defaults to retail value of false
> adding show_ammo_buff server config option

- Source/ACE.Database/ShardDatabase.cs
- Source/ACE.Server/Command/Handlers/CharacterCommands.cs
Changes to the way characters were handled probably broke this command at some point, so now this has been fixed
> Fix deletecharacter admin command

- Source/ACE.Server/WorldObjects/Creature_Combat.cs
- Source/ACE.Server/WorldObjects/Monster_Awareness.cs
Co-Authored-By: gmriggs <8909245+gmriggs@users.noreply.github.com>
> Update Monster AI Tolerance Alert Condition

- Source/ACE.Server/Factories/PlayerFactoryEx.cs
This also removes Olthoi from the heritage picker.
> Fix PlayerFactoryEx to pass verify-player-data

- Source/ACE.Server/WorldObjects/Player_Commerce.cs
CoinValue was not being updated if a single stack is being split and vaporized
> Fix issue with SpendCurrency

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Allow player/client to properly indicate and use splitter ui when giving to NPC
> Adjust GiveObjectToNPC handling

- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
> Match up Burden flag behavior with other similar properties

- Source/ACE.Server/Entity/Spell.cs
- Source/ACE.Server/WorldObjects/Gem.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- Expand the definition of IsImpenBaneType to include Rare impen and bane spell categories
- Unlock protection on method TryCastItemEnchantment_WithRedirects() from protected to public
- Add possibility for ItemEnchantment with redirects from spells cast be gem items
> Rare ImpenBane Support

- Source/ACE.DatLoader/FileTypes/SetupModel.cs
- Source/ACE.Server/WorldObjects/Creature_Missile.cs
- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Co-Authored-By: gmriggs <8909245+gmriggs@users.noreply.github.com>
> Wire up support for RotationSpeed

- Source/ACE.Server/Network/GameEvent/Events/GameEventBookDataResponse.cs
> Adjust GameEventBookDataResponse

- Source/ACE.Database/OfflineTools/Shard/BiotaGuidConsolidator.cs
- Source/ACE.Server/Program.cs
The objective here is to allow some biota consolidation without breaking plugins.
> Add MightBreakPlugins option to BiotaConsolidator

- Source/ACE.Database/SQLFormatters/World/EventSQLWriter.cs
- Source/ACE.Entity/Enum/Properties/PropertyInt.cs
Fix issue with double conversion in comments
> Update SQL Writers

- Source/ACE.Database/ShardDatabase.cs
> Fix issue with rename admin command

- Database/Updates/Shard/2022-01-14-00-Update-Red-Rune-Silveran-Weapons.sql
Biota updates for content PRs 1258 and (a delayed) 1183
> Biota update script for red rune silveran weapon fixes

- Database/Updates/Shard/2022-01-14-01-Update-Shield-of-Perfect-Light.sql
Extremely late biota fix for content PR 950. Possibly too late, but 100% magic absorb is a bit absurd.
> Biota update script for shield of perfect light fix

- Source/ACE.Server/WorldObjects/SpellProjectile.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Thanks to Xenocide for discussing retail data measurements!
> adjust war/void skillMod based on retail data

- Source/ACE.Server/Command/Handlers/AdminCommands.cs
This changes several broadcast commands and the event command to be usable on the console and in game.
> Change scope of some admin commands

- Source/ACE.Entity/Enum/Properties/PropertyDataId.cs
These names were pulled from the ACDM era admin client.
> Added proper enum names to "Guessed" DID properties

- Source/ACE.Server/WorldObjects/WorldObject_Networking.cs
Just changed some logic and added some comments to add clarity to this function. Should result in not actual changes to the game, but should be marginally more efficient of clear.
> Cleaned up CalculateObjDesc()

- Database/Updates/Shard/2022-05-14-00-Fix-Slayer-Damage.sql
- Database/Updates/Shard/2022-05-14-01-Fix-Black-Cloud-Bow.sql
- Database/Updates/Shard/2022-05-14-02-Fix-Exquisite-Lense.sql
- Database/Updates/Shard/2022-05-14-03-Fix-Nether-Society-Orb.sql
- Database/Updates/Shard/2022-05-14-04-Fix-Aegis-of-the-Golden-Flame.sql
- Database/Updates/Shard/2022-05-14-05-Fix-Nekodes.sql
- Database/Updates/Shard/2022-05-14-06-Fix-Gauntlet-Backpacks.sql
Co-Authored-By: Fire-Chimp <49045665+Fire-Chimp@users.noreply.github.com>
> Several Retroactive to Shard Item Fixes

- Source/ACE.Database/Models/Auth/AuthDbContext.cs
- Source/ACE.Database/Models/Shard/ShardDbContext.cs
- Source/ACE.Database/Models/World/WorldDbContext.cs
- Source/ACE.Server/Program_DbUpdates.cs
This may solve issues with SSL Authentication errors some users have experienced
> Add SslMode to SQL connection strings

- Source/ACE.Server/Managers/RecipeManager.cs
ACEmulator/ACE-World-16PY-Patches#1388 has updated data to validate against
> Add ModifyVital to RecipeManager

- Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
According to PDB, Position is not passed in to MoveToPos emote, only Frame data
> Update MoveToPos handling

- Source/ACE.Server/Factories/LootGenerationFactory_Slag.cs
- Source/ACE.Server/WorldObjects/Creature_Death.cs
- Source/ACE.Server/WorldObjects/Player_Death.cs
- Source/ACE.Server/WorldObjects/Player_Properties.cs
wip code from months ago
slag drops from olthoi players killing monsters is the only piece that has really been fleshed out
slag drops from olthoi players killing players is still todo, and has placeholder code
> very basic preliminary framework for slag drops

- Source/ACE.Server/Entity/Tailoring.cs
Log errors if pre-validation some how fails to catch capacity issues
> Pre-Validate Tailoring Intermediates

- Database/Updates/Shard/2022-08-11-00-Fix-Nether-Society-Orb.sql
Needs to be merged after https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1419
> retrofix for Nether Society Orb

- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Thanks to Derpy Mcgavin for reporting this issue
> fix bunny smite

- Source/ACE.Server/WorldObjects/Player_Inventory.cs
Thanks to Boskangeroe for reporting this issue
> fix merging full stack of equipped phials

- Source/ACE.Server/Managers/RecipeManager.cs
Also disallowed crafting when not at peace per weenie errors seen in retail
> Adjust crafting motion

- Source/ACE.Server/Entity/CastSpellParams.cs
- Source/ACE.Server/Entity/MagicState.cs
- Source/ACE.Server/WorldObjects/Player_Magic.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
based on client calculation found in             CACQualities::InqSkillLevel
Thanks to @nwg5817 for finding the bug and resolution
Co-Authored-By: JMAilan <12468698+nwg5817@users.noreply.github.com>
Co-Authored-By: gmriggs <8909245+gmriggs@users.noreply.github.com>
> Adjust calculation of Max Range for Spells

- AppVeyor/AppVeyorBeforePackage.bat
- appveyor.yml
Cloning release zip to ACE.Server.zip for easier direct linking
> Update Appveyor Release Artifacts

- Source/ACE.Database/Adapter/BiotaConverter.cs
Co-Authored-By: Mag-nus <Mag-nus@users.noreply.github.com>
> Catch and Fix NaN floats in Positions

- Source/ACE.Database/Adapter/BiotaConverter.cs
- Source/ACE.Database/Adapter/BiotaUpdater.cs
In the prior checkin, we took care of it in BiotaConverter
> BiotaUpdator Position NaN check

- Database/Updates/Shard/2023-03-01-00-Add-Enchanted-Phial-Pea-Bonded.sql
This update should be run at the same time as https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1492
> add Bonded property to existing Enchanted Platinum Phial Peas

- .gitignore
Config.js was not being ignored due to uppercase C in filename
> adjusted .gitignore file

- Database/Updates/Shard/2023-04-05-00-Add-Empowered-Phial-Pea-Bonded.sql
This should be checked in after https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1526
> more enchanted/empowered phial pea bonding

- Source/ACE.DatLoader.Tests/DatTests.cs
- Source/ACE.DatLoader/Entity/BasePropertyDesc.cs
- Source/ACE.DatLoader/FileTypes/MasterProperty.cs
- Source/ACE.Entity/Enum/BasePropertyType.cs
- Source/ACE.Entity/Enum/PropertyCachingType.cs
- Source/ACE.Entity/Enum/PropertyDatFileType.cs
- Source/ACE.Entity/Enum/PropertyGroupName.cs
- Source/ACE.Entity/Enum/PropertyInheritanceType.cs
- Source/ACE.Entity/Enum/PropertyPropagationType.cs
This is not at all useful for ACE operation, just another file type in the dat to cross off the list.
Contains misc properties and setting vars, and some basic info to go with them (max/min, defaults, and other stuff that appears to be useful or applicable for tools/World Builder)
> Added support for parsing MasterProperty, 0x39000001 in the client_portal.dat

- Database/Updates/Shard/2023-07-25-00-Fix-Geraine-Tomes.sql
Retro-apply attuned/bonded to existing tomes
> Adjust Geraine's Tomes

- Source/ACE.Server/Entity/AddEnchantmentResult.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
- Source/ACE.Server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
- Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Used with checking for player.AugmentationIncreasedSpellDuration
> Add isWeaponSpell to Enchantments

- Database/Updates/Shard/2023-09-02-00-Update-Spell-Hieroglyph-of-Healing-Mastery.sql
should be checked in after https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1582
> update spell on existing Hieroglyph of Healing Mastery items

- Source/ACE.Server/WorldObjects/Entity/CreatureVital.cs
> fix appraisal vital colors for buff/debuff

- Source/ACE.Server/WorldObjects/Player_Spells.cs
> add missing shield mastery to admin /buff command

- Source/ACE.Database/SQLFormatters/Shard/BiotaSQLWriter.cs
- Source/ACE.Database/ShardDatabase.cs
This also fixes the missing order column for BiotaPropertiesPalette
> Improve BiotaSQLWriter for ACLogView

- Source/ACE.Server/WorldObjects/Corpse.cs
source: infallible player memories
> player corpse FFA after first open

- Source/ACE.Server/Entity/Fellowship.cs
Thanks to @aquafir for reporting this issue!
> update hardcoded literal in Fellowship.AddConfirmedMember to proper const

- Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
Verifies enchantment registry has correct StatModType flags for Beneficial spells and optionally fixes
Fixes #4138
> Add verify-beneficial-enchantments command

- Dockerfile
- Dockerfile.arm64
- docker-compose.arm64
- docker-compose.yml
8.0-jammy-chiseled is a little too slim for ace as currently built and executed
> Switch docker images

- Dockerfile
- Dockerfile.arm64
Based on recommendations found at https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/
> More net8 Docker changes

- Source/ACE.Server/WorldObjects/Monster_Combat.cs
BPTableCache can be accessed by multiple threads at the same time.
> Fix Monster_Combat concurrency issue

- Source/ACE.Server/Command/Handlers/AdminStatCommands.cs
- Source/ACE.Server/Entity/LandblockGroup.cs
- Source/ACE.Server/Managers/LandblockManager.cs
> lbgroupstats

- Source/ACE.Server/Managers/LandblockManager.cs
This should help reduce the lock contention (usually by lscape) with minimal impact to performance.
> Switch LandblockManager from lock to ReaderWriterLockSlim

- Source/ACE.Database/ACE.Database.csproj
> Revert "Bump Pomelo.EntityFrameworkCore.MySql and Microsoft.EntityFrameworkCore in /Source"

- Source/ACE.Server/Managers/PlayerManager.cs
- Source/ACE.Server/WorldObjects/Player_Character.cs
- Source/ACE.Server/WorldObjects/Player_Networking.cs
Friends will now send broadcast text to announce their online status as was the case in retail.
> Improve Friends Notifications

- Source/ACE.DatLoader.Tests/DatTests.cs
- Source/ACE.DatLoader/Entity/ActionMapValue.cs
- Source/ACE.DatLoader/Entity/InputMapConflictsValue.cs
- Source/ACE.DatLoader/FileTypes/ActionMap.cs
- Source/ACE.DatLoader/FileTypes/UserBindingValue.cs
- Source/ACE.Server/Program.cs
Added dat handling for 0x26000000 Action Map from client_portal.dat
> DatReader - ActionMap

- Source/ACE.DatLoader/ACE.DatLoader.csproj
- Source/ACE.Database/ACE.Database.csproj
- Source/ACE.Server/ACE.Server.csproj
This reverts commit 836837bf3c846f6a58ffb2dda9dfc40aa42f8dc1.
> Revert "Bump log4net from 2.0.17 to 3.0.0 in /Source (#4227)"

- Source/ACE.Server/Managers/HouseManager.cs
- Source/ACE.Server/Network/Structure/HouseData.cs
- Source/ACE.Server/Network/Structure/HouseProfile.cs
- Source/ACE.Server/WorldObjects/House.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
Adjusted some logging and added a parentlink for slumlord to house.
> Set House ParentLink on Load

- Database/Updates/Shard/2025-03-09-00-Fix-Renegade-Kalindans.sql
> Biota updates for PR 1733 Renegade Kalindan Fix

- Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs
Thanks to @OptimShi for tracking retail / wiki information
https://asheron.fandom.com/wiki/Spectral_Fountain_Sip
> add support for negative HealOverTime spells

- Source/ACE.DatLoader/FileTypes/RenderTexture.cs
- Source/ACE.Entity/Enum/TextureType.cs
Updating some unknowns in RenderTexture dbobj
> Add DataCategory / TextureType to dat RenderTexture obj

- Source/ACE.DatLoader/Entity/CBldPortal.cs
Also matches existing https://github.com/ACEmulator/ACE/blob/master/Source/ACE.DatLoader/Entity/CellPortal.cs#L14
> match CBldPortal.PortalSide up to client

- Source/ACE.Common/OfflineConfiguration.cs
- Source/ACE.Server/Config.js.docker
- Source/ACE.Server/Config.js.example
- Source/ACE.Server/WorldObjects/Player_Networking.cs
Removed duplicate words from the following files:
- Source/ACE.Common/OfflineConfiguration.cs - line 63
- Source/ACE.Server/Config.js.docker - line 216
- Source/ACE.Server/Config.js.example - line 217
- Source/ACE.Server/WorldObjects/Player_Networking.cs - line 27
> Removed the duplicate "the" words from the comments

- Database/tools/CompileAuthenticationBase.sh
- Database/tools/DockerCompileAuthenticationBase.sh
- Database/tools/DockerExportShardBase.sh
- Database/tools/DockerExportWorldBase.sh
- Database/tools/ExportAuthenticationBase.sh
- Database/tools/ExportShardBase.sh
- Database/tools/ExportWorldBase.sh
- Database/tools/RebaseShardBase.sh
- Database/tools/RebaseWorldBase.sh
- README.md
Added .sh scripts for Linux/macOS users for DB export and rebase.
> Database tooling additions for Linux/macOS users

- Database/tools/CompileAuthenticationBase.sh
- Database/tools/DockerCompileAuthenticationBase.bat
- Database/tools/DockerCompileAuthenticationBase.sh
- Database/tools/DockerExportShardBase.bat
- Database/tools/DockerExportShardBase.sh
- Database/tools/DockerExportWorldBase.bat
- Database/tools/DockerExportWorldBase.sh
Modify file to correct 'acedb' to 'ace-db' to conform with docker-compose.yml and docker.env
> Fix DB Tools to Reference correct DB container name.

- Source/ACE.Server/Managers/GuidManager.cs
- Source/ACE.Server/Managers/HouseManager.cs
- Source/ACE.Server/WorldObjects/Player_House.cs
These are changes from PR #4199 which support outputting certain metrics that do not currently exist in ACEmulator.
These changes allow for the original PR to change to a simple Mod found at [ACEmulator/ACE.Mods.Metrics](https://github.com/ACEmulator/ACE.Mods.Metrics)
> Minimal changes to support metrics mod
